### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by aidansalvi** [AgoraIO-Extensions/react-native-agora#260]
Can you screen share using this library?

**Comment by LichKing-2234** [comment]
you can refer to this doc, and add it to your native layer.
https://docs.agora.io/en/Interactive%20Broadcast/screensharing_android?platform=Android

**Comment by garvitdelhi** [comment]
@LichKing-2234 do you have an example app we can refer too? Thanks!

**Comment by adityaddy** [comment]
@garvitdelhi @aidansalvi  Did you guys got something on this? if not, @LichKing-2234 could you please refer to an example App

**Comment by arya-man** [comment]
Been struggling for a while, could you please share your solution @garvitdelhi @aidansalvi

**Comment by LichKing-2234** [comment]
sure, the example here.
https://github.com/AgoraIO/Advanced-Video/tree/dev/win-screenshare/Screensharing/Agora-Screen-Sharing-Android
https://github.com/AgoraIO/Advanced-Video/tree/master/iOS&macOS/Agora-Screen-Sharing

**Comment by Amazing1974** [comment]
@LichKing-2234
thanks for sharing examples.
but can you explain how to add this to react native app?
Thanks

**Comment by plutoless** [comment]
@Amazing1974 the above links have been deprecated. please look at https://github.com/AgoraIO/API-Examples for potential guidance with native sdk

**Comment by Amazing1974** [comment]
@plutoless
thank you.
can i use this in react native?

**Comment by lniass** [comment]
@plutoless , are you sure this will work for react native? The question was to find a screensharing solution for react-native

**Comment by rmc3408** [comment]
@aidansalvi  Did you found solution for screen sharing?

**Comment by Jeopardous** [comment]
I am not able to write it on the native layer and not able to create bridge for the same. could anyone help me ?😔
