### ISSUE TITLE
localStream.muteVideo() from agora-rtc-sdk is not handled correctly in react-native-agora

### ISSUE THREAD

**Issue by sebazh** [AgoraIO-Extensions/react-native-agora#343]
Hi guys. Thank you this awesome package. We develop application with video calls across web and mobile applications. 
We use agora-rtc-sdk@3.4.0 for web and react-native-agora@3.3.2 for mobile

We faced with the following issue: when web app calls localStream.muteVideo() on their side - "RemoteVideoStateChanged" event is triggered in mobile app two times every second with the following values:
- VideoRemoteState.Stopped && VideoRemoteStateReason.RemoteMuted
- VideoRemoteState.Decoding && VideoRemoteStateReason.RemoteUnmuted

So there is no way to handle mute/unmute of remote video. 
(Btw event "UserMuteVideo" is also triggered every second with muted values: true/false and it's not triggered when user unmutes his video)

Then if user in web app unmutes his video - nothing is triggered in mobile app

Everything works fine with calls between web to web and mobile to mobile

Could you point me how to fix that, thanks

**Comment by RoJoHub** [comment]
> Hi guys. Thank you this awesome package. We develop application with video calls across web and mobile applications.
> We use agora-rtc-sdk@3.4.0 for web and react-native-agora@3.3.2 for mobile
> 
> We faced with the following issue: when web app calls localStream.muteVideo() on their side - "RemoteVideoStateChanged" event is triggered in mobile app two times every second with the following values:
> 
> * VideoRemoteState.Stopped && VideoRemoteStateReason.RemoteMuted
> * VideoRemoteState.Decoding && VideoRemoteStateReason.RemoteUnmuted
> 
> So there is no way to handle mute/unmute of remote video.
> (Btw event "UserMuteVideo" is also triggered every second with muted values: true/false and it's not triggered when user unmutes his video)
> 
> Then if user in web app unmutes his video - nothing is triggered in mobile app
> 
> Everything works fine with calls between web to web and mobile to mobile
> 
> Could you point me how to fix that, thanks



---

Maybe you might need to distinguish between channels and uids?
This problem is solved in this example.

```
rtcChannel.addListener(
      'RemoteVideoStateChanged',
      (uid, state, reason, elapsed) => {
        console.info('RemoteVideoStateChanged', uid, state, reason, elapsed);
        if (state === VideoRemoteState.Starting) {
          if (channelId === channelId0) {
            this.setState({ remoteUid0: [...this.state.remoteUid0, uid] });
          } else if (channelId === channelId1) {
            this.setState({ remoteUid1: [...this.state.remoteUid1, uid] });
          }
        } else if (state === VideoRemoteState.Stopped) {
          if (channelId === channelId0) {
            this.setState({
              remoteUid0: this.state.remoteUid0.filter(
                (value) => value !== uid
              ),
            });
          } else if (channelId === channelId1) {
            this.setState({
              remoteUid1: this.state.remoteUid1.filter(
                (value) => value !== uid
              ),
            });
          }
        }
      }
    );
```

**Comment by sebazh** [comment]
@RoJoHub Thank you for your answer. But i think you got me wrong. We have only one channel. The problem is that:
- when web app calls muteVideo() - mobile app starts to behave weird: RemoteVideoStateChanged event is triggered every second two times with values like video was just muted and then immediately unmuted

> VideoRemoteState.Stopped && VideoRemoteStateReason.RemoteMuted
> and 
> VideoRemoteState.Decoding && VideoRemoteStateReason.RemoteUnmuted

- when web app calls unmuteVideo() - nothing is triggered in mobile app

Everything works fine for calls between web and web, mobile and mobile. Issue happens only in calls between web and mobile

Here is how web creates stream: 
```
this._localStream = AgoraRTC.createStream({
        streamID: uid,
        audio: true,
        video: true,
        screen: false,
      });
```

Let me know if you need additional reproducing steps. Could someone help to fix the issue please. It's very critical for us

**Comment by RoJoHub** [comment]
We are looking into the problem now. Just a moment, please

**Comment by RoJoHub** [comment]
> @RoJoHub Thank you for your answer. But i think you got me wrong. We have only one channel. The problem is that:
> 
> * when web app calls muteVideo() - mobile app starts to behave weird: RemoteVideoStateChanged event is triggered every second two times with values like video was just muted and then immediately unmuted
> 
> > VideoRemoteState.Stopped && VideoRemoteStateReason.RemoteMuted
> > and
> > VideoRemoteState.Decoding && VideoRemoteStateReason.RemoteUnmuted
> 
> * when web app calls unmuteVideo() - nothing is triggered in mobile app
> 
> Everything works fine for calls between web and web, mobile and mobile. Issue happens only in calls between web and mobile
> 
> Here is how web creates stream:
> 
> ```
> this._localStream = AgoraRTC.createStream({
>         streamID: uid,
>         audio: true,
>         video: true,
>         screen: false,
>       });
> ```
> 
> Let me know if you need additional reproducing steps. Could someone help to fix the issue please. It's very critical for us
Hi, friend. 
As you said, the problem does exist.
We will step up efforts to solve this problem.

Thanks for you issue.

**Comment by avaromatias** [comment]
Any solution? I have the same problem
