### ISSUE TITLE
Audience users cannot route audio to the earpiece in the LiveBroadcasting profile

### ISSUE THREAD

**Issue by louxinbo** [AgoraIO-Extensions/react-native-agora#375]
I know it's designed like this, as mentioned in the [documentation](https://docs.agora.io/en/Video/API%20Reference/react_native/classes/rtcengine.html#setenablespeakerphone)
>This method (`setEnableSpeakerphone`) is invalid for audience users in the LiveBroadcasting profile.

This method seems to be working fine for audience users who use ios app.

Does anyone know why agora disable audience users to do it? Is there any workaround?
Thanks

**Comment by LichKing-2234** [comment]
@plutoless maybe you can answer this?
