### ISSUE TITLE
Local View is not showing after joining the call as  Live

### ISSUE THREAD

**Issue by iranu** [AgoraIO-Extensions/react-native-agora#388]
My app has two roles, one is as broadcaster and other is as audience , when I join the channel as a broadcaster from Android and then join from other iPhone on same channel as a Audience my local view is not showing on the audience device(iPhone) and remote not showing on Android.

When I join from Android as a audience it is showing blank screen but audio is coming properly. I am using the code from here.

Audience and broadcaster are not visible at the same time on both the screen.

[](https://docs.agora.io/en/Video/start_live_react_native?platform=Android)

Let me know what is wrong.

**Comment by LichKing-2234** [comment]
have you tried our example?

**Comment by iranu** [comment]
Yes only one view is visible at a time, I want to see broadcaster and audience on same screen.

**Comment by LichKing-2234** [comment]
audience has no stream.
