### ISSUE TITLE
Show incoming call

### ISSUE THREAD

**Issue by nero2009** [AgoraIO-Extensions/react-native-agora#389]
Please I have been able to implement calling feature using agora but how can I show incoming call screen when a call is initiated ?

I saw a suggestion to use CallKit and PushKit on iOS, ConnectionService and Firebase Cloud Messaging on Android, but I dont know how this can be integrated into a react native app.

Please any help would be nice

**Comment by LichKing-2234** [comment]
add it to the native layer.

**Comment by Thierry-Santos** [comment]
For Android you can use this (easy and fast to use for first understanding): https://github.com/bkdev98/react-native-incoming-call#readme, using normal push notifications for trigger the callback, but iOS you have to use CallKit with callkeep on React-Native: https://github.com/react-native-webrtc/react-native-callkeep
