### ISSUE TITLE
How to remove the user from the channel when app is terminated

### ISSUE THREAD

**Issue by iamgouravturka** [AgoraIO-Extensions/react-native-agora#391]
Is there any listener that listens when the app is terminated or killed ??

**Comment by LichKing-2234** [comment]
remove the local user or a remote user?

**Comment by iamgouravturka** [comment]
Remote user

**Comment by LichKing-2234** [comment]
you can use the RestfulAPI to control the channel.

**Comment by iamgouravturka** [comment]
How do I know when my app is terminated

**Comment by LichKing-2234** [comment]
if the app is terminated, the user will be removed.

**Comment by iamgouravturka** [comment]
suppose you have a group of users in the agora room (video chat) if my app is terminated then I need to leave forcefully all the users from the room

**Comment by LichKing-2234** [comment]
you can use socket to let your server know the user is left, then request the restful API on your server.

**Comment by iamgouravturka** [comment]
great I already do this socket and restful work but the problem is how I know the app is terminated because appStates gives me 'inactive' and 'background' state but not the terminated or killed state

**Comment by LichKing-2234** [comment]
You can not know when the app is terminated, But you can set the status to terminated if the socket is disconnected after a while.

**Comment by iamgouravturka** [comment]
I'm using socket io . I used both keyword disconnect and disconnected like this:
this.socket.on('disconnect, (reason) => {
          console.log('------reason', reason);
          console.log('-------disconnected');
        });
        
        but nothing happens

**Comment by LichKing-2234** [comment]
pls make sure check connection status on your server.
