### ISSUE TITLE
The remote video quality very poor, only freezing

### ISSUE THREAD

**Issue by ys1610** [AgoraIO-Extensions/react-native-agora#396]
await this.engine.setVideoEncoderConfiguration(
      new VideoEncoderConfiguration({
        dimensions: new VideoDimensions({
          width: 1280,
          height: 720,
        }),
        bitrate: 1,
        frameRate: VideoFrameRate.Fps30,
        degradationPrefer: 0,
      }),
    );

**Comment by LichKing-2234** [comment]
why set the bitrate to 1? pls refer to our document.

https://docs.agora.io/en/Interactive%20Broadcast/faq/video_profile?platform=Android

**Comment by ys1610** [comment]
Can I set bitrate more than 2760?
