### ISSUE TITLE
No .XCFramework included in iOS native SDK

### ISSUE THREAD

**Issue by hahtml** [AgoraIO-Extensions/react-native-agora#406]
After upgraded `react-native-agora` from 3.3.1 to 3.4.6 and run `pod install`, there is no `.XCFramework` included in pods. Then I manually download `AgoraRtcEngine_iOS` SDK and find it was removed at some point in 3.3.x. Therefore, we could not run the app which embeds Agora service in the simulator. However, there is no hints in Docs for such changes.

Could we add .XCFramework back?

**Comment by LichKing-2234** [comment]
For some reason, we only provide the framework now.

You can try to set this config to true.
![image](https://user-images.githubusercontent.com/9312526/132156277-b48c45c8-af93-4cf7-9661-eca76453298f.png)

**Comment by medlJeremy** [comment]
@hahtml I ran into the same issue. Replacing all the `.XCFramework` files with the `.framework` files of the same name got the app to build for me, but it would crash on launch. The top of the console output will have the name of a missing framework. I had to add the missing framework, rebuild and repeat until it the app ran. hope that helps
