### ISSUE TITLE
Degrading the minsdkversion  in react-native

### ISSUE THREAD

**Issue by AjithKumarRaviChandran** [AgoraIO-Extensions/react-native-agora#408]
I have integrated the react-native- agora rtc for the video call feature in our app, when we are trying to build the app with the minsdkversion 16 its throwing error that we need minsdkversion 24 to use the package, so is there any way to degrade the minsdkversion support?

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO-Community/react-native-agora/blob/master/android/build.gradle#L32

**Comment by LichKing-2234** [comment]
the minsdkversion is 16

**Comment by LichKing-2234** [comment]
maybe other reason?
