### ISSUE TITLE
Unable to run pod install command

### ISSUE THREAD

**Issue by ujwalshrestha** [AgoraIO-Extensions/react-native-agora#410]
I am trying to run the sample app . However , while running pod install command i get the following error:

```
[!] There are multiple dependencies with different sources for `react-native-agora` in `Podfile`:

- react-native-agora (from `../node_modules/react-native-agora`)
- react-native-agora (from `../..`)
```

**Comment by LichKing-2234** [comment]
have you followed https://github.com/AgoraIO-Community/react-native-agora/blob/master/example/README.md?

you did not need to npm install `react-native-agora` in our example, it has been installed locally.

**Comment by ujwalshrestha** [comment]
I have installed `react-native-agora`  , after that i have run pod install command

**Comment by LichKing-2234** [comment]
> I have installed `react-native-agora` , after that i have run pod install command

Sorry, I mean should not install `react-native-agora`

pls follow the README.md in the example folder.
