### ISSUE TITLE
RemoteVideoStateChanged and RemoteAudioStateChanged is not working

### ISSUE THREAD

**Issue by AjithKumarRaviChandran** [AgoraIO-Extensions/react-native-agora#415]
I have integrated the agora videocall to my project using the Rtcengine, and i am getting response for the joinchannel success and failed status, but RemoteVideoStateChanged and RemoteAudioStateChanged is not throwing any output also i want to know how to use the RtcEngineEvents to get the status of remote events.

**Comment by LichKing-2234** [comment]
have you tried our example?

**Comment by AjithKumarRaviChandran** [comment]
@LichKing-2234 can you share the example file or link, i have tried the code from the github.

**Comment by LichKing-2234** [comment]
in the example fold at this repo.

**Comment by AjithKumarRaviChandran** [comment]
I tried this example only @LichKing-2234 , but still i didn't got any response from the callback, can you share any working example.

**Comment by LichKing-2234** [comment]
pls double-check your appid and token.

**Comment by AjithKumarRaviChandran** [comment]
@LichKing-2234 As i mentioned in my first Comment, i am getting the Joinchannel and other callback responses using the same appid and token, but RemoteVideoStateChanged and RemoteAudioStateChanged callbacks are not returning any responses.


https://github.com/AgoraIO-Community/react-native-agora/issues/343 you can check this one, some people  have already raised the issue for the same.

**Comment by LichKing-2234** [comment]
the other client is web?

**Comment by AjithKumarRaviChandran** [comment]
Yes, the other client is from web

**Comment by Laviniaxyz** [comment]
Any updates on this issue? I'm facing the same problem as @AjithKumarRaviChandran

**Comment by LichKing-2234** [comment]
is working using two ReactNative client?

**Comment by Laviniaxyz** [comment]
> is working using two ReactNative client?

No, I have tried with 2 react native clients and but the callback RemoteVideoStateChanged is not triggered...

**Comment by LichKing-2234** [comment]
is our example working?
