### ISSUE TITLE
Is it possible to add custom components to video stream?

### ISSUE THREAD

**Issue by sebazh** [AgoraIO-Extensions/react-native-agora#416]
Hi guys. Thank you for this awesome package
I have a question: is it possible to add some screen elements like chat messages or other components to default camera output stream, which we further record using Cloud recording API?

I found "setExternalVideoSource" in the Agora docs for android, but it seems to be not maintained in react native package. 
Could you hint how to add Chat to recordered video file please?

**Comment by LichKing-2234** [comment]
you shoud implement it on the native      layer.
