### ISSUE TITLE
Unable to connect to React-Native Voice Call on iPhone se2

### ISSUE THREAD

**Issue by giftsets** [AgoraIO-Extensions/react-native-agora#425]
We implemented voice call and video call using Agora SDK for React-native. 

However, in iPhone se2, both voice call and video call do not work. All other phones are working fine. 
I wonder if agora react-native sdk has restrictions for each device. 
I can't find any mention of device specific or os specific restrictions on the official site. 
If you have that link, please share.

Thank you.

**Comment by LichKing-2234** [comment]
have you tried our example?

**Comment by LichKing-2234** [comment]
pls provide our SDK log, the we can confirm it.

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Interactive%20Broadcast/faq/logfile
