### ISSUE TITLE
Video SDK v4.0.0 integration

### ISSUE THREAD

**Issue by gtsopour** [AgoraIO-Extensions/react-native-agora#432]
Hello guys,
is there any specific plan for the Video SDK v4.0.0 integration? We are interested on integrating/adding the enableExtensionWithVendor() and setExtensionPropertyWithVendor() interfaces on top.

Thanks in advance.
George

**Comment by LichKing-2234** [comment]
web SDK?

**Comment by gtsopour** [comment]
No I mean React Native integration with the Video SDK v4.0.0 Preview https://docs.agora.io/en/All/downloads?platform=All%20Platforms. Currently react-native-agora.podspec has a dependency only to s.dependency "AgoraRtcEngine_iOS", "3.5.0.4".
At this version, AgoraRtcEngineKit does not provide yet the enableExtensionWithVendor and setExtensionPropertyWithVendor interfaces. What I am trying to do is to bring this integration https://www.banuba.com/faq/how-to-integrate-banuba-sdk-with-agora-sdk to React Native.

**Comment by gtsopour** [comment]
Hello @LichKing-2234,
sorry to ping you again but it's really critical this feature for us. Is there actually any plan for this Video SDK v4.0.0 integration or are we missing something in our end?

Thanks in advance for your support.
George

**Comment by LichKing-2234** [comment]
We have made a new SDK for v4.0.0, but it is an alpha version. you can connect to our support team to get more infomation.
