### ISSUE TITLE
Android video feed does not stop when app is backgrounded

### ISSUE THREAD

**Issue by P-Russell** [AgoraIO-Extensions/react-native-agora#435]
Hello,

We have an issue when a user is in a video call, they then move to another app, the video feed still continues.

Is there a way to explicitly prevent this?

Thank you.

**Comment by LichKing-2234** [comment]
foregroud

**Comment by P-Russell** [comment]
Hello @LichKing-2234 

Once the app is foregrounded the video call still continues uninterrupted.

**Comment by LichKing-2234** [comment]
You can listen to the event of the app enter background, then you can call `enableLocalVideo` and `muteAllRemoteVideoStreams` to control the local and remote video.
