### ISSUE TITLE
Device heating on IOS

### ISSUE THREAD

**Issue by sebazh** [AgoraIO-Extensions/react-native-agora#438]
react-native-agora: "3.4.7"

Hi guys. Thank you for this awesome package. 
We faced with a problem of device heating on ios reported by our clients during long audio and video calls (heating becomes noticeable after 5-10 minutes of call). Only RtcLocalView is displayed on this screen (fullscreen render)

Is it intended to have 50-60% CPU usage on iPhone X during such calls?
Screenshots from XCode Debug navigator attached
<img width="1167" alt="Screenshot 2021-11-08 at 14 49 56" src="https://user-images.githubusercontent.com/51706160/140767297-87934870-bea0-48d6-8530-3b22f6422780.png">
<img width="1173" alt="Screenshot 2021-11-08 at 14 53 37" src="https://user-images.githubusercontent.com/51706160/140767323-31812351-eaf4-4779-b103-51ef092f7cb1.png">

Could you point what might be wrong please or is it normal behaviour?
Thanks in advance

**Comment by LichKing-2234** [comment]
Could you pls provide the SDK log?

**Comment by sebazh** [comment]
@LichKing-2234 Thank you for your reply. Here is SDK log:
[agorasdk.log](https://github.com/AgoraIO-Community/react-native-agora/files/7503819/agorasdk.log)
