### ISSUE TITLE
setCameraCapturerConfiguration throws error on android

### ISSUE THREAD

**Issue by sebazh** [AgoraIO-Extensions/react-native-agora#443]
Hi guys.

Trying to solve the issue with heating device during long video call. The function `setCameraCapturerConfiguration` throws the following error on android: `Error: null cannot be cast to non-null type kotlin.Number`

Calling this function before joinChannel and enableVideo calls:
```
await this.engine.setCameraCapturerConfiguration({
	preference: CameraCaptureOutputPreference.Performance,
});
```

react-native-agora: 3.5.1

Please help to solve that,
thanks in advance

**Comment by LichKing-2234** [comment]
Sorry, `cameraDirection` is a required param, but it is an issue, Will be fixed the next version.
