### ISSUE TITLE
Is that possible to listen to my own voice in real-time to check how it sounds for my listeners? 

### ISSUE THREAD

**Issue by kolyuchii** [AgoraIO-Extensions/react-native-agora#457]
**Problem**
While live casting I'd like to have the ability to check how sound my own voice. Especially when some voice changes are applied.

The possible solution might be to plug in the headphones and press the button to listen to me only.

Is that or something like this possible?

Thanks!

**Comment by LichKing-2234** [comment]
Using `enableInEarMonitoring`

**Comment by kolyuchii** [comment]
Many thanks!!

**Comment by kolyuchii** [comment]
> Using [`enableInEarMonitoring`](https://github.com/AgoraIO-Community/react-native-agora/blob/master/src/common/RtcEngine.native.ts#L2214)

Is that possible to listen to the modified voice?
For example: after calling the setLocalVoicePitch I'd like to check it
