### ISSUE TITLE
Cannot record livestream with mobile's resolution

### ISSUE THREAD

**Issue by lamlengend98** [AgoraIO-Extensions/react-native-agora#463]
I want to record livestream when started on mobile, but dimension provided by react native agora just are 4:3 or 16:9
How can i use mobile dimension like 720x1280 or something like that?

**Comment by lamlengend98** [comment]
@LichKing-2234 can u take a look?

**Comment by LichKing-2234** [comment]
using cloud record?

**Comment by lamlengend98** [comment]
> using cloud record?

yes

**Comment by lamlengend98** [comment]
@LichKing-2234 any solution?

**Comment by Aries112233** [comment]
You can set the size you want to record in the API ‘transcodingConfig ’ of the start request of the recording. If it is 4:3, Please try to set it to 1024*768.

**Comment by lamlengend98** [comment]
> You can set the size you want to record in the API ‘transcodingConfig ’ of the start request of the recording. If it is 4:3, Please try to set it to 1024*768.

@Aries112233 i mean, i want to record with mobile size, like 768*1024, etc

**Comment by lamlengend98** [comment]
@LichKing-2234 can u support me this issue?
