### ISSUE TITLE
joinChannelWithUserAccount does not register user

### ISSUE THREAD

**Issue by yanzdog** [AgoraIO-Extensions/react-native-agora#468]
Hello! `RtcRemoteView` seems to only support Int uid. However our app uses string uuids to manage users.

By referring to https://github.com/AgoraIO-Community/react-native-agora/issues/338, I used `joinChannelWithUserAccount` to join channel and `getUserInfoByUserAccount` to retrieve mapped int uids of remote users but the response is always undefined.

Local user joining channel (broadcaster)

```
AgoraEngine.joinChannelWithUserAccount(token, channelId, remoteUser.uuid, null)
```

Getting remote user's uid (audience)

```
AgoraEngine.addListener("JoinChannelSuccess", async (channel, uid, elapsed) => {
  const res = await AgoraEngine.getUserInfoByUserAccount(remoteUser.uuid)
  console.log(res) # this prints undefined. seems like user is not registered 
});
```

`LocalUserRegistered` callback is fired successfully after `joinChannelWithUserAccount`

```
AgoraEngine.addListener("LocalUserRegistered", (uid, userAccount) => {
   console.log(uid) # this prints int uid
   console.log(userAccount) # this print user's uuid
})
```

Am I missing something? Do I need to call `registerLocalUserAccount` before `joinChannelWithUserAccount` ? According to document (https://docs.agora.io/en/live-streaming/API%20Reference/react_native/v3.5.0/classes/rtcengine.html#registerlocaluseraccount), it seems like either should work.

Any help would be much appreciated! Thanks a lot in advance!

**Comment by LichKing-2234** [comment]
You should call `getUserInfoByUserAccount` after `UserJoined` event received.

**Comment by yanzdog** [comment]
@LichKing-2234 

Thanks for the reply! I will try it!
