### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by CMLCNL** [AgoraIO-Extensions/react-native-agora#475]
We get such an error when we wait for close to 1 minute on a channel alone. 
We are getting this error when calling for someone. We have an application that works like Whatsapp

[agorasdk.log](https://github.com/AgoraIO-Community/react-native-agora/files/8049462/agorasdk.log)
.

**Comment by LichKing-2234** [comment]
Sorry for the late reply, have you tried our example?
