### ISSUE TITLE
method stopAudioMixing is not working on Android

### ISSUE THREAD

**Issue by siyahulhaq** [AgoraIO-Extensions/react-native-agora#477]
I had used `_rtcEngine.startAudioMixing(<URL>, true, false,-1)` and started audio mixing working properly but it's not stopping when I use `_rtcEngine.stopAudioMixing()` method the issue only persist on android not in IOS, In IOS working as I expected. Please try to fix it soon.

**Comment by LichKing-2234** [comment]
Sorry for the late reply, could you pls provide the SDK log file?
