### ISSUE TITLE
Does it provide stereo function?

### ISSUE THREAD

**Issue by Saehanseul** [AgoraIO-Extensions/react-native-agora#479]
Hello, i'm using react-native-agora 3.5.3.
and I setted like below.

`
this._engine.setAudioProfile(
      AudioProfile.MusicHighQualityStereo,
      AudioScenario.GameStreaming,
    )
`

but I can't send and receive stereo.

I made ticket and ask at agora-support and they replied like below.

> Quick update, as we took a detailed review on this topic, for your request, we believe you will need to configure custom audio source under react-native SDK in order to use stereo input.
> 
> Hope this information helps you,

How to using stereo with react-native-agora???

**Comment by plutoless** [comment]
i would like to understand your definition of stereo and how did you determine that it is not doing it?

**Comment by Saehanseul** [comment]
We are testing like this video: https://www.youtube.com/watch?v=6TWJaFD6R2s
We are testing audio interface with seperating left mic and right mic.

At the web(AgoraRTC_N-4.7.3), when broadcaster speak to left mic, app and web listener both can listen only left side.
But at the App("react-native-agora": "^3.5.3",), when broadcaster speak to left mic, app and web listener both listen left and right side same like mono input. 

I think this is bug because agora provide stereo type: **AudioProfile.MusicHighQualityStereo**
but it's not working stereo. just working same like mono type.
