### ISSUE TITLE
How to add borderRadius to RtcLocalView.SurfaceView ?

### ISSUE THREAD

**Issue by emmanuel-D** [AgoraIO-Extensions/react-native-agora#480]
How to add `borderRadius` to `RtcLocalView.SurfaceView` in React Native ?
I tried the following code, but the video is still **square** without rounded border :

```
<RtcLocalView.SurfaceView
    channelId={roomParticipant.roomId}
    renderMode={VideoRenderMode.Hidden}
    zOrderMediaOverlay={false}
    zOrderOnTop={false}
    style={{width: 65, height: 65, borderRadius: 55}}
/>
```

**Comment by LichKing-2234** [comment]
pls try textureview

**Comment by emmanuel-D** [comment]
Yess, this works on Android.
But on iOS, the `RtcLocalView.TextureView` is not allowed (Also mentioned in Agora docs).

**Comment by LichKing-2234** [comment]
You can check the platform and use the different widgets.

**Comment by rahulnainwalttn** [comment]
How to add border radius on Texture View.
<RtcTextureView
                canvas={{ uid: attendeeId }}
                style={[styles.videoPreview, { overflow: 'hidden' }]}
                surf
              />
