### ISSUE TITLE
TypeError when using expo 44 and AgoraUIKit

### ISSUE THREAD

**Issue by vladis-c** [AgoraIO-Extensions/react-native-agora#489]
Hi!

I am trying to follow the tutorial from https://www.agora.io/en/blog/building-a-video-calling-app-using-the-agora-sdk-on-expo-react-native/  with expo 44. 

When running I get an error: 
![image](https://user-images.githubusercontent.com/93081212/165069971-6afdc5c0-9d65-43c6-be6e-dee15d70128f.png)

I tried downgrading to expo 42, and it did not work. 

Please, Help! Thank you. 🙏

**Comment by LichKing-2234** [comment]
have you using expo-dev-client?

**Comment by LichKing-2234** [comment]
if not you can refer to https://github.com/AgoraIO-Community/react-native-agora/issues/188

**Comment by lamphq-krrish** [comment]
expo-dev-client is not helping.

**Comment by LinusU** [comment]
This is not working for me either, I'm building via [EAS](https://expo.dev/eas), specifically `eas build --platform=ios --profile=development`.

I think that for this to work with EAS there needs to be a [config plugin](https://docs.expo.dev/guides/config-plugins/) added to this package?

**Comment by LinusU** [comment]
My error is slightly different though:

```text
TypeError: null is not an object (evaluating 'AgoraRTM.prefix')
```

**Comment by LinusU** [comment]
Ah, the problem was that I had to run:

```sh
npm install agora-react-native-rtm
```

Following the blog post linked above I had only installed `react-native-agora` and `agora-rn-uikit`

**Comment by brytoz** [comment]
i had similar problems as yours @LinusU 

`TypeError: null is not an object (evaluating 'AgoraRTM.prefix')`

**Comment by EkaanshArora** [comment]
We have updated the UIKit to use the Agora RTM SDK for a few new features like usernames. We're updating the blog to include rtm in the installation instructions. To fix the error just install the RTM SDK. New installation step would look like this:

```
npm install react-native-agora agora-react-native-rtm agora-rn-uikit
```

**Comment by vladis-c** [comment]
Well, after the newest update I start to get 

TypeError: null is not an object (evaluating 'AgoraRTM.prefix')

@EkaanshArora Could you help please?

Expo sdk 45,
running using dev-client. All dependencies installed like in blog, and I also ran command expo run:android

**Comment by EkaanshArora** [comment]
Have you installed `agora-react-native-rtm`? @vladis-c

**Comment by vladis-c** [comment]
> Have you installed `agora-react-native-rtm`? @vladis-c 

Yes, it was installed.

 However the way I solved the issue is to use react-native-agora setup. 

I hope the issue stated here will be solved!

**Comment by brytoz** [comment]
> We have updated the UIKit to use the Agora RTM SDK for a few new features like usernames. We're updating the blog to include rtm in the installation instructions. To fix the error just install the RTM SDK. New installation step would look like this:
> 
> ```
> npm install react-native-agora agora-react-native-rtm agora-rn-uikit
> ```

Installed all but faced the same issue.

**Comment by brytoz** [comment]
> > Have you installed `agora-react-native-rtm`? @vladis-c 
> 
> Yes, it was installed.
> 
>  However the way I solved the issue is to use react-native-agora setup. 
> 
> I hope the issue stated here will be solved! 

@vladis-c are you talking about the agora blog post?

**Comment by vladis-c** [comment]
> > > Have you installed `agora-react-native-rtm`? @vladis-c 
> > 
> > Yes, it was installed.
> > 
> >  However the way I solved the issue is to use react-native-agora setup. 
> > 
> > I hope the issue stated here will be solved! 
> 
> @vladis-c are you talking about the agora blog post? 

What do you mean? 

To clarify, how I solved, I basically decided not to use agora-rn-uikit. 

I completely removed all the dependencies, and reinstalled react-native-agora only. I wrote the code from scratch, with all the methods, I wanted. Customised it like I wanted.

I think, it is a better option at the moment, if any of you, guys, wanna avoid the problems. 
I hope the agora-rn-uikit is gonna be fixed soon, and we can use that as well. 

Also, I think that UI kit conflicts a lot with expo and typescript. Using expo dev client does not make agora ui kit work.

**Comment by brytoz** [comment]
@vladis-c can you show me how you imported the packages? Just a screenshot of the page/file will do.
Thanks

**Comment by vladis-c** [comment]
> @vladis-c okay, I think I understand what you mean now. 
> 
> I'll try it.

Let me know if any of you guys want a demo with react-native-agora and typescript, I will make one :)

**Comment by brytoz** [comment]
A demo will be great. Thanks 👍

**Comment by vladis-c** [comment]
That's where I took the code from. 

[https://github.com/AgoraIO-Community/react-native-agora/blob/master/example/src/examples/basic/JoinChannelVideo/JoinChannelVideo.tsx](https://github.com/AgoraIO-Community/react-native-agora/blob/master/example/src/examples/basic/JoinChannelVideo/JoinChannelVideo.tsx)

**Comment by hanees13** [comment]
> A demo will be great. Thanks 👍

can you provide a demo git repo

**Comment by plutoless** [comment]
@hanees13 as @vladis-c mentioned you can get the demo git here
https://github.com/AgoraIO-Extensions/react-native-agora/tree/master/example/src/examples

issue closed as the issue seems solved.
