### ISSUE TITLE
localVideo not display

### ISSUE THREAD

**Issue by harmit001** [AgoraIO-Extensions/react-native-agora#499]
I used the enableLocalVideo and muteLocalVideoStream props but video was not displayed on screen.

**Comment by LichKing-2234** [comment]
Is our example working?

**Comment by harmit001** [comment]
@LichKing-2234 Example also has the same issue.

**Comment by LichKing-2234** [comment]
could you pls share the code? The example works for me.

**Comment by harmit001** [comment]
import React, {
  Component
} from "react";
import {
  Dimensions,
  TouchableOpacity,
  View,
  Text,
  StatusBar,
  PermissionsAndroid,
  ImageBackground,
  ActivityIndicator,
  AppState,
  SafeAreaView,
  TouchableHighlight,
  ScrollView,
  SectionList,
  TouchableWithoutFeedback,
  Platform,
} from "react-native";
import Ionicons from "react-native-vector-icons/Ionicons";
import MaterialCommunityIcons from "react-native-vector-icons/MaterialCommunityIcons";
import MaterialIcons from "react-native-vector-icons/MaterialIcons";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "@/theme/dimen";
import {
  wineIcon
} from "@/assets";
import FastImage from "react-native-fast-image";
import {
  activateKeepAwake,
  deactivateKeepAwake,
} from "@sayem314/react-native-keep-awake";
import Toast from "react-native-toast-message";
import {
  toastConfig
} from "@/theme/toastConfig";
/******************** StyleSheet ********************/
import styles from "./styles";
import {
  connect
} from "react-redux";
import RtcEngine, {
  ChannelProfile,
  ClientRole,
  RtcEngineContext,
  RtcLocalView,
  RtcRemoteView,
  VideoRenderMode,
  VideoRemoteState,
} from "react-native-agora";
/************** Controlers *************/
import {
  VideoCallController
} from "@/controllers";
import {
  SommelierController
} from "@/controllers";
import {
  RestaurantsController
} from "@/controllers";
import {
  strings
} from "@/localization";
import Modal from "react-native-modal";
import SplashScreen from "react-native-splash-screen";
import AntDesign from "react-native-vector-icons/AntDesign";
import {
  COLLECTION
} from "@/constants/collection";
import {
  cameraVector,
  welcome_img,
  editIcon
} from "@/assets";
/******************** components ***************/
import Container from "@/components/container";
import CardContainer from "@/components/cardContainer";
import firestore from "@react-native-firebase/firestore";
import {
  DynamicAppStyles
} from "@/theme";
import {
  Appearance
} from "react-native-appearance";
import {
  CommonActions
} from "@react-navigation/native";
import FeedbackModal from "@/components/FeedbackModal";
import {
  updateRatingApi
} from "@/utils";
import {
  Button
} from "@/components";

const COLOR_SCHEME = Appearance.getColorScheme();
const windowWidth = Dimensions.get("window").width;
class videoCall extends Component {
  constructor(props) {
    super(props);
    this._engine = RtcEngine;
    this.state = {
      appId: "1d194c1b24c1402a9ca54785aa262549",
      channelName: "",
      token: "",
      joinSucceed: false,
      peerIds: [],
      startCall: false,
      options: {
        mic: false,
        videoEnable: true,
        callEnd: true,
        switchCamera: true,
      },
      offVideoRemoteStream: [],
      currentuid: null,
      visibleProduct: false,
      filteredArray: [],
      feedbackModal: false,
      callStatus: {},
    };
  }

  componentWillMount() {
    activateKeepAwake();
  }
  componentWillUnmount() {
    if (this.state.callStatus ? .status == strings.callStatus.accepted) {
      this._engine ? .destroy();
    }
    deactivateKeepAwake();
    AppState.removeEventListener("change", this._handleAppStateChange);
  }
  componentDidMount() {
    const {
      channelName
    } = this.props.route.params;
    console.log(this.props.route.params, "channelName", channelName);
    AppState.addEventListener("change", this._handleAppStateChange);
    VideoCallController.getAccessToken(
      channelName ? channelName : this.props.user.userDetails.restaurantName
    ).then((resToken) => {
      console.log(
        resToken,
        "resToken",
        this.props.route.params ? .data ? .channelUniqid
      );
      if (resToken.status) {
        if (this.props.route.params ? .data ? .channelUniqid) {
          firestore()
            .collection(COLLECTION.CALLHISTORY)
            .where("id", "==", this.props.route.params ? .data ? .channelUniqid)
            .onSnapshot((querySnapshot) => {
              if (querySnapshot.size > 0) {
                querySnapshot.forEach((document) => {
                  console.log("querySnapshot.data()", document.data());
                  if (document.data().status == strings.callStatus.accepted) {
                    clearInterval(this._interval);
                    this.setState({
                        token: resToken.token,
                        channelName: channelName ?
                          channelName :
                          this.props.user.userDetails.restaurantName,
                      },
                      () => {
                        this.init();
                        console.log(this.state.callStatus, "callssattua");
                        this.setState({
                          callStatus: document.data()
                        });
                      }
                    );
                  } else if (
                    document.data().status == strings.callStatus.declined
                  ) {
                    this.props.navigation.goBack();
                  }
                });
              } else {
                console.log("elseee");
              }
            });
        }
      } else {
        this.gobackHandler();
      }
    });
    this.getProducts();
    SplashScreen.hide();
    this._interval = setInterval(() => {
      this.callDeclined();
    }, 60000);
    // this.startCall()
  }
  getProducts = () => {
    const {
      data
    } = this.props.route.params;
    if (data ? .resturantID) {
      var id = data ? .resturantID;
      firestore()
        .collection(COLLECTION.PRODUCTS)
        .where("restaurantId", "==", id)
        .get()
        .then((querySnapshot) => {
          console.log("querySnapshotquerySnapshot", querySnapshot);
          const dispatches = [];
          var total = 0;
          querySnapshot ? .forEach((document) => {
            dispatches.push(document.data());
            total = total + parseInt(document.data().qty);
          });
          this.setState({
            totalProduct: total
          });
          console.log(total, "dispatches12", dispatches);
          let arr = dispatches;
          let data = [];
          let arr2 = dispatches;
          while (arr2 ? .length != 0) {
            let temp = arr2[0].category;
            let fil = arr2.filter((item) => {
              return item.category == temp;
            });
            data.push({
              title: temp,
              data: fil
            });
            arr2 = arr2.filter((item) => {
              return item.category != temp;
            });
          }
          this.setState({
            filteredArray: data
          });
        })
        .catch((err) => {
          console.log("Error");
        });
    }
  };

  _handleAppStateChange = async (nextAppState) => {
    console.log(nextAppState, "nextAppState");
    if (nextAppState == "background") {
      await this._engine.disableVideo();
    } else {
      await this._engine.enableVideo();
    }
    // this.setState({ appState: nextAppState });
  };
  // Pass in your App ID through this.state, create and initialize an RtcEngine object.
  init = async () => {
    try {
      const {
        appId
      } = this.state;
      this._engine = await RtcEngine.create(appId);
      await this._engine.enableVideo();
      await this._engine.enableLocalAudio(true);
      // Listen for the UserJoined callback.
      // This callback occurs when the remote user successfully joins the channel.
      this._engine.addListener("UserJoined", (uid, elapsed) => {
        console.log("UserJoined", uid, elapsed);
        const {
          peerIds
        } = this.state;
        if (peerIds.indexOf(uid) === -1) {
          this.setState({
            peerIds: [...peerIds, uid],
          });
        }
      });
      this._engine.addListener(
        "RemoteVideoStateChanged",
        (uid, state, reason, elapsed) => {}
      );
      // Listen for the UserOffline callback.
      // This callback occurs when the remote user leaves the channel or drops offline.
      this._engine.addListener("UserOffline", (uid, reason) => {
        console.log("UserOffline", uid, reason);
        const {
          peerIds
        } = this.state;

        this.setState({
            peerIds: peerIds.filter((id) => id !== uid),
          },
          () => {
            this.setState({
              startCall: false,
              options: {
                ...this.state.options,
                callEnd: !this.state.options.callEnd,
              },
            });
            this.endCall();
          }
        );
      });
      // Listen for the JoinChannelSuccess callback.
      // This callback occurs when the local user successfully joins the channel.
      this._engine.addListener(
        "JoinChannelSuccess",
        (channel, uid, elapsed) => {
          console.log("JoinChannelSuccess", channel, uid, elapsed);
          this.setState({
            joinSucceed: true,
            currentuid: uid,
          });
        }
      );
      // Listen for Warning
      this._engine ? .addListener("Warning", (warningCode) => {
        console.info("Warning", warningCode);
      });
      // Listen for Error
      this._engine ? .addListener("Error", (errorCode) => {
        console.info("Error", errorCode);
      });
      this._engine ? .addListener(
        "VideoPublishStateChanged",
        (uid, state, reason, elapsed) => {
          console.info("VideoPublishStateChanged", uid, state, reason, elapsed);
        }
      );
      this._engine ? .addListener(
        "LocalVideoStateChanged",
        (uid, state, reason, elapsed) => {
          console.info("LocalVideoStateChanged", uid, state, reason, elapsed);
        }
      );
      this._engine ? .addListener("UserEnableVideo", (uid, state) => {
        console.info("UserEnableVideo", uid, state);
        const {
          offVideoRemoteStream
        } = this.state;
        if (!state) {
          if (offVideoRemoteStream.indexOf(uid) === -1) {
            this.setState({
              offVideoRemoteStream: [...offVideoRemoteStream, uid],
            });
          }
        } else {
          if (offVideoRemoteStream.indexOf(uid) > -1) {
            this.setState({
              offVideoRemoteStream: this.state.offVideoRemoteStream.filter(
                (id) => id !== uid
              ),
            });
          }
        }
      });
      // this._engine?.addListener('RemoteVideoStateChanged', (uid, state, reason, elapsed) => {
      //   console.info('RemoteVideoStateChanged', uid, state, reason, elapsed);
      // });
      this.startCall();
    } catch (e) {
      console.log("ERROR", e);
    }
  };
  startCall = async () => {
    var res = await this._engine ? .joinChannel(
      this.state.token,
      this.state.channelName,
      null,
      0
    );
    console.log("resresres", res);
    this.setState({
      startCall: true
    });

    setTimeout(() => {
      if (this.props.route.params ? .status == "cancel") {
        this.setState({
          startCall: false,
          options: {
            ...this.state.options,
            callEnd: !this.state.options.callEnd,
          },
        });
        this.endCall();
      }
    }, 1000);
  };
  localStreamVideoEnable = () => {
    return ( <
      RtcLocalView.SurfaceView style = {
        {
          flex: 1
        }
      }
      channelId = {
        this.state.channelName
      }
      renderMode = {
        VideoRenderMode.Hidden
      }
      />
    );
  };
  localStreamVideoDisable = () => {
    return ( <
      View style = {
        styles.localStreamDisable
      } >
      <
      View style = {
        styles.offlineVideoContainer
      } >
      <
      Text style = {
        styles.offlineVideoTextStyle
      } > SO < /Text> <
      /View> <
      /View>
    );
  };
  localStreamRender = () => {
    const {
      joinSucceed
    } = this.state;
    console.log(joinSucceed, "joinSucceed");
    return ( <
      View style = {
        styles.localStreamContainer
      } > {
        joinSucceed ? ( <
          View style = {
            styles.localStream
          } > {
            this.state.options.videoEnable ?
            this.localStreamVideoEnable() :
              this.localStreamVideoDisable()
          } <
          /View>
        ) : ( <
          View style = {
            styles.localStream
          } > < /View>
        )
      } <
      Text style = {
        styles.localStreamText
      }
      numberOfLines = {
        2
      }
      adjustsFontSizeToFit >
      {
        this.props.user.userDetails.fullName
      } <
      /Text> <
      /View>
    );
  };
  endCall = async () => {
    console.log("end calllll");
    this.sentRequest();
    await this._engine ? .leaveChannel();
    this.setState({
      peerIds: [],
      joinSucceed: false
    });

    this.gobackHandler();
  };

  callDeclined = async () => {
    firestore()
      .collection(COLLECTION.CALLHISTORY)
      .doc(this.props.route.params ? .data ? .channelUniqid)
      .update({
        status: strings.callStatus.declined
      })
      .then(() => {
        clearInterval(this._interval);
        //this.props.navigation.goBack()
      })
      .catch((error) => {
        console.log("wsdwdwdd", error);
      });
  };

  _renderRemoteVideos = () => {
    const {
      peerIds,
      offVideoRemoteStream
    } = this.state;
    console.log(offVideoRemoteStream, "offVideoRemoteStream");
    console.log(peerIds, "peerIds");
    console.log(this.state.currentuid, "currentuid");
    return ( <
      ScrollView style = {
        {
          flex: 1
        }
      }
      contentContainerStyle = {
        {
          flex: 1
        }
      }
      horizontal = {
        true
      }
      showsHorizontalScrollIndicator = {
        false
      } >
      {
        peerIds.map((value, index, array) => {
          var showVideo = true;
          // if(offVideoRemoteStream?.length>0){
          console.log(
            offVideoRemoteStream,
            "offVideoRemoteStream=========>1",
            value
          );
          if (offVideoRemoteStream.includes(value)) {
            showVideo = false;
          } else {
            showVideo = true;
          }

          return showVideo ? ( <
            RtcRemoteView.SurfaceView style = {
              {
                flex: 1
              }
            }
            uid = {
              value
            }
            channelId = {
              this.state.channelName
            }
            renderMode = {
              VideoRenderMode.Hidden
            }
            zOrderMediaOverlay = {
              false
            }
            />
          ) : ( <
            View style = {
              {
                alignSelf: "center",
                justifyContent: "center",
                alignItems: "center",
                flex: 1,
              }
            } >
            <
            View style = {
              [styles.offlineVideoContainer]
            } >
            <
            Text style = {
              styles.offlineVideoTextStyle
            } > EO < /Text> <
            /View> <
            /View>
          );
        })
      } <
      /ScrollView>
    );
  };
  gobackHandler = async () => {
    console.log("if=======");
    if (this.props.user.role == strings.userRole.sommelier) {
      var data = await this.props.navigation.dispatch((state) => {
        // Remove the last 2 routes from current list of routes
        const routes = state.routes.slice(0, -1);

        // Reset the state to the new state with updated list of routes
        return CommonActions.reset({
          ...state,
          index: routes.length - 1,
          routes,
        });
      });
      console.log("data", data);
      this.props.navigation.goBack();
    } else {
      console.log("else=======");
      this.setState({
        feedbackModal: true
      });
      // if(this.props.route.params?.status == 'accept'){this.setState({feedbackModal:true})}else{
      //   this.props.navigation.goBack()
      // }
    }
  };
  sentRequest = async () => {
    const {
      data
    } = this.props.route.params;
    console.log(this.props.route, "CALL CONNECTION DATA", data);
    if (data.isIntrocall) {
      try {
        var res = await SommelierController.sentRequest(
          data.sommilerID,
          data.resturantID
        );
        console.log("res", res);
        if (res.status) {
          alert(strings.common.sentRequest);
        }
      } catch (error) {
        console.log("error-------->", error);
      }
    }
  };
  storeRating = async (data1) => {
    console.log(data1, "data1");
    if (data1.rating > 0 || data1.feedback) {
      const {
        data
      } = this.props.route.params;
      var all = {
        rating: data1.rating,
        feedBack: data1.feedback,
        restaurantId: this.props.user.userDetails.id,
        sommilerId: data.sommilerID,
      };
      try {
        var res = await RestaurantsController.storeRating(all);
        console.log("resNew", res.status);
        if (res.status) {
          let res = await updateRatingApi(data.sommilerID);
          console.log("update rate =====", res);
          this.setState({
            feedbackModal: false
          });
          Toast.show({
            type: "success",
            text1: "Feedback has been added successfully",
          });
          setTimeout(() => {
            this.props.navigation.goBack();
          }, 500);
        }
      } catch (error) {
        this.setState({
          feedbackModal: false
        });
        this.props.navigation.goBack();
      }
    } else {
      Toast.show({
        type: "error",
        text1: "you must give rating",
      });
    }
  };
  render() {
    const helper = {
      m0: "mic",
      m1: "mic-off",
      v0: "video",
      v1: "video-off",
    };

    if (this.state.token == "") {
      console.log(this.state.callStatus, "this.state.callStatus");
      return ( <
        View style = {
          {
            flex: 1,
            justifyContent: "center",
            alignItems: "center"
          }
        } >
        {
          this.props.route.params ? .status == strings.callStatus.accepted ? ( <
            Text > waiting
            for connection < /Text>
          ) : ( <
            View style = {
              styles.vCallOptionsControler
            } >
            <
            ActivityIndicator size = "small"
            color = {
              DynamicAppStyles.colorSet[COLOR_SCHEME].TomatoRed
            }
            /> <
            Text style = {
              styles.btnTxtStyles
            } > Ringing < /Text> <
            Button title = {
              "End Call"
            }
            style = {
              {
                marginTop: hp(2),
                alignSelf: "center"
              }
            }
            textStyle = {
              styles.btnTxtStyles
            }
            onPress = {
              () => {
                this.callDeclined();
              }
            }
            /> <
            /View>
          )
        } <
        /View>
      );
    }
    return ( <
      SafeAreaView style = {
        styles.SafeAreaView
      } >
      <
      StatusBar barStyle = "light-content"
      translucent = {
        true
      }
      />

      <
      View style = {
        styles.remoteControlStyles
      } > {
        /* <View style={styles.offlineVideoContainer}>
                        <Text style={styles.offlineVideoTextStyle}>EO</Text>
            </View>*/
      } {
        this._renderRemoteVideos()
      } {
        this.localStreamRender()
      } <
      View style = {
        this.state.visibleProduct ?
        styles.openModalvCallOptionsControlerMain :
          styles.vCallOptionsControlerMain
      } >
      <
      View style = {
        styles.vCallOptionsControler
      } >
      <
      TouchableHighlight activeOpacity = {
        0
      }
      underlayColor = {
        "transperent"
      }
      onPress = {
        () => {
          this.setState({
              options: {
                ...this.state.options,
                mic: !this.state.options.mic,
              },
            },
            async () => {
              if (this.state.options.mic) {
                await this._engine.enableLocalAudio(false);
              } else {
                await this._engine.enableLocalAudio(true);
              }
            }
          );
        }
      } >
      <
      Ionicons name = {
        this.state.options.mic ? helper["m1"] : helper["m0"]
      }
      style = {
        styles.controllerStyle
      }
      /> <
      /TouchableHighlight> <
      /View> <
      View style = {
        styles.vCallOptionsControler
      } >
      <
      TouchableHighlight activeOpacity = {
        0
      }
      underlayColor = {
        "transperent"
      }
      onPress = {
        () => {
          var videoEnable = !this.state.options.videoEnable;
          this.setState({
              options: {
                ...this.state.options,
                videoEnable: videoEnable,
              },
            },
            async () => {
              if (!videoEnable) {
                await this._engine.disableVideo();
                //await this._engine.disableLocalVideo()
              } else {
                await this._engine.enableVideo();
              }
            }
          );
        }
      } >
      <
      MaterialCommunityIcons name = {
        this.state.options.videoEnable ? helper["v0"] : helper["v1"]
      }
      style = {
        styles.controllerStyle
      }
      /> <
      /TouchableHighlight> <
      /View> <
      View style = {
        styles.vCallOptionsControler
      } >
      <
      View style = {
        styles.endCallStyles
      } >
      <
      TouchableHighlight activeOpacity = {
        0
      }
      underlayColor = {
        "transperent"
      }
      onPress = {
        () => {
          this.setState({
            startCall: false,
            options: {
              ...this.state.options,
              callEnd: !this.state.options.callEnd,
            },
          });
          this.endCall();
        }
      } >
      <
      MaterialIcons name = {
        "call-end"
      }
      style = {
        [styles.controllerStyle, {
          fontSize: hp(4)
        }]
      }
      /> <
      /TouchableHighlight> <
      /View> <
      /View> <
      View style = {
        styles.vCallOptionsControler
      } >
      <
      TouchableHighlight activeOpacity = {
        0
      }
      underlayColor = {
        "transperent"
      }
      onPress = {
        () => {
          this.setState({
              options: {
                ...this.state.options,
                switchCamera: !this.state.options.switchCamera,
              },
            },
            () => {
              this._engine ? .switchCamera();
            }
          );
        }
      } >
      <
      MaterialIcons name = {
        "flip-camera-android"
      }
      style = {
        [styles.controllerStyle, {
          fontSize: hp(4)
        }]
      }
      /> <
      /TouchableHighlight> <
      /View> <
      /View>

      <
      View style = {
        styles.wineIconContainer
      } >
      <
      View style = {
        styles.wineStyles
      } >
      <
      TouchableHighlight activeOpacity = {
        0
      }
      underlayColor = {
        "transperent"
      }
      onPress = {
        () => {
          this.setState({
            visibleProduct: !this.state.visibleProduct
          });
        }
      } >
      <
      FastImage style = {
        styles.wineIconStyle
      }
      source = {
        wineIcon
      }
      resizeMode = {
        FastImage.resizeMode.contain
      }
      /> <
      /TouchableHighlight> <
      /View> <
      /View> <
      /View> <
      FeedbackModal visible = {
        this.state.feedbackModal
      }
      cancel = {
        () => (
          this.setState({
            feedbackModal: false
          }),
          this.props.navigation.goBack()
        )
      }
      submit = {
        (data) => this.storeRating(data)
      }
      /> <
      Modal visible = {
        this.state.visibleProduct
      }
      animated animationType = "slide"
      panResponderThreshold transparent hasBackdrop style = {
        {
          flex: 1,
          margin: 0,
          justifyContent: "flex-end"
        }
      }
      onBackdropPress = {
        () => this.setState({
          visibleProduct: false
        })
      } >
      <
      View style = {
        styles.overlay
      } >
      <
      Container containerStyle = {
        {
          paddingHorizontal: wp(0)
        }
      } >
      <
      CardContainer fullCard = {
        false
      }
      halfCardContainer = {
        styles.modalCardContainer
      } >
      <
      View style = {
        styles.headerContainer
      } >
      <
      TouchableWithoutFeedback onPress = {
        () => {
          this.setState({
            visibleProduct: false
          });
        }
      } >
      <
      AntDesign name = {
        "close"
      }
      size = {
        Platform.isPad ? wp(3) : wp(4)
      }
      color = {
        DynamicAppStyles.colorSet[COLOR_SCHEME].Grey
      }
      /> <
      /TouchableWithoutFeedback> <
      /View> {
        /* <KeyboardAwareScrollView contentContainerStyle={styles.scrollView} extraScrollHeight={hp(2.5)} keyboardShouldPersistTaps='handled' nestedScrollEnabled={true}> */ }

      <
      SectionList sections = {
        this.state.filteredArray
      }
      keyExtractor = {
        (item, index) => item + index
      }
      renderItem = {
        ({
          item
        }) => {
          return ( <
            View >
            <
            View style = {
              [styles.mainRow]
            } >
            <
            View style = {
              styles.subContainer
            } >
            <
            View style = {
              {
                alignSelf: "center"
              }
            } > {
              item ? .winePhoto ? .url ? ( <
                FastImage style = {
                  styles.wineImgStyle
                }
                source = {
                  {
                    uri: item ? .winePhoto ? .url
                  }
                }
                resizeMode = {
                  FastImage.resizeMode.contain
                }
                />
              ) : ( <
                FastImage style = {
                  styles.wineImgStyle
                }
                source = {
                  welcome_img
                }
                resizeMode = {
                  FastImage.resizeMode.contain
                }
                />
              )
            } <
            /View> <
            View style = {
              styles.centerContainer
            } >
            <
            View style = {
              styles.subColumn
            } >
            <
            Text style = {
              [
                styles.nameTxt,
                {
                  marginRight: wp(2)
                },
              ]
            } >
            {
              item.name
            } <
            /Text>

            <
            View style = {
              styles.SubRow
            } >
            <
            Text style = {
              styles.qtyTxt
            } > {
              item.format
            } <
            /Text> <
            /View> <
            /View>

            <
            Text style = {
              [
                styles.countryYearTxt,
                {
                  color: item.qty == 0 ?
                    DynamicAppStyles.colorSet[
                      COLOR_SCHEME
                    ].Black :
                    DynamicAppStyles.colorSet[
                      COLOR_SCHEME
                    ].MountainMist,
                },
              ]
            } >
            {
              item.country
            } {
              item.year
            } <
            /Text>

            <
            Text numberOfLines = {
              1
            }
            style = {
              [styles.briefTxt, {}]
            } >
            {
              item.brief
            } <
            /Text> <
            /View> <
            /View>

            <
            View style = {
              {
                width: windowWidth > 760 || Platform.isPad ?
                  wp(10) :
                  wp(13),
                alignItems: "center",
                justifyContent: "center",
              }
            } >
            <
            Text style = {
              [styles.pricetxt]
            } >
            $ {
              item ? .pricePerGlass ? item.pricePerGlass : 0
            } <
            /Text> <
            /View> <
            View style = {
              {
                width: windowWidth > 760 || Platform.isPad ?
                  wp(10) :
                  wp(13),
                alignItems: "center",
              }
            } >
            <
            Text style = {
              [styles.pricetxt]
            } >
            $ {
              item ? .pricePerBottle ? item.pricePerBottle : 0
            } <
            /Text> <
            /View> {
              /* <View style={styles.editBtnContainer}>

                                                              </View> */
            } <
            /View> <
            /View>
          );
        }
      }
      renderSectionHeader = {
        ({
          section: {
            title
          }
        }) => ( <
          View style = {
            styles.sectionContainer
          } >
          <
          Text style = {
            [styles.sectionHeading, {
              flex: 1
            }]
          } > {
            title
          } <
          /Text> <
          View style = {
            {
              width: windowWidth > 760 || Platform.isPad ?
                wp(10) :
                wp(13),
              alignItems: "center",
            }
          } >
          <
          Text style = {
            [styles.sectionHeading]
          } > Glass < /Text> <
          /View> <
          View style = {
            {
              width: windowWidth > 760 || Platform.isPad ?
                wp(10) :
                wp(13),
              alignItems: "center",
            }
          } >
          <
          Text style = {
            [styles.sectionHeading]
          } > Bottle < /Text> <
          /View>

          <
          View style = {
            styles.devider
          }
          /> <
          /View>
        )
      }
      /> <
      /CardContainer> <
      /Container> <
      /View> <
      /Modal> <
      Toast position = "bottom"
      config = {
        toastConfig
      }
      bottomOffset = {
        20
      }
      /> <
      /SafeAreaView>
    );
  }
}
const mapStateToProps = (state) => ({
  user: state.user,
});
export default connect(mapStateToProps, {})(videoCall);

**Comment by harmit001** [comment]
[videoCall.txt](https://github.com/AgoraIO-Community/react-native-agora/files/8713236/videoCall.txt)

@LichKing-2234 I have an attached File over here. please review it. Many many thanks.
