### ISSUE TITLE
tap to change RtcLocalView to RtcRemoteView issue.

### ISSUE THREAD

**Issue by torretorich** [AgoraIO-Extensions/react-native-agora#500]
i make a one to one video calling app.
how can i add a features to change RtcLocalView to RtcRemoteView.
when i click on RtcRemoteView => large camera view is set in short view and short camera view is set in large view.
change state of RtcLocalView and RtcRemoteView in ReactNative.

**Comment by LichKing-2234** [comment]
just render with a flag state

**Comment by torretorich** [comment]
`import { StyleSheet, Text, View, Platform, ScrollView, TouchableOpacity, Dimensions, PermissionsAndroid, Image, FlatList } from 'react-native'
import React, { Component, useEffect, useState, useRef, useCallback } from 'react'
import RtcEngine, {
    RtcLocalView,
    RtcRemoteView,
    VideoRenderMode,
    ClientRole,
    ChannelProfile,
} from 'react-native-agora';
// var _engine = _engine;
const requestCameraAndAudioPermission = async () => {
    try {
        const granted = await PermissionsAndroid.requestMultiple([
            PermissionsAndroid.PERMISSIONS.CAMERA,
            PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        ]);
        if (
            granted['android.permission.RECORD_AUDIO'] ===
            PermissionsAndroid.RESULTS.GRANTED &&
            granted['android.permission.CAMERA'] ===
            PermissionsAndroid.RESULTS.GRANTED
        ) {
            console.log('You can use the cameras & mic');
        } else {
            console.log('Permission denied');
        }
    } catch (err) {
        console.warn(err);
    }
}

const token = '006e525c5a435734e02814b698ae69198fbIABVQV5zy9kp4Dc8rggtZw9G/RseMgNDHZY7d3m+bFCHQ6JrsCMAAAAAEADTxV3AVGiMYgEAAQBUaIxi';
const appId = 'e525c5a435734e02814b698ae69198fb';
const channelName = 'NewChannel';

const StartCallScreen = () => {
    const [isHost, setIsHost] = useState(true);
    const [joinSucceed, setJoinSucceed] = useState(false);
    const [peerIds, setPeerIds] = useState([]);
    const [openMicrophone, setOpenMicrophone] = useState(true);
    const [switchCamera, setSwitchCamera] = useState(true);
    if (Platform.OS === 'android') {
                    // Request required permissions from Android
                    requestCameraAndAudioPermission().then(() => {
                        console.log('requested!', requestCameraAndAudioPermission);
                    });
                }

    const initAgora = useCallback(async () => {
        RtcEngine.current = await RtcEngine.create(appId);
        await RtcEngine.current?.enableVideo();
        await RtcEngine.current?.setChannelProfile(ChannelProfile.LiveBroadcasting);
        await RtcEngine.current?.setClientRole(
            isHost ? ClientRole.Broadcaster : ClientRole.Audience
        );
        RtcEngine.current?.addListener('Warning', (warn) => {
            console.log('Warning=>>', warn);
        });
        RtcEngine.current?.addListener('Error', (err) => {
            console.log('Error ===>', err);
        });
        RtcEngine.current?.addListener('UserJoined', (uid, elapsed) => {
            console.log('UserJoined', uid, elapsed);
            if (peerIds.indexOf(uid) === -1) {
                setPeerIds([...peerIds, uid])
            }
        });
        RtcEngine.current?.addListener('UserOffline', (uid, reason) => {
            console.log('UserOffline', uid, reason);
            setPeerIds({ peerIds: peerIds.filter((id) => id !== uid) });
        });
        // If Local user joins RTC channel
        RtcEngine.current?.addListener('JoinChannelSuccess', (channel, uid, elapsed) => {
            console.log('JoinChannelSuccess', channel, uid, elapsed);
        });
    }, [])

    useEffect(() => {
        initAgora();
        return () => {
        };
    }, [initAgora]);

    const startCall = async () => {
        await RtcEngine.current?.joinChannel(token, channelName, null, 0);
        console.log('call started');
        setJoinSucceed(true);
    };

    const endCall = async () => {
        await RtcEngine.current?.leaveChannel();
        setPeerIds([]);
        setJoinSucceed(false);
        console.log('endCall')
    };

    const _switchCamera = () => {
        RtcEngine.current
            ?.switchCamera()
            .then(() => {
                setSwitchCamera(!switchCamera);
            })
            .catch((err) => {
                console.warn('switchCamera', err);
            });
    };

    const _switchMicrophone = () => {
        RtcEngine.current
            ?.enableLocalAudio(!openMicrophone)
            .then(() => {
                setOpenMicrophone(!openMicrophone);
            })
            .catch((err) => {
                console.warn('enableLocalAudio', err);
            });
    };
const touchpress=()=>{
alert("jhk")
}
    return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            {joinSucceed ? (
                <View>

                    <View>
                        {joinSucceed ? (
                            <View style={styles.fullView}>
                                    {isHost ? (
                                        <RtcLocalView.SurfaceView
                                            style={{flex:1}}
                                            channelId={channelName}
                                            renderMode={VideoRenderMode.Hidden}
                                        />
                                    ) : null}
                                
                                <ScrollView
                                    style={styles.remoteContainer}
                                    contentContainerStyle={styles.remoteContainerContent}
                                    horizontal={true}
                                >
                                    <FlatList
                                    data={peerIds}
                                    renderItem={({ item })=> {
                                        return(
                                            <TouchableOpacity onPress={()=>touchpress()}>
                                        <RtcRemoteView.SurfaceView
                                                style={{ width: 150, height: 150,}}
                                                uid={item}
                                                channelId={channelName}
                                                renderMode={VideoRenderMode.Hidden}
                                                zOrderMediaOverlay={true}
                                            />
                                            </TouchableOpacity>
                                            
                                    )}}
                                    
                                    />
                                </ScrollView>
                               
                            </View>
                        ) : (null)
                        }
                    </View>
                    <View style={styles.buttonView}>
                        <TouchableOpacity style={styles.buttons}
                            onPress={() => _switchMicrophone()}>
                            <Image style={styles.icon2}
                                source={require('../Assets/Icon/mute-microphone.png')}
                            />
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.buttons}
                            onPress={() => _switchCamera()} >
                            <Image style={styles.icon2}
                                source={require('../Assets/Icon/switch-camera.png')}
                            />
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.buttons}>
                            <Image style={styles.icon2}
                                source={require('../Assets/Icon/camera-off.png')}
                            />
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.endCallIcon}
                            onPress={() => endCall()}>
                            <Image style={styles.icon2}
                                source={require('../Assets/Icon/end-call.png')}
                            />
                        </TouchableOpacity>
                        
                    </View>
                    
                </View>
            ) : (
                <View>
                    <TouchableOpacity
                        onPress={() => startCall()}
                        style={styles.startButton}>
                        <Text style={styles.startButtonText}>Start Call</Text>
                    </TouchableOpacity>
                </View>
            )
            }
        </View>
    );
}

export default StartCallScreen;

const dimensions = {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
};

const styles = StyleSheet.create({
    icon2: {
        tintColor: '#fff',
        height: 40,
        width: 40,
    },
    fullView: {
        width: dimensions.width,
        height: dimensions.height - 100,
    },
    remoteContainer: {
        width: '100%',
        height: 150,
        position: 'absolute',
        top: 5,
    },
    remoteContainerContent: {
        paddingHorizontal: 2.5,
    },
    startButton: {
         backgroundColor: '#0093e9',
          padding: 10,
           borderRadius: 20 
    },
    startButtonText:{
         fontSize: 20,
             color: '#fff'
    },
    endCallIcon:{ 
        justifyContent: 'center',
         alignItems: 'center',
          backgroundColor: '#f00',
           padding: 10,
            borderRadius: 40
         },
         buttonView:{
            backgroundColor: '#0093e9',
            padding: 20,
            flexDirection: 'row',
            justifyContent: 'space-between',
            borderTopStartRadius: 20,
            borderTopEndRadius: 20,
        },
        buttons:{
            padding:10
        }
})`

**Comment by torretorich** [comment]
can you help to change flex or styling of Rtclocalview RtcremoteView how to overLay localView on remoteView video.
