### ISSUE TITLE
RtcEngine.disableVideo() is not working

### ISSUE THREAD

**Issue by torretorich** [AgoraIO-Extensions/react-native-agora#501]
i want to add function video on/off in video calling project through RtcEngine.disableVideo() but its not work i also apply RtcEngine.muteLocalVideoStream (false) to off local camera but it's not worked. can you help how to apply these features to add function in my project.

**Comment by LichKing-2234** [comment]
pls try enableLocalVideo

**Comment by torretorich** [comment]
i already apply enableLocalVideo but how to implement camera off feature in videoCalling.
i want to add camera on/off feature in videocalling.

**Comment by LichKing-2234** [comment]
call enableLocalVideo with true or false

**Comment by torretorich** [comment]
I am able to enable Video  using   RtcEngine.current?.enableVideo(true);  but not able to disable video.
Please guide me to hide the video and if  you have any reference then please share with me.

**Comment by LichKing-2234** [comment]
enableVideo just for video engine.
enableLocalVideo for local video capture.
muteLocalVideo for mute the local video stream, but still keep capture.
