### ISSUE TITLE
Ios Last Version enableFaceDetection nil

### ISSUE THREAD

**Issue by caferyukseloglu** [AgoraIO-Extensions/react-native-agora#503]
Hi, after upgrading the version to the 3.7.0 whenever opening face cam it crashes on ios.
"react": "17.0.1",
 "react-native": "0.64.1",
"react-native-agora": "3.7.0",

await _engine.joinChannel(token, props.channel, null, 0);
await _engine.enableFaceDetection(true);

2022-05-29 18:48:49.748592+0300 chatApp[xxxx:xxxxxx] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file react_native_agora/RtcEngine.swift, line 1178

Line 1178 =>  @objc func enableFaceDetection(_ params: NSDictionary, _ callback: Callback) {
        callback.code(engine?.enableFaceDetection(params["enabled"] as! Bool))
    }

**Comment by caferyukseloglu** [comment]
@objc func enableFaceDetection(_ params: NSDictionary, _ callback: Callback) {
        callback.code(engine?.enableFaceDetection(true))
    }
Patches error but when we quit calling other end stays open I don't know it is connected to this it is there.
Also I found that in ios version or enable changed to enabled but in react native it still is enable therefore it can be an version match error. Could you fix that asap. Thank you very much.

**Comment by caferyukseloglu** [comment]
@LichKing-2234 Any Idea about this issue ?

**Comment by LichKing-2234** [comment]
It works for me, any other infomation can help?

**Comment by LichKing-2234** [comment]
is it working for compile? just throw error on runtime?

**Comment by LichKing-2234** [comment]
could pls check your podfile.lock file to get the version of AgoraRtcEngine_iOS

**Comment by caferyukseloglu** [comment]
Sure agara and rtcEngine 3.7.0

**Comment by LichKing-2234** [comment]
could pls share the screenshot of podfile.lock?

**Comment by LichKing-2234** [comment]
btw, which swift version you used? and is our example working?

**Comment by caferyukseloglu** [comment]
Sorry for late answer I was of the pc. There you go;
[https://ibb.co/St428tm](Image1)
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: x86_64-apple-macosx12.0

**Comment by LichKing-2234** [comment]
I will test it on RN 0.64.1, could you pls try our example?

**Comment by caferyukseloglu** [comment]
Sure
