### ISSUE TITLE
Different mirror options for local view and remote view conflict

### ISSUE THREAD

**Issue by pretorh** [AgoraIO-Extensions/react-native-agora#504]
- react-native: `0.61.5`
- react-native-agora: `3.6.2`

I am trying to setup a `RtcLocalView.SurfaceView` to not mirror, and `RtcRemoteView.SurfaceView`s to mirror:

```
<View>
  <RtcLocalView.SurfaceView
    style={{
      width: 120,
      height: 120,
    }}
    renderMode={VideoRenderMode.Fit}
    mirrorMode={VideoMirrorMode.Disabled}
    zOrderMediaOverlay={true} />

  {userIds.map((uid, index) => (
    <RtcRemoteView.SurfaceView
      key={index}
      style={{
        width: 120,
        height: 120,
      }}
      uid={uid}
      renderMode={VideoRenderMode.Fit}
      mirrorMode={VideoMirrorMode.Enabled}
      zOrderMediaOverlay={true} />
  ))}
</View>
```

If the local user is the only user in the channel then the video is not mirrored correctly, but once another user joins, the local view is (incorrectly) mirrored again

Looking in `io.agora.rtc.base.RtcSurfaceView`, `setupRenderMode` is calling `engine.setLocalRenderMode` if `canvas.uid == 0` and `engine.setRemoteRenderMode` otherwise  
However when the views are created `setMirrorMode` is called before `setData`, meaning that `canvas.uid` is always `0`, resulting in the local render mode always being set (and the remote render mode never)

Had the same problem when using `TextureView` instead of `SurfaceView`, and on `3.7.0` (though tested less on 3.7)

I can work around this by calling `setupRenderMode(engine)` at the end of `setData` (instead of in `setRenderMode` and `setMirrorMode`), but not sure if that is the correct solution for this

**Comment by pretorh** [comment]
Update: changed the mirroring: Local should be unmirrored (disabled) as before but remote should be set to the default

``` diff
@@ -17,7 +17,6 @@
       }}
       uid={uid}
       renderMode={VideoRenderMode.Fit}
-      mirrorMode={VideoMirrorMode.Enabled}
       zOrderMediaOverlay={true} />
   ))}
 </View>
```

getting the same result as previous example

**Comment by LichKing-2234** [comment]
Sorry for the late reply, we will fixed it at the next version.
