### ISSUE TITLE
NetworkQuality Seems to be stuck on Detecting state for uid(0)

### ISSUE THREAD

**Issue by valenciaed** [AgoraIO-Extensions/react-native-agora#506]
- react-native: `0.67.4`
- react-native-agora: `3.7.0`

After I upgraded react-native-agora from v3.6.2 to v3.7.0 the `NetworkQuality` event always reports Detecting(8) on both txQuality and rxQuality for uid(0). This was working fine in v3.6.2. 

The screenshot below is a result of `console.info('NetworkQuality', uid, txQuality, rxQuality)` where uid, txQuality, rxQuality was taken from `NetworkQualityWithUidCallback` as the result of NetworkQuality event using v3.7.0:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/12947607/175292457-f1fcf759-1bd0-402e-a096-ace31ce60023.png">

From what I understand based on the screenshot, uid(0) reports the current user's network quality while uid(1) is the broadcaster's NetworkQuality since I've set the broadcaster's uid to 1. Previously in v3.6.2, uid(0) is not stuck in Detecting(8) and is reporting correctly and independently from uid(1).

Below is the screenshot for v3.6.2 which shows that it is working even for uid(0):
<img width="227" alt="image" src="https://user-images.githubusercontent.com/12947607/175295248-831f51d5-9b21-4fb5-9aef-27827888c5ec.png">

I am writing this issue to clarify if this is legit bug or an intentional update. If it is an intentional update what should I use to get the network quality of the current user? Thank you.

**Comment by LichKing-2234** [comment]
Could you pls provide the SDK log file?
