### ISSUE TITLE
Screen Sharing crop some part of screen & for web-to-mobile video call remote video stream is very slow

### ISSUE THREAD

**Issue by yasvitajoshi309** [AgoraIO-Extensions/react-native-agora#509]
Hello all, we are using,

react-native: 0.66.4
react-native-agora: 3.7.0

We have successfully implemented screen sharing with this 

await RTCEngine.startScreenCapture({
        captureAudio: true,
        captureVideo: true,
        videoParams: {
          bitrate: 1800,
          frameRate: 24,
          width: screenWidth,
          height: screenHeight,
          contentHint: VideoContentHint.Details,
        },
      });

also tried without videoParams but in both case screen sharing view on remote devices showing some part cropped from top and bottom some times please help

**Comment by LichKing-2234** [comment]
pls check the demission of video encoder configuration

**Comment by LichKing-2234** [comment]
Sorry, what means making a smooth view?

**Comment by yasvitajoshi309** [comment]
In web-to-web video call view is working fine but for web-to-mobile video call remote video stream is very slow

**Comment by LichKing-2234** [comment]
Could pls provide the SDK log, it will be helpful.

**Comment by yasvitajoshi309** [comment]
@LichKing-2234 Thanks again for your time, here is 
[agorasdk.log](https://github.com/AgoraIO-Community/react-native-agora/files/9099148/agorasdk.log)
SDK log file

**Comment by LichKing-2234** [comment]
seem like the value of bitrate is too high, is it necessary

**Comment by yasvitajoshi309** [comment]
No it's not necessary, can you please recommend which value we should use for better performance from this https://docs.agora.io/en/Video/API%20Reference/web_ng/globals.html#videoencoderconfigurationpreset

**Comment by LichKing-2234** [comment]
The SDK uses "480p_1" by default.

I think keep the default value is fine.

**Comment by yasvitajoshi309** [comment]
Hello,
We had tried with default video configuration and even with lower value but it's still grainy can you please help if there is any other workaround!

**Comment by LichKing-2234** [comment]
sorry, do you mean the remote stream looks like slow and frozen or out of sync with local?

**Comment by yasvitajoshi309** [comment]
Yes it's very slow

**Comment by LichKing-2234** [comment]
if you still have this issue, pls provide the new SDK log.

**Comment by yasvitajoshi309** [comment]
yes please find here new sdk log file
[agorasdk (1).log](https://github.com/AgoraIO-Extensions/react-native-agora/files/10021816/agorasdk.1.log)

**Comment by yasvitajoshi309** [comment]
And that screen share cropped some part issue now we are facing in ios device can you please help !

**Comment by LichKing-2234** [comment]
BTW, do you preview the screen sharing locally?

**Comment by LichKing-2234** [comment]
From the background data analysis, your network may not be very good.

**Comment by yasvitajoshi309** [comment]
> 

No, should we do that?

**Comment by LichKing-2234** [comment]
> From the background data analysis, your network may not be very good.

@yasvitajoshi309 have you tried change your network?

**Comment by kaumil1611** [comment]
Hello can you help for same, I am working on screen sharing functionality for web, user is able to share screen but remote user can not be see that screen i am not understand why?
