### ISSUE TITLE
Cannot build for iOS simulator

### ISSUE THREAD

**Issue by nbonatsakis** [AgoraIO-Extensions/react-native-agora#510]
When trying to build for the iOS simulator, we see the following error:

```
❌  ld: building for iOS Simulator, but linking in dylib built for iOS, file '/var/folders/zl/w7170jkx3_d5dvf8gvscv_b40000gn/T/eas-build-local-nodejs/d7da0d3d-98b3-4baf-98c2-1a155c538ccc/build/client/ios/Pods/AgoraRtm_iOS/AgoraRtmKit.framework/AgoraRtmKit' for architecture arm64
```

This is presumably because the Agora framework is not being compiled as a fat binary with all architectures, but rather, it only contains support for arm64.

While we do not need the functionality to work on simulator, we do use it extensively for testing purposes and it would be very helpful if Agora could build and run on it, in a disabled form.

**Comment by LichKing-2234** [comment]
You can refer to https://github.com/AgoraIO-Community/react-native-agora/issues/433
