### ISSUE TITLE
Execution failed for task ':react-native-agora:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by abisalde** [AgoraIO-Extensions/react-native-agora#513]
*Agora Version* 
- "react-native-agora": "^3.7.1", 
- "react": "17.0.2",
- "react-native": "0.67.0",

`> Task :react-native-agora:compileDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/abisalde/.gradle/caches/transforms-3/1df8c0d89b114b1835131371b6a8d2be/transformed/jetified-kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/abisalde/.gradle/caches/transforms-3/1815633100dc9bd55044d7d299aa405d/transformed/jetified-kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /home/abisalde/.gradle/caches/transforms-3/5393e7baa137d70aecc818c1887013df/transformed/jetified-kotlin-stdlib-1.7.0.jar (version 1.7)
    /home/abisalde/.gradle/caches/transforms-3/c979cadce27909efc9f6779fa79deb42/transformed/jetified-kotlin-stdlib-common-1.7.0.jar (version 1.7)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath`

- [ ] I deleted my node_modules
- [ ] I deleted .gradle globally
- [ ] I installed node_modules back
- [ ] do `./gradlew clean` on the android folder and was successful
- [ ] App can't build `:debug release` and `.assembleRelease` cos of this

**Comment by LichKing-2234** [comment]
Seem like the Kotlin version is different from our library and your root project. You can refer to this and define `kotlinVersion ` at your root project.

https://github.com/AgoraIO-Community/react-native-agora/blob/master/android/build.gradle#L3

**Comment by abisalde** [comment]
@LichKing-2234 Thanks...  I will work with this

**Comment by anisurrahman072** [comment]
Hey guys, basically i found these 2 lines from the very big log after build command
**One is:**   react-native-agora:compileDebugKotlin
**Two is:**   kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

So then i understand that i have to add kotlin version like bellow in **android/build.gradle** under ext

```
ext {
	......... other versions
        kotlinVersion = "1.6.0"
}
```

Wow, thats great & working perfectly now ✌️🎉🚀
