### ISSUE TITLE
My Android App Size Increased by 90 MB... 

### ISSUE THREAD

**Issue by JeremiahUL** [AgoraIO-Extensions/react-native-agora#514]
Hi Guys,

I am panicking because I didn't check the repercussions of using this library before I started. My app was 17.2 MB before I installed react-native-agora, I just made a build today with hermes and proguard up and it resolved to 105.6 MB. 

I don't think this is the intended behavior, I suspect I am doing something wrong.

**Comment by JeremiahUL** [comment]
I deleted the build folder and ran it again. Still the same

**Comment by JeremiahUL** [comment]
Hi @LichKing-2234 please can you enlighten me a bit. 
I used
```
            ndk {
                abiFilters "arm64-v8a", "armeabi-v7a"// , "x86", "x86_64"
            }
```
And it reduced it to 62MB which is ok but doesn't this mean some cpu architecture will not be able to access the application

**Comment by radko93** [comment]
Don't use universal APKs. Use Android bundle to upload to Play Store. Google then sends small files specific for devices, not your APK.

**Comment by hafizMDM** [comment]
This affects iOS too. It increase the app size by 150+ MB.

**Comment by LichKing-2234** [comment]
@hafizMDM our demo just 30M you can try to package it

**Comment by LichKing-2234** [comment]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/9312526/195493854-5b918e56-89b9-4f5b-b61d-29e2c19be9f4.png">

**Comment by hafizMDM** [comment]
@LichKing-2234 Which branch is that ? 

https://github.com/AgoraIO-Extensions/react-native-agora/tree/main/example

This doesn't have 'react-native-agora' package in package.json.

**Comment by LichKing-2234** [comment]
@hafizMDM It use `react-native-builder-bob`, so it link the package locally.
