### ISSUE TITLE
IOS build failed Unknow type name 'namespace' error

### ISSUE THREAD

**Issue by ajitdas123** [AgoraIO-Extensions/react-native-agora#515]
Whenever I try to build on Xcode with this package, the build fails with an error saying

> Unknown type name 'namespace'
> Expected ';' after top-level declarator
And some more similar errors, attaching a screenshot of all the errors. 

I have followed the installation instructions as mentioned over [here](https://github.com/AgoraIO-Extensions/react-native-agora/blob/master/docs/v3/installation.ios.md). For the installation I am using CocoaPods.

**I also have added a blank swift file, to make it swift compatible.** 

There are some similar issues available on the issues list but those didn't help me much as those seem outdated. 

https://github.com/AgoraIO-Extensions/react-native-agora/issues/168
https://github.com/AgoraIO-Extensions/react-native-agora/issues/433
https://github.com/AgoraIO-Extensions/react-native-agora/issues/168

Also as mentioned in the comment of #168 `try to add s.static_framework = true into react-native-agora.podspec.`. I have no idea where is ` react-native-agora.podspe` located. I tried adding in the podfile of the project but it threw an error at the time of pod installation.

### For my environment 

- react: 17.0.2,
- react-native: 0.68.2,
- react-native-agora:3.7.0
- Xcode: 13.1 (13A1030d)
- **M1 chips**

### Screenshot
![Screenshot 2022-09-10 at 12 38 26 PM](https://user-images.githubusercontent.com/20204881/189473575-880bff9c-6567-482f-a569-a67960d5b088.png)

**Comment by LichKing-2234** [comment]
seem like your project does not support swift, pls follow https://developer.apple.com/documentation/swift/migrating-your-objective-c-code-to-swift

**Comment by ajitdas123** [comment]
Hello @LichKing-2234 Thank you for your response, But I have added a swift file and also a bridging header

Please have a look,  I checked the documentation link you have shared, but it looks a bit complicated as I am not familiar with Swift or IOS as a whole. 

![Screenshot 2022-09-15 at 4 35 52 PM](https://user-images.githubusercontent.com/20204881/190388731-bd669f3a-6e2b-40b4-a4b0-8cfdcd90d4bc.png)

**Comment by LichKing-2234** [comment]
@ajitdas123 Sorry for the late reply, it seem like fine.

**Comment by ajitdas123** [comment]
Thank you @LichKing-2234 ,It seems like some older versions were downloaded somehow. After clearing node module, package.lock and reinstalling the packages it worked fine.
