### ISSUE TITLE
FixedPortrait mode is not working perfectly

### ISSUE THREAD

**Issue by anisurrahman072** [AgoraIO-Extensions/react-native-agora#516]
In broadcasting part i did bellow things:
1. I used setVideoEncoderConfiguration with FixedPortrait orientation mode.
2. I set setVideoEncoderConfiguration before enableVideo()

Output i noticed in android:
1.  Broadcaster device in portrait mode: 
       a. ****In Broadcasting part:**** Local video is in portrait mode. **It is OK.**
       b. **In Receiving part:** Remote video is in portrait mode. **It is OK.**

2.  Broadcaster device in landscape mode: 
       a. **In Broadcasting part:** Local video is in Landscape mode. **It is OK.**
       b. **In Receiving part:** Remote video is 90 degree rotated. **_Which is not expected._** As per this theory ( https://docs.agora.io/en/Video/video_rotation_android?platform=Android ) of Agora, in FixedPortrait orientation mode the Remote video in receiving part should always be in Portrait mode. It shouldn't be rotated by 90 degree like bellow !!!!!!
<img width="540" alt="Screenshot 2022-09-12 at 8 37 21 AM" src="https://user-images.githubusercontent.com/40535268/189564158-97e1ab12-4c86-4dec-a70e-efd9ae695d75.png">

[LichKing-2234](https://github.com/LichKing-2234) Urgently fix this issue please. We need to have a production build of our App urgently.

**Comment by LichKing-2234** [comment]
Sorry for the late reply, I think you should call `setVideoEncoderConfiguration` after `enableVideo`

**Comment by rajat-mobileCoder** [comment]
Hi @anisurrahman072 have you find any solution yet. because I'm also facing this same issue

**Comment by anisurrahman072** [comment]
Hi @rajat-mobileCoder, 
Though i'm very busy but i want to something about this. I hope you maintained the documentation & wrote the code. If you did then just follow this bellow & see if it works or not

So basically, we all know in Android/ IOS device there is a device-rotation button in the Device top navigation bar. Last time i saw that when I turned-off the device rotation mode the agora-react-native orientation mode is not working. But when i turned on the device  rotation mode then the agora-react-native orientation mode is working perfectly 🚀💯

My simple config for agora-react-native was just like bellow:
 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/40535268/209400577-9efac9d5-01ea-4b89-92b4-7853710b13f3.png">

Hope it will help you 🎉🎉

**Comment by rajat-mobileCoder** [comment]
Hi @anisurrahman072,
thanks for the response I tried your code same but its not working I used this code before and after enabling the video.
everything is working fine but orientationMode is not working after trying all solutions
<img width="535" alt="Screenshot 2022-12-27 at 6 04 24 PM" src="https://user-images.githubusercontent.com/54932417/209667457-fe4f7084-9349-4a74-8efb-3746d065a555.png">

**Comment by rajat-mobileCoder** [comment]
Hi @LichKing-2234 I tried setVideoEncoderConfiguration after enable the video but it also not worked

**Comment by anisurrahman072** [comment]
Did you tried with On & off this bellow option in your Android device or Emulator @rajat-mobileCoder 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/40535268/209670598-eddd18b4-1302-468c-8813-79496e7075ba.png">

**Comment by rajat-mobileCoder** [comment]
I searched almost everywhere but nothing worked @anisurrahman072

**Comment by anisurrahman072** [comment]
Ohhh, brother I telling the details once again. Umm hope it will help you to get the behaviour of Orientation Mode 2. Bellow I am showing you 2 scenario.

> Now I am showing you both my Input & Output Video when Android device **Auto-rotation** Off


**Input in my Android Device (Horizontal): **
<img width="459" alt="Screenshot 2022-12-27 at 7 24 09 PM" src="https://user-images.githubusercontent.com/40535268/209673042-eba20d99-f5b9-43c8-9677-e3c4b8ab8f68.png">



**Output of the above Input in Web (Used Web Agora SDK)**
<img width="1440" alt="Screenshot 2022-12-27 at 7 24 35 PM" src="https://user-images.githubusercontent.com/40535268/209673087-0a9bc6a3-2300-493f-b7bc-aaedd05c137f.png">




> Now I am showing you both my Input & Output Video when Android device **Auto-rotation** ON
**Input in my Android Device (Horizontal): **
<img width="720" alt="Screenshot 2022-12-27 at 7 25 42 PM" src="https://user-images.githubusercontent.com/40535268/209673219-7c474d7c-32e5-46d4-8bb5-2b773962b564.png">


**Output of the above Input in Web (Used Web Agora SDK)**

<img width="1440" alt="Screenshot 2022-12-27 at 7 26 08 PM" src="https://user-images.githubusercontent.com/40535268/209673276-c7a97b15-46fe-4ebd-ba3a-3963482b41cd.png">



From these above 👆👆 2 scenarios, I hope you understand the behaviour of Agora Video Orientation Mode 2. Check your outputs with these above & let me know is it already OK for you or not.
