### ISSUE TITLE
4.0.0-rc.1 fails to compile on M1 iOS simulator

### ISSUE THREAD

**Issue by radko93** [AgoraIO-Extensions/react-native-agora#525]
Hi,
I've installed the new SDK 4.0.0-rc.1. It works on Android but fails to compile on M1 iOS simulator for me on React Native 0.69. Hermes and flipper disabled.

This line fails: 
[`#import <AgoraRtcWrapper/iris_rtc_cxx_api.h>`](https://github.com/AgoraIO-Extensions/react-native-agora/blob/582bc78ce18a311a1eb03361232f0b4fcbd4d42d/ios/ReactNativeAgoraRtcNg.h#L1)

> 'AgoraRtcWrapper/iris_rtc_cxx_api.h' file not found

Seems like cocoapods are not configured probably.

**Comment by radko93** [comment]
@LichKing-2234

**Comment by luz33c** [comment]
You need to do this thing：
`cd ios & pod install`

Are you apple chip？

**Comment by radko93** [comment]
I did the installation many times. Yes I'm on Apple chip

**Comment by radko93** [comment]
How to reproduce:
1. Create an new RN project (currently 0.70.1).
2. Disable Hermes and Flipper on iOS in pod file.
3. Install agora 4.0.
4. Try to build


Repro https://github.com/radko93/TestAgora

**Comment by luz33c** [comment]
Have you checked whether your "pod install"
is Success? 
Maybe you can look at this article, which will show you how to run react native under Apple chip：
https://medium.com/@alberto.schiabel/how-to-fix-pod-install-error-in-react-native-on-mac-m1-5d79dc52f7e8

About uninstall cocoapods （Maybe you installed the wrong cocoapods ）：
https://superuser.com/questions/686317/how-to-fully-uninstall-the-cocoapods-from-the-mac-machine

(I can run your Repro in my m1 macbook)

**Comment by radko93** [comment]
Yes my pod install is successful, as for all different projects I run. I don't have Rosetta cocoapods version because it's not required.

Last thing that comes to my mind: are you running on Xcode 14 and iOS16?

**Comment by radko93** [comment]
![image](https://user-images.githubusercontent.com/7029942/191007118-486c18ce-4753-476e-8854-e89090790079.png)
![image](https://user-images.githubusercontent.com/7029942/191007163-70a8b3b4-f669-4b49-854b-7de3aaa484c3.png)
`AgoraRctWrapper` inside `AgoraIrisRTC_iOS` pod has not iOS simulator support under M1.

**Comment by radko93** [comment]
I can confirm it's working on real device. But why was the support removed?

**Comment by LichKing-2234** [comment]
It will support on the next version.

**Comment by hronnro** [comment]
I have the same issue (also have a M1 Pro apple chip). My app works on an iOS device but simulator build fails on `'AgoraRtcWrapper/iris_rtc_cxx_api.h' file not found` 

I just tried version `4.0.0` that was released earlier today but I still get the same error. Was a the simulator support supposed to be included in that release @LichKing-2234 ?

**Comment by LichKing-2234** [comment]
it will support at 4.1.0 version

**Comment by salmanrajz** [comment]
> it will support at 4.1.0 version

when will 4.1.0 Version release.?
Thanks

**Comment by LichKing-2234** [comment]
@salmanrajz The end of November

**Comment by hronnro** [comment]
@LichKing-2234 will the 4.1.0 be released this week? 😊
My team is currently doing planning for the next month and this release plays a big part in our decisions 🙏

**Comment by LichKing-2234** [comment]
the `4.1.0-rc.1` version has been released.

**Comment by atseven** [comment]
First uninstall agora: npm uninstall react-native-agora
Then install pods: cd ios && pod install
Now install agora latest version: npm install react-native-agora@4.1.0-rc.1
Now install pods again: cd ios && pod install

You are good to go :)
