### ISSUE TITLE
Mute All Remote Users.

### ISSUE THREAD

**Issue by muhamadjawad** [AgoraIO-Extensions/react-native-agora#529]
Hi All.
In my case i want to host a voice call (just like zoom ) and then wants to be able to mute or disable the mic of all the remote users that means they want  be able to talk until I permit them./
So in agora is there any method to achieve it??

**Comment by plutoless** [comment]
you will need to implement a signaling system and talk to all users in the room when you want to mute/disable them audio. the receiver side needs to react to the signaling message he receives and call muteLocalAudio api.

**Comment by jawadgolootlo** [comment]
can u provide code reference??
