### ISSUE TITLE
TypeError: Cannot read property 'SurfaceView' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by webexpert889** [AgoraIO-Extensions/react-native-agora#532]
Hi 

Just Install the new React Native app and I install `react-native-agora` and `agora-rn-uikit`

After starting the project it give me `TypeError: Cannot read property 'SurfaceView' of undefined, js engine: hermes` error.

This my react native dependencies

```
 "dependencies": {
    "agora-react-native-rtm": "^1.5.0",
    "agora-rn-uikit": "^4.0.0",
    "react": "18.1.0",
    "react-native": "0.70.1",
    "react-native-agora": "^4.0.0-rc.1"
  },
```

And this is my App.tsx code

```

import React, {useState} from 'react';
import AgoraUIKit from 'agora-rn-uikit';

const App = () => {
  const [videoCall, setVideoCall] = useState(true);
  const connectionData = {appId: 'APPID', channel: 'test'};
  const rtcCallbacks = {
    EndCall: () => setVideoCall(false)
    };
  return videoCall ? <AgoraUIKit connectionData={connectionData} rtcCallbacks={rtcCallbacks} /> : null;
};

export default App;
```
Please help me what I am wrong here!

Thank  you In Advance

**Comment by LichKing-2234** [comment]
I think you can creat an issue at the uikit repo, thanks

**Comment by srinath116** [comment]
@webexpert889 as a turn around till the issue gets resolved downgrade react-native-agora to ^3.7.1

**Comment by plutoless** [comment]
i would suggest to raise an issue in rn-uikit repo. issue closed here.

**Comment by anisurrahman072** [comment]
Not an issue of "rn-uikit repo". I'm not using "rn-uikit repo". Still getting this error after migrating to v4. 

Pretty unclear migration guide. 😒
