### ISSUE TITLE
不能安装

### ISSUE THREAD

**Issue by yirenkeji555** [AgoraIO-Extensions/react-native-agora#536]
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/48214423/194736867-99833c90-0312-44fa-8c00-99f07f06e8aa.png">

**Comment by luz33c** [comment]
**You need to install simulator and  settings of the simulator：**
install simulator：
<img width="796" alt="image" src="https://user-images.githubusercontent.com/62172559/194737038-86d6fd7d-91fd-41ff-9bf0-84b078001884.png">
settings of the simulator：
<img width="416" alt="image" src="https://user-images.githubusercontent.com/62172559/194737062-1d0f123e-8ecf-4604-8f9a-4c6e4a7ba99b.png">

<img width="491" alt="image" src="https://user-images.githubusercontent.com/62172559/194737098-85b79a0d-8ed6-4dce-80c9-66285be0cbcc.png">


**If  settings doesn't work, update Xcode to its latest version.**

**Comment by yirenkeji555** [comment]
试过了 erase all content and setting，但是还是不行，也升级了xcode 版本为 12.5.1 也是同样的情况。

**Comment by yirenkeji555** [comment]
xcode 如果要用最新的版本，需要更新Mac的系统，我正在升级……

**Comment by LichKing-2234** [comment]
请问真机可以运行么？

**Comment by yirenkeji555** [comment]
更新Mac到最新系统、xcode最新版本，终于可以了。
