### ISSUE TITLE
Using deprecated listeners in 4.0.0

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Extensions/react-native-agora#539]
Reopening #534

DeviceEventEmitter is [deprecated](https://github.com/facebook/react-native/blob/1490ab12ef156bf3201882eeabfcac18a1210352/Libraries/EventEmitter/RCTNativeAppEventEmitter.js#L15), you should use [NativeEventEmitter](https://reactnative.dev/docs/native-modules-ios#sending-events-to-javascript) instead.

**Comment by LichKing-2234** [comment]
Will be fixed in the 4.1.0 version.

**Comment by LichKing-2234** [comment]
the `4.1.0-rc.1` version has been released.
