### ISSUE TITLE
From example Screen Share not working in iOS for some devices 

### ISSUE THREAD

**Issue by yasvitajoshi309** [AgoraIO-Extensions/react-native-agora#540]
Hello all, we are using,

react-native: 0.66.4
react-native-agora: 3.7.1

We have implemented screen sharing with this

await RTCEngine.startScreenCapture({
captureAudio: true,
captureVideo: true,
videoParams: {
          bitrate: 500,
          frameRate: 15,
          width: MyConstants.windowWidth,
          height: MyConstants.windowHeight,
          contentHint: VideoContentHint.Details,
        },
});

And it's working perfect for android but for ios some devices (iPhone XR (OS 14.0.1), iPhone12) it's not working even i have tested demo sdk project in sdk example also it gives (CaptureInBackground = 6) error code in local video state change event after click on start broadcast popup button and failed to capture screen even app is in foreground state please help!

**Comment by lienbao** [comment]
iOS replaykit Prompt error ？

**Comment by yasvitajoshi309** [comment]
No error is prompting

**Comment by yasvitajoshi309** [comment]
Here is the logas for your reference

**Comment by lienbao** [comment]
replaykit process is not started from video , you can xcode debug replaykit, need to make sure
