### ISSUE TITLE
[iOS-Screen Share]: App crashes after calling showRPSystemBroadcastPickerView()

### ISSUE THREAD

**Issue by pedro-rivas** [AgoraIO-Extensions/react-native-agora#542]
**Description:**

Hey, I'm trying to implement the screen share feature I followed the demo on [src/examples/advanced/ScreenShare](https://github.com/AgoraIO-Extensions/react-native-agora/tree/main/example/src/examples/advanced/ScreenShare). Android works fine, but the app is crashing on iOS. 

I found the issue, it seems that this:
`NSURL *url = [[NSBundle mainBundle] URLForResource:nil withExtension:@"appex" subdirectory:@"PlugIns"];` is returning nil, therefore: 
`NSBundle *bundle = [NSBundle bundleWithURL:url];` Is trowing an error and the app crashes.

does anyone know which is the right **NSURL** configuration to find the **bundle url**?

Lemme know what I can do to make the issue clearer.

I attached a SS of the ReactNativeAgoraRtcNg.mm file producing the issue. 

Saludos!!

![Screen Shot 2022-11-11 at 9 45 22](https://user-images.githubusercontent.com/68823441/201375532-729db370-4f11-444c-9dd3-772be9b5a354.png)

**Comment by pedro-rivas** [comment]
You need to add the Broadcast Upload Extension to your project.

**Comment by Khubaib-Sarfraz** [comment]
how did you resolve this issue?
