### ISSUE TITLE
TypeError: Cannot read property 'showRPSystemBroadcastPickerView' of undefined

### ISSUE THREAD

**Issue by elenitaex5** [AgoraIO-Extensions/react-native-agora#545]
Hi! I'm trying to use Agora for my React Native/Typescript project. We've seen is the better way to have video calls in our app. 

Unfortunately,  following this tutorial [https://www.agora.io/en/blog/building-a-video-calling-app-using-the-agora-sdk-on-expo-react-native/](https://www.agora.io/en/blog/building-a-video-calling-app-using-the-agora-sdk-on-expo-react-native/), throws me an error when I open my app.
`TypeError: Cannot read property 'showRPSystemBroadcastPickerView' of undefined`

I'm using Expo (Expo SDK 45) in my project and I've been trying to open my app having it in Expo in my Android device, installing an apk build or in my android emulator. 

these are my **package.json** dependencies
```
"dependencies": {
    "@aws-amplify/ui-react": "^3.5.1",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/netinfo": "^9.3.0",
    "@react-native-picker/picker": "^2.4.4",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@storybook/addon-knobs": "^6.4.0",
    "@types/react-native": "^0.67.3",
    "@types/react-native-dotenv": "^0.2.0",
    "agora-react-native-rtm": "^1.5.0",
    "agora-rn-uikit": "^4.0.2",
    "amazon-cognito-identity-js": "^5.2.10",
    "aws-amplify": "^4.3.35",
    "aws-amplify-react-native": "^6.0.5",
    "expo": "^45.0.6",
    "expo-dev-client": "~1.0.0",
    "expo-device": "~4.2.0",
    "expo-image-picker": "~13.1.1",
    "expo-linking": "~3.1.0",
    "expo-notifications": "~0.15.4",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "i18next": "^21.9.1",
    "intl": "^1.2.5",
    "native-base": "^3.4.15",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-i18next": "^11.18.5",
    "react-native": "0.68.2",
    "react-native-agora": "^4.0.0",
    "react-native-animation-library": "^0.0.8",
    "react-native-dotenv": "^3.3.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.13.1",
    "react-native-signature-canvas": "^4.4.1",
    "react-native-svg": "^12.1.1",
    "react-native-web": "^0.17.7",
    "react-native-webview": "^11.22.4",
    "webpack-merge": "^5.8.0"
  }
```

Thanks for any help.

**Comment by LichKing-2234** [comment]
Pls refet to https://github.com/AgoraIO-Extensions/react-native-agora/issues/188

**Comment by elenitaex5** [comment]
Thanks @LichKing-2234 for your answer I've been reading [#188](https://github.com/AgoraIO-Extensions/react-native-agora/issues/188) before writing this post. 
I've been following the blog steps except I have my project and I'm not creating one from zero. 
And I've read is only Expo SDK 42. Is this the problem? I have to downgrade my expo SDK from 45 to 42?

**Comment by EkaanshArora** [comment]
Hi @elenitaex5 I maintain the `agora-rn-uikit` package, right now the Agora React Native UIKit only support using v3 of the sdk (`react-native-agora`). We're adding support for `v4.1.0` of the sdk as it gets released in the coming weeks.
You can downgrade `react-native-agora` to `v3.7.1` to try things out, we'll release an update shortly.

**Comment by elenitaex5** [comment]
@EkaanshArora @LichKing-2234 I've tried to download versions, but still having some errors. If I only downgrade `react-native-agora` to `v3.7.1` it seems to work, but there's only a black screen with a message 
`Attempting: test` and `Error: 110`. Looking for doc about this error is maybe an auth error? but I have my project in test mode (only AppId) and I try to create another one (if I was mistaken) but same error. 

So I've following some other fixed issues and downgrade some other packages having
```
"agora-react-native-rtm": "^1.5.0",
"agora-rn-uikit": "^3.3.0",
"expo": "^45.0.6",
 "react": "17.0.2",
 "react-dom": "17.0.2",
"react-i18next": "^11.18.5",
 "react-native": "0.68.2",
 "react-native-agora": "^3.5.3",
```

and this is the error shown
<img width="405" alt="image" src="https://user-images.githubusercontent.com/14013852/202114155-4e1ecb2f-434a-41de-8f0f-eca844d7a071.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/14013852/202114237-97ed5ab2-9e3b-495f-8dc0-f48547bfb98d.png">

I don't know if this library only works with EXPO 42? I have to downgrade expo too?

**Comment by elenitaex5** [comment]
I close it. I've started everything from the beginning and it's working fine.
