### ISSUE TITLE
Screen sharing on v4.x

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Extensions/react-native-agora#546]
Hey @LichKing-2234, we had a [method](https://api-ref.agora.io/en/voice-sdk/react-native/3.x/classes/rtcengine.html#startscreencapture) to capture the screen with v3.7.0 of the react-native SDK.

Do we have support for sharing the screen on react-native SDK v4.x? The api reference has an empty table: 
![image](https://user-images.githubusercontent.com/10047883/201942025-3d668d87-6d2e-431e-b4e0-105989fd0a86.png)

Is this planned for the future? Can we add this as a feature request?

**Comment by pedro-rivas** [comment]
Yess, its supported. Checkout this example https://github.com/AgoraIO-Extensions/react-native-agora/tree/main/example/src/examples/advanced/ScreenShare.

I'm facing some issues with the iOS screen share extension tho.

**Comment by LichKing-2234** [comment]
You can refer to the this example.

> Yess, its supported. Checkout this example https://github.com/AgoraIO-Extensions/react-native-agora/tree/main/example/src/examples/advanced/ScreenShare.
> 
> I'm facing some issues with the iOS screen share extension tho.

**Comment by pedro-rivas** [comment]
Maybe you can point me in the right direction @EkaanshArora @LichKing-2234 .

I'm trying to implement the screen share feature which is working fine on Android, but it does not on iOS (using the v4.0.0).

Calling **showRPSystemBroadcastPickerView()** opens the picker with the app extension, after pressing Start Broadcast the count down goes to 0, but it never start recording the screen (I attached a SS).

I already:

- Added the Broadcast Upload Extension.
- Updated the **NSExtensionPrincipalClass** to AgoraReplayKitHandler.

is there something I'm missing?

I'm using the RN v0.66.5 and my ios target is 12.1.

![IMG_0391](https://user-images.githubusercontent.com/68823441/202375916-8d6b5bf8-78d0-491c-892d-1eeccfef35e6.png)
![Screen Shot 2022-11-17 at 0 48 19](https://user-images.githubusercontent.com/68823441/202376077-6b316456-7e7f-489d-8c60-ec9c2b484bba.png)
![Screen Shot 2022-11-17 at 0 49 00](https://user-images.githubusercontent.com/68823441/202376194-3657bf2a-f18e-41d8-aacf-b3e23479f1e4.png)
![Screen Shot 2022-11-17 at 0 49 24](https://user-images.githubusercontent.com/68823441/202376269-417a536f-e0eb-45ba-a613-7f3d18700844.png)
