### ISSUE TITLE
Migrate all examples to hooks instead of classes

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Extensions/react-native-agora#553]
The new [React docs](https://beta.reactjs.org/apis/react/Component) recommend defining components as functions instead of classes.
![image](https://user-images.githubusercontent.com/10047883/202708832-4b9231a9-6398-41a3-a42f-a3db7cffbc4c.png)

We should migrate our example to use functions and hooks as suggested by the docs as part of the next release.

**Comment by LichKing-2234** [comment]
I think the example is just for our APIs, this feature is low priority.

**Comment by maxxfrazer** [comment]
Seems like a straightforward change to modernise the components putting it in a format that more react native developers understand, without being too much overhead for Agora.

Reasonable to put in for `v4.2.0` @LichKing-2234?

**Comment by pedro-rivas** [comment]
@LichKing-2234 a good first issue? I can help with this if you (guys) don't mind

**Comment by LichKing-2234** [comment]
@pedro-rivas If you can help, it will be very grateful.

**Comment by EkaanshArora** [comment]
@pedro-rivas hi here's a basic app to help you get started: https://github.com/AgoraIO-Community/Agora-RN-Quickstart/tree/4.x

**Comment by LichKing-2234** [comment]
we have migrate some case to hooks
