### ISSUE TITLE
Conflict with other react-native modules, other libs using RCTDeviceEventEmitter with 'onEvent'

### ISSUE THREAD

**Issue by rcugut** [AgoraIO-Extensions/react-native-agora#554]
When the lib is installed along other libs that use native modules with RCTDeviceEventEmitter, the event names (may) conflict. One example is [Pusher react-native](https://github.com/pusher/pusher-websocket-react-native/issues/54).

The [React Native code says](https://github.com/facebook/react-native/blob/49dd38f1338ab8fb37144f03980bb7f122a8f04e/Libraries/EventEmitter/NativeEventEmitter.js#L34-L36):

> Currently, all native events are fired via a global RCTDeviceEventEmitter.
> This means **event names must be globally unique**, and it means that call sites
> can theoretically listen to RCTDeviceEventEmitter (although discouraged).

https://github.com/AgoraIO-Extensions/react-native-agora/blob/603a19dbc895f7cb3600ca6a38cd6354f56f4c72/android/src/main/java/io/agora/rtc/ng/react/ReactNativeAgoraRtcNgModule.java#L106-L108

A simple solution is to just rename the event name from `"onEvent"` to be `"agorartc:event"`, or something that only this lib would use. This event is only for intra-module bridge communication only anyway. The public JS API should not change.

**Comment by LichKing-2234** [comment]
Good point! Do you actually encounter this conflict problem locally?

**Comment by EkaanshArora** [comment]
@LichKing-2234 can we target this for `4.1.0`?

**Comment by rcugut** [comment]
@LichKing-2234
> Good point! Do you actually encounter this conflict problem locally?

Yes, in my case the conflict is with the lib: https://github.com/pusher/pusher-websocket-react-native

I explained it into a github issue I opened with that project: https://github.com/pusher/pusher-websocket-react-native/issues/54

Basically, both libs use the event named `"onEvent"` :-)
