### ISSUE TITLE
createAgoraRtcEngine() does not load. The react native app crashes & call is not accepting in my M1 Mac (react-native-agora 4.1.0-rc.1)

### ISSUE THREAD

**Issue by atseven** [AgoraIO-Extensions/react-native-agora#560]
Hi, I am using the latest version of agora package **react-native-agora 4.1.0-rc.1** in my react native app. My app crashes when someone make a call into it. When I click the accept call button, the app suddenly crashes. It is not loading the **createAgoraRtcEngine()**. Below is some slight piece of code.

import {
    ClientRoleType,
    createAgoraRtcEngine,
    IRtcEngine,
    RtcSurfaceView,
    ChannelProfileType,
} from 'react-native-agora';

const agoraEngineRef= useRef()
agoraEngineRef.current = createAgoraRtcEngine();

The calling feature is working perfectly in my web app. But this thing only creating problem in the react native app. 
I don't know what is the problem. Please solve this issue community ?? I will be very thankful to you guys. Please let me know if you want to know more details about error...

**Comment by LichKing-2234** [comment]
is our demo working?

**Comment by rua26** [comment]
Faced the same issue on mac m1

**Comment by atseven** [comment]
> is our demo working?

No, nothing is working in mobile app. App suddenly crashes. I tried to debug it and even just put one line which is:

const agoraEngineRef= useRef()
agoraEngineRef.current = createAgoraRtcEngine();

But it is not loading it and app crashes. My friend which is using MacBook 2015 model and using 4.0.0 version of agora. On there side, the calling feature is working fine. But I same copy pasted his code and installed 4.1.0-rc-1 version because 4.0.0 was not allowing me to open simulator and other stuff that's why you launched this new release.
Kindly resolve this current issue that I am having...

**Comment by EkaanshArora** [comment]
Are you trying this on the simulator? I don't think the simulator is a supported target. Does it work on a physical device?

**Comment by atseven** [comment]
> Are you trying this on the simulator? I don't think the simulator is a supported target. Does it work on a physical device?

No it's also not working on physical device as well. I have iphone X but getting same issue. 
I also attached a video link where the app crashes. Please have a look:

https://www.uploadlite.com/d/8FT4bZj8XPDit8

**Comment by atseven** [comment]
@LichKing-2234, @EkaanshArora 
Any update guys ?

I'm too much worried because our app is going to live and we're just waiting for this issue to be fixed

**Comment by atseven** [comment]
> Faced the same issue on mac m1

@rua26 did you get any solution?

**Comment by rua26** [comment]
@atseven I have one solution. I returned my agora version to agora 4.0.0 and build app with intel chip

**Comment by rua26** [comment]
@atseven one update. It worked fine on their demo app.
My macbook is pro 14 inch.

**Comment by rua26** [comment]
and on simulator alse working fine.

**Comment by atseven** [comment]
> @atseven I have one solution. I returned my agora version to agora 4.0.0 and build app with intel chip

@rua26 I do not have the intel chip and let say if I arrange then everytime whenever I need to make changes in the app then I need to build there. I think its not good. And 4.0.0 is not working in my M1 chip. It throws an error of some header file is missing. That's why this new version 4.1.0-rc-1 I installed but this is creating problem as mentioned. Literally don't know what to do..

**Comment by atseven** [comment]
> @atseven one update. It worked fine on their demo app. My macbook is pro 14 inch.

@rua26 your is M1 chip? If yes, then please send me the reference link that you're talking about 🙏🏻...

**Comment by rua26** [comment]
@atseven Yes, my MacBook is an M1 Pro 14 inch. I mean the demo example provided by Agora. It's working fine on my MacBook, but I still don't know why my app crashed, maybe some settings're not right.

**Comment by atseven** [comment]
> @atseven Yes, my MacBook is an M1 Pro 14 inch. I mean the demo example provided by Agora. It's working fine on my MacBook, but I still don't know why my app crashed, maybe some settings're not right.

@rua26 can you message me please on WhatsApp +923498310350 so that we connect and try to get some solution. Agora team is not replying at all. So sad to hear it

**Comment by LichKing-2234** [comment]
@atseven any crash dump? I can't find any useful info in your video.

**Comment by atseven** [comment]
> @atseven any crash dump? I can't find any useful info in your video.

@LichKing-2234  No I didn't get anything. I just get one popup from Mac that "Your app is crashed unexpectedly"

**Comment by LichKing-2234** [comment]
unusually, you can get the dump from the console app

**Comment by atseven** [comment]
@LichKing-2234  here is that:
https://drive.google.com/drive/folders/1ROL3hbNUv1e8XY8WPGUsM73JGt-XrdNc?usp=share_link

**Comment by LichKing-2234** [comment]
@atseven sorry, I think it is not a dump. pls, refer to this.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9312526/207214367-10c2b0c7-3b6c-4bc1-9a34-fa304e1dd9b9.png">

**Comment by atseven** [comment]
I can't find this. After a lot of hustle, we planned to leave agora and planning to move to other SDK...

**Comment by rua26** [comment]
[Dump_report.docx](https://github.com/AgoraIO-Extensions/react-native-agora/files/10253583/Dump_report.docx)
@LichKing-2234 You meant this dump report?
