### ISSUE TITLE
startEchoTest is not working

### ISSUE THREAD

**Issue by y120sb** [AgoraIO-Extensions/react-native-agora#565]
Calling startEchoTest does not return audio.
The return value of the function is 0, but if I subscribe to onError in engine.registerEventHandler, onError is called with an ErrInvalidToken as the err argument.
```
engine.registerEventHandler({
    onError(err: ErrorCodeType, msg: string) {
        // err is ErrInvalidToken(110)
    },
});

const result = engine.startEchoTest();
console.log(result); // 0
```

Reproduce
react-native-agora@4.0.0

Not reproduce
react-native-agora@3.6.2

**Comment by LichKing-2234** [comment]
you can try this before the 4.2.x version.
`
callIrisApi.call(this, 'RtcEngine_startEchoTest3', {
      config: {
        enableAudio: true,
        enableVideo: false,
        token: '',
        channelId: '',
      },
    });
`
