### ISSUE TITLE
Really Pause functionality is not yet provided for Cloud Recording?

### ISSUE THREAD

**Issue by anisurrahman072** [AgoraIO-Extensions/react-native-agora#570]
Hi dev geeks,
Basically I have successfully implemented the Cloud Recording in my React Native App with AWS as Cloud storage. For your information i am using these:

- **mode**: mix
- **channelType**: Live broadcast profile
- **streamTypes**: 2 which is 'Default' (Meaning: Subscribes to both audio and video streams.)

With these above 👆👆 configurations i was successfully able to upload the recorded MP4 video to my AWS bucket. But now I need to know how to enable Pause/ onHold feature while Recording?

From this doc (link: https://docs.agora.io/en/cloud-recording/reference/rest-api/update) I have found that Pause/ onHold feature is only done for **mode: web**. Then i tried to do in some way to unsubscribing the HOST audio & video of the stream while recording to anyhow do Pause/ onHold feature. But Alas!!! I didn't find any work around solution for **mode: mix**!!

 @LichKing-2234  , @EkaanshArora you heroic guys or anyone, could you please help me. Thanks in advance 🙏🙏

**Comment by LichKing-2234** [comment]
Is possible to stop and reopen the cloud recording?

**Comment by anisurrahman072** [comment]
Hi @LichKing-2234 , successfully STOP & Re-start with new resourceID is working perfectly 💯
