### ISSUE TITLE
How to Count total Audience for LiveBroadcasting channel? No solution!!?

### ISSUE THREAD

**Issue by anisurrahman072** [AgoraIO-Extensions/react-native-agora#572]
Hi dev geeks,
I have successfully implemented the live broadcasting channel by Agora. My audience from App & even from Web are smoothly watching the streams. For your information:

- **ChannelProfile**: LiveBroadcasting
- **Broadcaster**: In my App at a time only one broadcaster will broadcast
- **Audience**: In my App a lot of audience will join in the channel to watch the broadcasting

With this above👆 configuration, I can't **get the total count of Audience** in the Channel. Don't know is it a bug or not??!!

> From Agora documentation, I found & tested that, when we are using **"_LiveBroadcasting_" Profile** then the event listener **"_UserJoined_"** will only be triggered when any other **Broadcaster** join in the channel. When a **"Audience"** join in the channel this even Listener will not trigger for **"_LiveBroadcasting_" Profile**

So as i'm also using the  **"_LiveBroadcasting_" Profile**, I'm totally unable to count the total Audience count. Could anyone please help me get a solution?

**Comment by LichKing-2234** [comment]
I think there is no solution to it. You can count it on your server.

**Comment by anisurrahman072** [comment]
@LichKing-2234 , thanks to clear it out. 

I can do it but how can i understand when an Audience went away after joining the channel due to lack of internet connection or unexpectedly shut down the App from where he joined as an Audience to the channel? Yaa, I know React Native has AppState, beforeRemove Event listeners to handle user interactions but I'm concerning about unexpected stuffs. 

Umm, I'm keeping a proposal to make this feature brother.

**Comment by jfbourne** [comment]
I solve this same issue you are having with firebase RealTime database. You can use the ref.OnDisconnect for when the user suddenly goes offline (lost internet or killed the app)

**Comment by kofiarkoh** [comment]
I am also facing same issue, the idea of countring on the server leads to my audience making multiple requests to my server which is not realy good.
I found out that when its is a communications profile, the userCount is correctly broadcasted across all users using the onRtcStats event. but this returns 2 when the profile is lives broadcasting

**Comment by anisurrahman072** [comment]
Hi @kofiarkoh thanks for your suggestion

But you may already know that **I need the Broadcasting Profile** instead of **Communications Profile** because in my scenario I have a single/ max 2 Broadcaster in a channel at a time & all others are audience. Audience can't talk to each other.

To achieve this scenario i need the Broadcasting Profile. Yaa, i know i could do a hacky solution like I could use **Communications Profile** with all audience audio mute/ zero (0) but that would be miss-leading to Agora Bandwidth loss in a channel as in **Communications Profile** Agora is providing the Audio communication feature for all users in a channel. That means all audience unnecessary getting Audio Bandwidth & my money will be lost for unnecessary for unnecessary bandwidth.

**Comment by kofiarkoh** [comment]
Yes @anisurrahman072  you are right. i also have the same scenario, i need only one audience and the rest must be audience. 
Let's hope to get a fix for this as soon as possible.

**Comment by LichKing-2234** [comment]
> I solve this same issue you are having with firebase RealTime database. You can use the ref.OnDisconnect for when the user suddenly goes offline (lost internet or killed the app)

This is a good solution, normally, your app can connect to your server by WebSocket.

**Comment by kofiarkoh** [comment]
@LichKing-2234 , the issue here is you will have to spend another time implementing another flow, meanwhile their sdk is able to count correctly when it is video call (communication profile) and emit the value every 2 seconds, so we will be glad if they can extend it to a live broadcasting

**Comment by anisurrahman072** [comment]
Hi @kofiarkoh, you are very right really. You said exactly what is cycling in my mind that why i should go for Firebase stuff to handle Agora stuff. Firebase is an another flow to maintain 😒

Umm I'm taking a decision with my CTO & team to handle this by using **Socket.io**. Hope it will help me for now with very simple code stuff also any one can use it if they wish. If I can successfully do it by using Socket.io then i will share my code here.

Also looking forward for a real solution from agora as it is already exist for **"Communications Profile"**. I wish if I could get some free time to create this feature for Agora 🤔

**Comment by LichKing-2234** [comment]
@anisurrahman072 you can refer to https://docs.agora.io/en/video-calling/reference/channel-management-rest-api?platform=android#gets-the-user-list

It may be helpful for you.

**Comment by anisurrahman072** [comment]
Yaaaaaa @LichKing-2234 you are heroic bro. it is working perfectly & fine ❤️ ❤️. I wish I could give you a treat 🎉
