### ISSUE TITLE
Issue with 3.x and 4.x working together

### ISSUE THREAD

**Issue by jfbourne** [AgoraIO-Extensions/react-native-agora#574]
Hey everyone I’m having issue trying to running version 3.x in production and 4.x in developments. 

Scenario 1:
1. User of version 3.x join channel as host/broadcaster 
2. User of version 3.x join as audience and can hear the host
3. User of version 4.x join as audience and CANNOT hear the host 

Scenario 2:
1. User of version 4.x join channel as host/broadcaster 
2. User of version 4.x join as audience and can hear the host
3. User of version 3.x join as audience and CANNOT hear the host 

Anybody able to explain what is going on with these versions? Are they not backward compatible?

**Comment by LichKing-2234** [comment]
Is our demo working for you?
