### ISSUE TITLE
[BUG] Android build failed

### ISSUE THREAD

**Issue by Resulte** [AgoraIO-Extensions/react-native-agora#575]
FAILURE: Build completed with 4 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-agora:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-agora:debugCompileClasspath'.
   > Could not find full-screen-sharing-4.1.0-1.jar (io.agora.rtc:full-screen-sharing:4.1.0-1).
     Searched in the following locations:
         https://maven.aliyun.com/repository/public/io/agora/rtc/full-screen-sharing/4.1.0-1/full-screen-sharing-4.1.0-1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find full-screen-sharing-4.1.0-1.jar (io.agora.rtc:full-screen-sharing:4.1.0-1).
     Searched in the following locations:
         https://maven.aliyun.com/repository/public/io/agora/rtc/full-screen-sharing/4.1.0-1/full-screen-sharing-4.1.0-1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find full-screen-sharing-4.1.0-1.jar (io.agora.rtc:full-screen-sharing:4.1.0-1).
     Searched in the following locations:
         https://maven.aliyun.com/repository/public/io/agora/rtc/full-screen-sharing/4.1.0-1/full-screen-sharing-4.1.0-1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find full-screen-sharing-4.1.0-1.jar (io.agora.rtc:full-screen-sharing:4.1.0-1).
     Searched in the following locations:
         https://maven.aliyun.com/repository/public/io/agora/rtc/full-screen-sharing/4.1.0-1/full-screen-sharing-4.1.0-1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==========================================================

**Comment by LichKing-2234** [comment]
请保持使用maven官方源，看起来是aliyun没有同步到
