### ISSUE TITLE
No FileList is returned from Agora Server after stop the Cloud Recording

### ISSUE THREAD

**Issue by anisurrahman072** [AgoraIO-Extensions/react-native-agora#577]
Hi,
I have successfully done Agora Cloud Recording implementation in my React Native App with AWS. Now i need to store some screenshots of recording so that in future i can show those screenshots of records as thumbnail of the video.

I have used bellow configs for uploading the snapshots to AWS:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/40535268/210327121-a3261b76-81c6-494f-aa3c-7bd875fd9a3f.png">

From the above 👆 config you understand that i have used **snapshotConfig**. From the doc (link: https://docs.agora.io/en/cloud-recording/reference/rest-api/stop#http-response#http-response) i have seen for **snapshotConfig** no **fileListMode** will be returned. Okay, this is good. That means Agora server will also not return **fileList** in the response of STOP recording API.

My question is, if no **fileList** is returned then how we will be able to store the file name & file url to database? Is there any other way to get the file url? File means "jpg" images. 

FYI, this is response from Agora when i stop the recording. No  **fileList** (means .jpg files name) is inside **serverResponse** 👇 but the snapshots were uploaded in AWS successfully ✅

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/40535268/210328216-36e13f5a-3068-4384-927e-223375545d9b.png">

Please help me, please 🙏

**Comment by LichKing-2234** [comment]
@plutoless Could you pls take a look?

**Comment by plutoless** [comment]
@anisurrahman072 
you may be use following pattern to find result jpg files in your OSS
<sid>_<cname>__uid_s_<uid>__uid_e_video_<utc>.jpg
