### ISSUE TITLE
bug: hard crash when calling engine method after release

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Extensions/react-native-agora#579]
When any engine method (like `leaveChannel`) is called after `release` the app crashes because of unsafe memory access here: https://github.com/AgoraIO-Extensions/react-native-agora/blob/d7363abf94dc731a19290cb44280b1d14a0678f0/ios/AgoraRtcNg.mm#L158

<img width="969" alt="Screenshot 2023-01-09 at 11 13 44 PM" src="https://user-images.githubusercontent.com/10047883/211372841-edead8a8-fb3a-4452-9e0a-586e2867d9aa.png">

We should handle this edge case for the user with a warning and avoid the app crash by checking the call like so:
```objc
    if (self.irisApiEngine != nullptr) {
        error_code = self.irisApiEngine->CallIrisApi(&param);
    } else {
        // handle case
    }
```

**Comment by dippathak26** [comment]
Hello, I am facing the same issue mentioned above with React native version 0.70.2 and react-native-agora version 4.1.0. Could you please update, like when 4.2.0 will be available?
Looking forward for the new release.
Thanks :)

**Comment by dhameliyawork** [comment]
Hi I am also facing this crash issue. Any update when 4.2.0 will be released? Our app release is blocked. I tried to downgrade agora version but still getting issue. 

```
 "react-native": "^0.69.7",
 "react-native-agora": "^4.1.1",
```

<img width="982" alt="Screenshot at Jan 25 18-49-56" src="https://user-images.githubusercontent.com/104249713/214573824-68b9485a-b8b2-42b9-847b-42747f5f56f2.png">

**Comment by dhameliyawork** [comment]
Hi I am also facing this crash issue. Any update when 4.2.0 will be released? Our app release is blocked. I tried to downgrade agora version but still getting issue. 

```
 "react-native": "^0.69.7",
 "react-native-agora": "^4.1.1",
```

<img width="982" alt="Screenshot at Jan 25 18-49-56" src="https://user-images.githubusercontent.com/104249713/214573824-68b9485a-b8b2-42b9-847b-42747f5f56f2.png">

**Comment by dippathak26** [comment]
> Will fix it at 4.2.0

Hello, could you please update, when this version will be released? Agora is the core functionality that needs to be implemented in app. Looking forward to hearing from you as soon as convenient.

Thanks :)

**Comment by LichKing-2234** [comment]
@dippathak26 you can refer to this commit

https://github.com/AgoraIO-Extensions/react-native-agora/commit/282d4dede4d56329f593bbb65592def1e2e78baf#diff-9ff45d0bcb0301b7c1e8617fb684ab30e81e5e7f9aee8189a0f0f50e9aaf5d8bR158

**Comment by dippathak26** [comment]
> @dippathak26 you can refer to this commit before we release the new version.
> 
> [282d4de#diff-9ff45d0bcb0301b7c1e8617fb684ab30e81e5e7f9aee8189a0f0f50e9aaf5d8bR158](https://github.com/AgoraIO-Extensions/react-native-agora/commit/282d4dede4d56329f593bbb65592def1e2e78baf#diff-9ff45d0bcb0301b7c1e8617fb684ab30e81e5e7f9aee8189a0f0f50e9aaf5d8bR158)

Hello,

Sure, let me check and refer the commit and update you if it works fine. 
Thanks for the update

**Comment by dippathak26** [comment]
> @dippathak26 you can refer to this commit before we release the new version.
> 
> [282d4de#diff-9ff45d0bcb0301b7c1e8617fb684ab30e81e5e7f9aee8189a0f0f50e9aaf5d8bR158](https://github.com/AgoraIO-Extensions/react-native-agora/commit/282d4dede4d56329f593bbb65592def1e2e78baf#diff-9ff45d0bcb0301b7c1e8617fb684ab30e81e5e7f9aee8189a0f0f50e9aaf5d8bR158)

Hello, I have made the changes as per the above link but still facing the same issue (please check the screenshot attached below). I am using react native verions 0.70.2, and I have changed the agora version to 4.1.0.
![image](https://user-images.githubusercontent.com/84957963/219563789-2617aa47-0de7-4a3b-9d39-e312278c5101.png)

**Comment by LichKing-2234** [comment]
I can't see any modifications from your screen capture.

**Comment by schalagashvili** [comment]
> @dippathak26 you can refer to this commit before we release the new version.
> 
> [282d4de#diff-9ff45d0bcb0301b7c1e8617fb684ab30e81e5e7f9aee8189a0f0f50e9aaf5d8bR158](https://github.com/AgoraIO-Extensions/react-native-agora/commit/282d4dede4d56329f593bbb65592def1e2e78baf#diff-9ff45d0bcb0301b7c1e8617fb684ab30e81e5e7f9aee8189a0f0f50e9aaf5d8bR158)

When do you plan to release the new version?
