### ISSUE TITLE
AgoraRTCException: AgoraRTCError NOT_SUPPORTED: your browser does not support setting the audio output device

### ISSUE THREAD

**Issue by vietdung97** [AgoraIO-Extensions/react-native-agora#581]
Hi Agora Team,
Sorry that my question is not related in this group. But it's still related to Agora.
I'm implementing voice call feature using agora-rtc-sdk-ng. But when I changed the output device, the error happened.
![image](https://user-images.githubusercontent.com/50390141/211757605-dec14894-eee4-40b2-a02d-8c1d14e54c90.png)

Here is my code

```
import AgoraRTC from 'agora-rtc-sdk-ng';

const client = AgoraRTC.createClient({ codec: 'h264', mode: 'rtc' });

await client.join(process.env.AGORA_APP_ID as string, channel, token || null, uid);
const localAudio = await AgoraRTC.createMicrophoneAudioTrack();
await localAudio.setMuted(false);

await localAudio.setDevice(inputId);
await localAudio.setPlaybackDevice(outputId); //throw error at this line
await client.publish([localAudio]);
```
Your device: Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Package: "agora-rtc-sdk-ng": "^4.15.1", "next": "13.1.1",

**Comment by LichKing-2234** [comment]
This issue is about the web SDK, I will close it.
Pls create a new issue here. https://github.com/AgoraIO/API-Examples-Web/issues/new
