### ISSUE TITLE
android don't trigger onJoinChannelSuccess

### ISSUE THREAD

**Issue by bastengao** [AgoraIO-Extensions/react-native-agora#582]
Join channel success but `onJoinChannelSuccess` callback was not called, `onRemoteAudioStateChanged` callback was called normally.

agora SDK 4.1.0, android 11

**Comment by LichKing-2234** [comment]
Is our demo working?

**Comment by bastengao** [comment]
> Is our demo working?

I do not try demo. I found it on our product.

**Comment by LichKing-2234** [comment]
Could you pls share your code about it?

**Comment by bastengao** [comment]
It's same with iOS, iOS will trigger callback, but android is not.

**Comment by paoloricciuti** [comment]
I have the same issue, also curiously if I leave the channel and than join again it is called

**Comment by UADACID** [comment]
same case, any progress?

**Comment by LichKing-2234** [comment]
@UADACID have you double confirmed the appId and token?

**Comment by LichKing-2234** [comment]
BTW, pls test it by our example
