### ISSUE TITLE
fix: use requiresMainQueueSetup

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Extensions/react-native-agora#583]
**WARN** Module AgoraRtcNg requires main queue setup since it overrides `init` but doesn’t implement `requiresMainQueueSetup`.
In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

This error is thrown in newer version of react-native when using this SDK. We need to check if we can initialize the SDK in a background thread and modify the implementation to avoid this warning.

From react docs:
> For iOS, if you override constantsToExport() then you should also implement + requiresMainQueueSetup to let React Native know if your module needs to be initialized on the main thread, before any JavaScript code executes. Otherwise you will see a warning that in the future your module may be initialized on a background thread unless you explicitly opt out with + requiresMainQueueSetup:. If your module does not require access to UIKit, then you should respond to + requiresMainQueueSetup with NO.

[related answer](https://stackoverflow.com/questions/50773748/difference-requiresmainqueuesetup-and-dispatch-get-main-queue)

**Comment by dcansyn** [comment]
I'm not sure how accurate this method is, but the warning message was resolved when I edited the processing seen on the video.

Video: https://youtu.be/tDVFfMZDoDc?t=214

I added this code above "supportedEvents" function in the "AgoraRtcNg.mm" file under the "node_modules\react-native-agora\ios\" folder and the error message was gone.

`+ (BOOL) requiresMainQueueSetup {
  return YES;
}`

<img width="503" alt="Ekran Resmi 2023-03-07 16 52 37" src="https://user-images.githubusercontent.com/22218232/223442662-9efc8c27-ac48-4b51-9334-7e5490a6c7b0.png">
