### ISSUE TITLE
Version 4 and react-native-agora-rawdata@0.2.0

### ISSUE THREAD

**Issue by 345ml** [AgoraIO-Extensions/react-native-agora#587]
Thanks, developers.

Does version 0.2.0 of react-native-agora-rawdata not work with version 4 or later?
I was using this in version 3.

The version 4 Example appears to be using version 0.1.0 of react-native-agora-rawdata.
- https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/example/yarn.lock#L3677
- https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/example/src/examples/advanced/ProcessVideoRawData/ProcessVideoRawData.tsx

Do you have any plans regarding this?

**Comment by 345ml** [comment]
I was using AgoraRawdata.swift to process against frames.
I am looking for a way to do that with version 4 react-native-agora as well.

**Comment by LichKing-2234** [comment]
the latest raw data library has migrated to c++, you can refer to 

https://github.com/AgoraLibrary/react-native-agora-rawdata

**Comment by 345ml** [comment]
@LichKing-2234 
Thanks.
So I need to rewrite the processing process for the frames in c++.
Got it 😢
