### ISSUE TITLE
registerVideoFrameObserver. Memory usage has not stopped rising.

### ISSUE THREAD

**Issue by 345ml** [AgoraIO-Extensions/react-native-agora#589]
https://docs.agora.io/en/video-calling/develop/stream-raw-audio-and-video?platform=react-native

Details are in the title.
Sorry, I have not seen the internal implementation of the library yet.

This can be resolved by removing the following code

```js
agoraEngineRef.current.getMediaEngine().registerVideoFrameObserver({});
```

Xcode view
![memory-react-native-agora-registerVideoFrameObserver](https://user-images.githubusercontent.com/8254811/216949075-2499e4a9-87b4-4f44-ba42-43cdea4b112e.gif)

**Comment by LichKing-2234** [comment]
This is a trial function. It has been proved that JS single thread cannot carry raw data events. This memory leak is due to thread blocking, and memory cannot be reclaimed in time.

**Comment by 345ml** [comment]
@LichKing-2234 
🙏🙏🙏

**Comment by 345ml** [comment]
@LichKing-2234 
Is there any way to access this in Swift?
