### ISSUE TITLE
[v4] Virtual background with BackgroundSourceType.BackgroundBlur works as BackgroundSourceType.BackgroundColor

### ISSUE THREAD

**Issue by pavelbabenko** [AgoraIO-Extensions/react-native-agora#596]
"react-native-agora": "^4.1.1"

`BackgroundSourceType.BackgroundBlur` doesn't work. It works the same as `BackgroundColor`

`const virtualBackgroundSource = {
  backgroundSourceType: BackgroundSourceType.BackgroundBlur,
  blur_degree: BackgroundBlurDegree.BlurDegreeMedium,
};`

**Comment by LichKing-2234** [comment]
have you tried https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/example/src/examples/advanced/VirtualBackground/VirtualBackground.tsx?

**Comment by pavelbabenko** [comment]
@LichKing-2234 Yes, it's reproducible in VirtualBackground example

**Comment by LichKing-2234** [comment]
Which device you used? It works for me.

**Comment by pavelbabenko** [comment]
@LichKing-2234 
iPhone 12, iOS 16.1.1
