### ISSUE TITLE
[v4] Compiling error with newArchEnabled: true

### ISSUE THREAD

**Issue by pavelbabenko** [AgoraIO-Extensions/react-native-agora#597]
"react-native": "0.71.3",
"react-native-agora": "^4.1.0"

The build fails when I try to build with [New Architecture](https://reactnative.dev/architecture/overview) enabled

<img width="707" alt="image" src="https://user-images.githubusercontent.com/44643721/221648877-8771acf9-21b7-4736-be61-f57573b6b6af.png">

**Comment by LichKing-2234** [comment]
It will be fixed next version
