### ISSUE TITLE
getting this error any can help 

### ISSUE THREAD

**Issue by al0kdash** [AgoraIO-Extensions/react-native-agora#601]
[](url)
![Screenshot_1677943849](https://user-images.githubusercontent.com/39987398/222914772-2ddc0ad7-e46d-4b54-9091-907effd3c64c.png)

**Comment by LichKing-2234** [comment]
have you tried the example?
btw, are you using [expo](https://github.com/AgoraIO-Extensions/react-native-agora/issues/188)?

**Comment by al0kdash** [comment]
no iam using cli. and example is not working properly. its also giving errors

**Comment by LichKing-2234** [comment]
Maybe you run the project without the workspace

**Comment by LichKing-2234** [comment]
So it not contains the native layer.
