### ISSUE TITLE
APK size too big

### ISSUE THREAD

**Issue by abdoerrahiem** [AgoraIO-Extensions/react-native-agora#604]
My app size increased to 268 MB, before using this library my app was just 60+ MB. 
How can I decrease the size? I use the latest version of react-native-agora

**Comment by LichKing-2234** [comment]
Pls follow https://github.com/AgoraIO-Extensions/react-native-agora/issues/514

**Comment by abdoerrahiem** [comment]
![Screen Shot 2023-03-14 at 17 06 17](https://user-images.githubusercontent.com/54793608/224966855-ff2f1025-3fd0-4861-9031-e00b78df54e1.png)
![Screen Shot 2023-03-14 at 17 06 41](https://user-images.githubusercontent.com/54793608/224966964-6d6a4a03-a67d-42f3-92f0-67c6ed7de0ba.png)
You mean this?

**Comment by LichKing-2234** [comment]
yes

**Comment by abdoerrahiem** [comment]
the size decreased to 140 MB. still a litte too big, but it's ok. 
thanks for the help
