### ISSUE TITLE
co hosting with different channel

### ISSUE THREAD

**Issue by imransiddiqui511** [AgoraIO-Extensions/react-native-agora#636]
there are hosts who are broadcasting on different channels how can I combine their broadcasts into one stream or how they can see each other into their leave stream , their audience also can see them

**Comment by imransiddiqui511** [comment]
any update on it ?

**Comment by LichKing-2234** [comment]
Sorry for the late reply, pls refer to https://api-ref.agora.io/en/voice-sdk/react-native/4.x/API/rtc_api_overview_ng.html#rtc_api_overview_ng__media_stream_relay_across_channels
