### ISSUE TITLE
changing user role of remote user

### ISSUE THREAD

**Issue by soorajpandey** [AgoraIO-Extensions/react-native-agora#637]
hello team,

I am looking to change the user role of remote user,
use case is whenever user raises hand the host can change role of user, I am using firebase for signalling, 
I know user can invite any remote user and user can use setClientRole to change it's role.
I am curious if it can be done from host side, thanks.
I am using token server to generate token for both host and audience.

**Comment by soorajpandey** [comment]
i fixed it.

**Comment by AbirAhsan** [comment]
> i fixed it.

Hi, I successfully changed the role from Audience to Broadcaster, but other users cannot see or hear the new broadcaster's audio/video. Can you share?
