### ISSUE TITLE
Security issue about SQL injection attacks

### ISSUE THREAD

**Issue by vunguyendhSTS** [AgoraIO-Extensions/react-native-agora#645]
**Describe the bug**
Security issue about SQL injection attacks

**To Reproduce**
Hi team

my application scanned by security team and we got issue about SQL injection attacks with description:

io/agora/utils/SqliteWrapper.java :

this.db.execSQL("delete from "" + str + "" where key = "" + str2 + "";");

When i'm trying to view actually happens inside SqliteWrapper.java by import io.agora.utils.moduleName then i just see 3 moduleName are:
NetUtils
ThreadUtils
HttpRequest

**Expected behavior**
my question is where the SQL command is and how can i view it and fix with parameter the SQL

**Comment by DengQiming-private** [comment]
We didn't use SqliteWrapper.java anymore, and will delete this file from the next official version. Thanks for your mention @vunguyendhSTS

**Comment by vunguyendhSTS** [comment]
thanks for your information. Good to hear that but can i know when the next version will release ?

This is some selfist but we only have this security issue left, good to use your next official version and our app will get secure certificate.

Thank you @DengQiming-private

**Comment by vunguyendhSTS** [comment]
One more thing

i'm using "agora-react-native-rtm": "^1.5.1", and "react-native-agora": "^4.1.2",

can i know where SqliteWrapper.java locate at on above 2 libs ? just to upgrade right lib to fix that issue
good to have some release note or exact which lib you are using SqliteWrapper.java

<img width="419" alt="image" src="https://user-images.githubusercontent.com/117509324/234746687-cf2488c8-e276-41cb-9b16-71e81a82f0fd.png">

thank you @DengQiming-private

**Comment by vunguyendhSTS** [comment]
hello @DengQiming-private 
any update on this ? it been 3 weeks and i dont see any releases from you guys

**Comment by LichKing-2234** [comment]
@vunguyendhSTS the next version is 4.2.0, this is a large version and will be released at the end of this month.

**Comment by vunguyendhSTS** [comment]
Good to here that
i'll wait until your release and verify it again then i could close this issue later
thank you again

**Comment by LichKing-2234** [comment]
fixed at 4.2.0
