### ISSUE TITLE
Background blur not enabled when enabled before broadcasting

### ISSUE THREAD

**Issue by radko93** [AgoraIO-Extensions/react-native-agora#649]
**Describe the bug**
Background blur is not applied if enabled before broadcasting.

**To Reproduce**
1. Enable background blur
```
enableVirtualBackground(
      enabled,
      {
        background_source_type: BackgroundSourceType.BackgroundBlur,
        blur_degree: BackgroundBlurDegree.BlurDegreeMedium,
      },
      {},
    )
```
3. Switch role to `ClientRoleBroadcaster`

**Expected behavior**
Background blur setting is applied even if set before switching the role.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.4

**Comment by LichKing-2234** [comment]
sorry for the late reply, Generally, most APIs need to be called after the client role is changed, but this still seems to be a problem, I will take a look.
