### ISSUE TITLE
Error when streaming directly to Facebook, AntMedia Server

### ISSUE THREAD

**Issue by xuanhieupd** [AgoraIO-Extensions/react-native-agora#663]
I'm currently using react-native-agora version 4.1.2 with the following code:

```async function initRtcEngine() {
    engineRef.current = createAgoraRtcEngine();
    engineRef.current.initialize({ appId: StreamConstants.APP_ID, channelProfile: ChannelProfileType.ChannelProfileLiveBroadcasting });
    engineRef.current.registerEventHandler({
        onConnectionStateChanged: (connection, state, reason) => {
            alert(JSON.stringify({
                connection,
                state,
                reason,
            }));
        },
        onNetworkQuality(_connection, _Uid, _txQuality, rxQuality: QualityType) {
            setState((prevState) => ({ ...prevState, networkQuality: rxQuality }));
        },
    });

    if (Platform.OS === 'android') {
        await PermissionsAndroid.requestMultiple([
            'android.permission.RECORD_AUDIO',
            'android.permission.CAMERA',
        ]);
    }

    if (Platform.OS === 'android') engineRef.current?.loadExtensionProvider('agora_clear_vision_extension');
    engineRef.current?.enableExtension('agora_video_filters_clear_vision', 'clear_vision', true);

    engineRef.current.enableVideo();
    engineRef.current.startPreview();
    setState((prevState) => ({ ...prevState, startPreview: true }));
}

function setDirectCdnStreamingVideoConfiguration() {
	engineRef.current?.setDirectCdnStreamingVideoConfiguration({
	    codecType: VideoCodecType.VideoCodecH264,
	    dimensions: {
	        width: 1280,
	        height: 720,
	    },
	    frameRate: 30,
	    bitrate: 900,
	    minBitrate: -1,
	    orientationMode: OrientationMode.OrientationModeAdaptive,
	    degradationPreference: DegradationPreference.Disabled,
	    mirrorMode: VideoMirrorModeType.VideoMirrorModeDisabled,
	});
}

function startDirectCdnStreaming() {
    setDirectCdnStreamingVideoConfiguration();

    const streamUrl = `rtmp://sin01.contribute.live-video.net/app/live_908574973_MtCZnMOyY2Unt43CudLeuzLcNWABCXYZ?abc=xyz`;

    const eventHandler = {
        onDirectCdnStreamingStateChanged(state: DirectCdnStreamingState, error: DirectCdnStreamingError, message: string) {
            console.log('onDirectCdnStreamingStateChanged', {
                state,
                error,
                message,
            });
        },
        onDirectCdnStreamingStats(stats: DirectCdnStreamingStats) {
            console.log('stats', stats);
        },
    };

    engineRef.current?.startDirectCdnStreaming(eventHandler, streamUrl, { publishCameraTrack: true, publishMicrophoneTrack: true });
    setState((prevState) => ({ ...prevState, isStreaming: true }));
}

function stopDirectCdnStreaming() {
    engineRef.current?.stopDirectCdnStreaming();
    setState((prevState) => ({ ...prevState, isStreaming: false }));
}
```

With this code, I can successfully live stream to YouTube and Twitch. However, when I change the streamUrl in the setDirectCdnStreamingVideoConfiguration function to a different live platform, I encounter the error "DirectCdnStreamingErrorNetConnect: Fails to connect to the CDN, error code = 4".

These are the streamUrls that I have tried:
+ Facebook: rtmps://live-api-s.facebook.com:443/rtmp/FB-6236964989751388-0-AbwEWyyyk94ZPABC
+ AntMedia: rtmp://test.antmedia.io/WebRTCAppEE/streamId_Op4QIQHnV

I have tested these streamUrl values with OBS software, and they work fine. However, they don't work when applied to the above code.

Could you please let me know if this is a limitation of Agora that doesn't allow streaming to other platforms, or if there might be some configuration missing in my code?

**Comment by LichKing-2234** [comment]
you can try startRtmpStreamWithTranscoding or startRtmpStreamWithoutTranscoding

**Comment by xuanhieupd** [comment]
@LichKing-2234  What can we use the startDirectCdnStreaming method for? I tried using the RTMPStreaming method, but we want to directly stream to a CDN. If we use RTMPStreaming, we still have to go through Agora MediaPush service.

**Comment by LichKing-2234** [comment]
But the direct CDN not support rtmps.

**Comment by xuanhieupd** [comment]
@LichKing-2234 Thank you for quick reply. However, I have tried AntMedia Server and it is not in the form of RTMPS. It has the following format: rtmp://test.antmedia.io/WebRTCAppEE/streamId_Op4QIQHnV.

**Comment by LichKing-2234** [comment]
Antmedia, I think the server is not responding to the protocol, probably the link has expired

**Comment by xuanhieupd** [comment]
@LichKing-2234 They still work effectively in OBS with an RTMP link with the following configuration.
![image](https://github.com/AgoraIO-Extensions/react-native-agora/assets/17641778/7077691d-1146-4cfe-9904-41ae82635e8a)

And here is the error I encounter when using the agora example.

https://github.com/AgoraIO-Extensions/react-native-agora/assets/17641778/cd45e668-42b6-4982-9749-d050dcb5403c



Am I misconfigured at any point?
