### ISSUE TITLE
Black screen show in remote user device in react native 0.71.8 version

### ISSUE THREAD

**Issue by yash1898-coder** [AgoraIO-Extensions/react-native-agora#672]
**Describe the bug**
  import {
    ClientRoleType,
    createAgoraRtcEngine,
    IRtcEngine,
    RtcSurfaceView,
    ChannelProfileType,
  } from 'react-native-agora';
  
  const LiveStreamingScreen = ({navigation,route}) => {
   const agoraEngineRef = useRef(IRtcEngine);  
  const [isJoined, setIsJoined] = useState(false); // Indicates if the local user has joined the channel
  const [audience, setAudience] = useState(false);
  const [remoteUid, setRemoteUid] = useState(0); // Uid of the remote user
  const [message, setMessage] = useState(''); // Message to the user
  const [isCoHost, setIsCoHost] = useState(false);
  
   const setupVideoSDKEngine = async () => {
      try {
        // use the helper function to get permissions
        if (Platform.OS === 'android') {
          await getPermission();
        }
        agoraEngineRef.current = createAgoraRtcEngine();
        const agoraEngine = agoraEngineRef.current;
      
        
        agoraEngine.registerEventHandler({
          onJoinChannelSuccess: () => {
            console.log('Successfully joined the channel ' + channelName);
            setIsJoined(true);
          },
          onUserJoined: (_connection, Uid) => {
            console.log('Remote user joined with uid ' + Uid);
            setRemoteUid(Uid);
          },
          onUserOffline: (_connection, Uid) => {
            console.log('Remote user left the channel. uid: ' + Uid);
            setRemoteUid(0);
          },
          })

        agoraEngine.initialize({
          appId: appId,
          channelProfile: ChannelProfileType.ChannelProfileLiveBroadcasting,
        });
      
        agoraEngineRef.current?.enableVideo()
        agoraEngineRef.current?.enableAudio();

        
      } catch (e) {
        console.log(e);
      }
    };

 const join = async () => {
      if (isJoined) {
        return;
      }
      try {
        if (agoraEngineRef.current) {
          console.log("Get Response Data:::::",token, channelName, remoteUid,route.params?.isHost)
          agoraEngineRef.current.setChannelProfile(
            ChannelProfileType.ChannelProfileLiveBroadcasting
          );
          if (route.params?.isHost) {
            agoraEngineRef.current.startPreview();
            agoraEngineRef.current.joinChannel(token, channelName, 0, {
              clientRoleType: isCoHost? ClientRoleType.ClientRoleBroadcaster:ClientRoleType.ClientRoleAudience
            });
          } else {
            setAudience(true)
            agoraEngineRef.current.joinChannel(token, channelName, remoteUid, {
              clientRoleType: ClientRoleType.ClientRoleAudience,
            });
          }
          setIsJoined(true);
        }
      } catch (e) {
        console.log(e);
      }
    };
    
    retrun(
    <View>
      {  route.params.isHost?
        <> 
        {isJoined&&
        <>
          <React.Fragment key={0}>
            <RtcSurfaceView canvas={{ uid: 0 }} style={[styles.fullscreenVideoView]} />
          </React.Fragment>

 {isCoHost &&
  <React.Fragment key={0}>

  <RtcSurfaceView canvas={{ uid:0 }} style={[styles.cohostVideoView]} />
 
</React.Fragment>
 }
 </>
}
:  
<>
{audience &&
       <React.Fragment key={remoteUid}>
            <RtcSurfaceView
              canvas={{ uid: remoteUid }}
              style={styles.fullscreenVideoView}
            />
          </React.Fragment>
}
</>
}
}
    </View>
    )
    
    }
    
    
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-agora": "^4.2.0",
    
    please help me to solve this issue.

**Comment by yash1898-coder** [comment]
Please help me solve this issue my token and appId details are right and the remote user channel connects successfully but shows a black screen, also video enable issue is not there because I added ClientRoleType.ClientRoleBroadcaster then the camera is shown but I was using ClientRoleType.ClientRoleAudience then shows a black screen.

**Comment by HackX-IN** [comment]
Hello ! I am  also facing the same issue when the clients joins the channel it’s shows up with the black screen and the version I am using is the same 


"react": "18.2.0",
"react-native": "0.71.8",
"react-native-agora": "^4.2.0",

please help me to solve this issue.

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by HackX-IN** [comment]
> is our example working?

I have tried example too the same issue occurs client or audience shows up with black screen

**Comment by yash1898-coder** [comment]
the same issue solves in the example. working fine in the host device but a black screen shown in the remote user (audience) device.

**Comment by HackX-IN** [comment]
we have finally solved this issue 
pacakage used :
 react-native --version 0.72.0 and react-native-agora --version 4.2.0
