### ISSUE TITLE
co host functionality is not working in new version 

### ISSUE THREAD

**Issue by yash1898-coder** [AgoraIO-Extensions/react-native-agora#673]
**Describe the bug**
I joined as an audience then the audience sends a request for a co-host on the host device. the host is accept requests but does not show the co-host video on both devices. please help me to solve this issue.

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by yash1898-coder** [comment]
not work in the example also.

**Comment by LichKing-2234** [comment]
which case did you run?

**Comment by yash1898-coder** [comment]
host and audience are working well. but I have implemented co-host functionality. and co-host functionality is not available in example.

**Comment by hiralari02** [comment]
@yash1898-coder have you found any solution to this?
