### ISSUE TITLE
In iOS not show video of remote user when leave old channel and join new channel

### ISSUE THREAD

**Issue by NinhNM** [AgoraIO-Extensions/react-native-agora#677]
**Describe the bug**
Not show video of remote user when leave channel old and join new channel

**To Reproduce**
Step below:
Acc 1 leave old channel and join new channel with name is "ABC"
Acc 2 leave old channel ( not same channel of acc 1)  and join new channel with name is "ABC"
I don't see remote video of remote user after Acc 2 join channel.
It just occurs when both Acc 1 and Acc 2 leaved old channel and join new channel.

**Expected behavior**
Please help !!
Thank you!

**Smartphone (please complete the following information):**
 - Device: Iphone 8
 - OS: ver > 15.0

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by NinhNM** [comment]
> 



> is our example working?

If haven't step leave old channel, Acc 1 and Acc 2 concurrent  join channel "ABC" your example is working
