### ISSUE TITLE
Screensharing Pod clarification

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Extensions/react-native-agora#678]
> > @LichKing-2234 the react native SDK uses both, should it just use one?
> > https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/react-native-agora.podspec#L20-L21
> 
> just need to using native

Re: [this comment](https://github.com/AgoraIO/Docs-Source/issues/1420#issuecomment-1627977762), can we remove `'AgoraIrisRTC_iOS'` is we're using only `'AgoraRtcEngine_iOS'`?

**Comment by maxxfrazer** [comment]
is the screen share extension using anything other than `AgoraRtcEngine_iOS/ReplayKit`?

**Comment by EkaanshArora** [comment]
Is our understanding correct—the RN SDK uses Iris Pod, but the extension uses the iOS Pod?

**Comment by LichKing-2234** [comment]
> Is our understanding correct—the RN SDK uses Iris Pod, but the extension uses the iOS Pod?

yes, RN SDK use iris and iOS pod, the extension just need to use the iOS pod
