### ISSUE TITLE
See Screen Share Feed of remote user

### ISSUE THREAD

**Issue by saad277** [AgoraIO-Extensions/react-native-agora#682]
How to view screen shared feed of remote user ?
Following this docs : https://docs.agora.io/en/video-calling/develop/product-workflow?platform=react-native
could not find anything to see the screen shared feed of remote user 

Can easily view screen sharing feed of my device with this tho :
<RtcSurfaceView
                            canvas={{
                                uid: localUid,
                                view: { zIndex: 99, position: "absolute" },

                                sourceType: VideoSourceType.VideoSourceScreen,
                                renderMode: RenderModeType.RenderModeFit
                            }}
                            style={styles.videoView}
                            zOrderMediaOverlay={true}
                        />

**Comment by saad277** [comment]
@LichKing-2234

**Comment by LichKing-2234** [comment]
you should use remoteUid to render remote video stream.
```
<RtcSurfaceView
canvas={{
uid: remoteUid,
sourceType: VideoSourceType.VideoSourceRemote,
renderMode: RenderModeType.RenderModeFit
}}
style={styles.videoView}
zOrderMediaOverlay={true}
/>
```

**Comment by saad277** [comment]
Hey @LichKing-2234  yes its working great on android but , 
Getting this error 1: No specified reason for the local video failure. on ios after configuring the broadcast extension step

**Comment by IbrarButt123** [comment]
HI @saad277 Any update from your side over this issue?

**Comment by saad277** [comment]
@IbrarButt123  i got the remote user screen share stream to show on web, android but having issues starting screen share on ios

**Comment by saad277** [comment]
@IbrarButt123  email me at saadsheikh27@gmail.com

**Comment by LichKing-2234** [comment]
> Hey @LichKing-2234 yes its working great on android but , Getting this error 1: No specified reason for the local video failure. on ios after configuring the broadcast extension step

@saad277 have you follow https://docs.agora.io/en/video-calling/develop/product-workflow?platform=react-native#project-setup

**Comment by saad277** [comment]
@LichKing-2234  yes followed every step of this 
when i call  await showRPSystemBroadcastPickerView(true); 
is shows rest other apps (who can screen share) not my app : 
![image](https://github.com/AgoraIO-Extensions/react-native-agora/assets/49332968/c0b5764e-3e96-4258-872a-3144f78d72f4)

**Comment by LichKing-2234** [comment]
@saad277 could you pls share the screenshot about the Broadcast Upload extension?

**Comment by saad277** [comment]
@LichKing-2234 
<img width="1440" alt="Screenshot 2023-08-15 at 4 33 31 PM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/49332968/1fb56314-77aa-4af7-8d6a-b1c4a5a82d56">

**Comment by saad277** [comment]
@LichKing-2234  i matched the config of xcode with your example repo , everything looks same soo far !
<img width="1440" alt="Screenshot 2023-08-15 at 4 36 07 PM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/49332968/9ddda9c1-cc68-4f09-8d11-0a88780e5fce">

**Comment by IbrarButt123** [comment]
@saad277 @LichKing-2234 Can you guys please confirm me that we can share screen in agora audio call? 
Because I am facing issue to share screen in audio call but when I convert into video call then the scree share works properly.

**Comment by LichKing-2234** [comment]
> @LichKing-2234 <img alt="Screenshot 2023-08-15 at 4 33 31 PM" width="1440" src="https://user-images.githubusercontent.com/49332968/260698776-1fb56314-77aa-4af7-8d6a-b1c4a5a82d56.png">

pls try to set iOS 12.0 which is in the Deployment Info.

**Comment by saad277** [comment]
@LichKing-2234  after setting the deployment target of the broadcast extension to 12.4 (matching the app target) I got the screen share locally to work on the device screen-shot attached but , for some reason the shared broadcast does not show to remote user  I guess i called the publish or start capture wrong some way: 
but however great progress ! thanks @LichKing-2234  🙏
![](https://airforshare.com/files/tlTnLK.png)

**Comment by LichKing-2234** [comment]
@saad277 pls refer to https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/example/src/examples/advanced/ScreenShare/ScreenShare.tsx#L268

**Comment by saad277** [comment]
Hey ! @LichKing-2234  i got it to work , i guess i was passing the wrong channel id in joinChannel ex , anyways thank you for the great response appreciated ! 🚀🙏

**Comment by lakshmankatari** [comment]
> 

if want to see screen share from remote is it same?

**Comment by saad277** [comment]
@lakshmankatari yes

**Comment by lakshmankatari** [comment]
> @lakshmankatari yes

can you share code on user end

**Comment by lakshmankatari** [comment]
<RtcSurfaceView
canvas={{
uid: remoteUid,
sourceType: VideoSourceType.VideoSourceRemote,
renderMode: RenderModeType.RenderModeFit
}}
style={styles.videoView}
zOrderMediaOverlay={true}
/>
this code will show screen share from host? to the user side?

**Comment by saad277** [comment]
@lakshmankatari  yes your code is correct

**Comment by lakshmankatari** [comment]
> @lakshmankatari yes your code is correct

its not showing screen share video display on userside
