### ISSUE TITLE
Version Migration from 3 to 4 has huge change in existing functionality. It hampers developers time ?

### ISSUE THREAD

**Issue by anisurrahman072** [AgoraIO-Extensions/react-native-agora#685]
### PROBLEM/ ISSUE
We **BasementSports** team is a paid user of @AgoraIO for last 1 year. We were using sdk version 3. Currently we are seeing that a lots of new feature came in version 4 & also version 3 has some useful methods missing. When we are in a plan to migrate to version 4 we found that there is a version migration guide. This version migration guide is saying that **there will be a lots of changes in most of all core existing functionalities**. Our app has **150+ screens** & almost **40+ screens has streaming feature**. As a result i'm almost frustrated after seeing these huge change to be done to migrate from version 3 to 4.

### SOLUTION
It would be really great if you @AgoraIO team **not changing the current functionalities**. Adding new functionalities is great but current implementations like unnecessary function name change, unnecessary function argument change, unnecessary function argument type change should be avoided.

### HELP NEEDED
Currently i'm very frustrated about it. It seems like almost a **`2 or 3 week extra work`** caused for these **huge change in existing functionalities** in version Migration to 4. Please suggest me what should i do 🙏

@LichKing-2234 could you please help here?

**Comment by qiuyanli1990** [comment]
Hi, 
Can you please help to raise a support ticket from your Agora console.  Let's schedule a session to review the migration doc and sort out what changes you need to make and what changes you can safetly ignore. I don't think you need to do all the changes mentioned in the migration guide.
