### ISSUE TITLE
Conditionally loading full or basic agora library

### ISSUE THREAD

**Issue by JonatanSalas** [AgoraIO-Extensions/react-native-agora#686]
Hi! First of all, thanks to the community for their efforts on this project. 

I'm working on an application that relies heavily in agora for video calls. 

After performing a release build and analyzing it I realize that there's a lot of libraries that are loaded into the APK but aren't being used. **This performs an increase of 35/40MB in APK size.**

<img width="1070" alt="Screen Shot 2023-08-01 at 18 02 39" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/7697196/11d0c02b-c73a-4aa9-a265-40dae9ac6cd0">

I think that it would be possible to make or provide a config in order that this library loads the full or the basic version of the agora native library. 

I'm investing some efforts in doing so, a PR with this support would be something that you would be able to accept?

**Comment by LichKing-2234** [comment]
you can refer to https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1214
