### ISSUE TITLE
[Pod issue] pod install so slow and get stuck

### ISSUE THREAD

**Issue by iita71737** [AgoraIO-Extensions/react-native-agora#690]
**Describe the bug**

![Screenshot 2023-08-10 at 1 40 50 PM](https://github.com/AgoraIO-Extensions/react-native-agora/assets/11864209/fe311306-6e84-4caa-8f8a-d59dd93857d1)

SKD url which get stuck : [HERE](https://download.agora.io/sdk/release/AgoraRtcEngine_iOS-4.2.1.zip)

```
-> Installing AgoraRtcEngine_iOS (4.2.0)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/mk/pjslmr954696rg78rd35rsqr0000gp/T/d20230810-7500-w1vy8u/file.zip https://download.agora.io/sdk/release/AgoraRtcEngine_iOS-4.2.0.zip --create-dirs
   --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3'
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     2  105M    2 2539k    0     0  15260      0  2:00:29  0:02:50  1:57:39 10263
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mbpr apple M1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LichKing-2234** [comment]
what country you are in?

**Comment by chenqi777** [comment]
Try turning off the network proxy

**Comment by iita71737** [comment]
> what country you are in?

I'm located in TW now.

But now is OK, 

I'm not sure if my network problem or macbook problem ,

thanks a lot !
