### ISSUE TITLE
User Offline not triggering in live broadcasting after user closes app directly without clicking on leave channel

### ISSUE THREAD

**Issue by lakshmankatari** [AgoraIO-Extensions/react-native-agora#694]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maxxfrazer** [comment]
this is a big introduced since the core sdk 4.2.0, a fix is in the works for 4.2.3; apologies for the inconvenience! the feature works correctly in all 4.1.x versions

**Comment by lakshmankatari** [comment]
it doesn't work for 3.7.0?

**Comment by maxxfrazer** [comment]
it is a much newer feature than 3.7. 3.x versions are being sunset very soon, 4.x is the version that should be used

**Comment by lakshmankatari** [comment]
and 4.x supports running call while app in background with floating windows ? is it possible?

**Comment by lakshmankatari** [comment]
Error: The package 'react-native-agora' doesn't seem to be linked. getting this error when I upgrade from 3 to version 4

**Comment by lakshmankatari** [comment]
**### getting this error**
require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 ERROR  Error: The package 'react-native-agora' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo Go
, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

**Comment by lakshmankatari** [comment]
> it is a much newer feature than 3.7. 3.x versions are being sunset very soon, 4.x is the version that should be used

even this new version not helping to track user offline when they close it directly without using leave channel

**Comment by maxxfrazer** [comment]
> even this new version not helping to track user offline when they close it directly without using leave channel

as mentioned, the 4.1.x versions do, and 4.2.3 will have it fixed.

**Comment by lakshmankatari** [comment]
> > even this new version not helping to track user offline when they close it directly without using leave channel
> 
> as mentioned, the 4.1.x versions do, and 4.2.3 will have it fixed.
even on 4.1.2 useroffline not triggering

**Comment by lakshmankatari** [comment]
I am asking incase of broadcasting, in broadcasting profile host unable to track if user goes offline

**Comment by lakshmankatari** [comment]
screen share not working if joined with video call followed all documentation joinchannelwithuseraccount not showing screen capture on user screen
