### ISSUE TITLE
Rtcsurfaceview how to render video on audience side in broadcasting

### ISSUE THREAD

**Issue by lakshmankatari** [AgoraIO-Extensions/react-native-agora#697]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LichKing-2234** [comment]
pls refer to our example https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/example/src/examples/basic/JoinChannelVideo/JoinChannelVideo.tsx
