### ISSUE TITLE
while using startscreencapture() not showing on remote side in example remote side code not written

### ISSUE THREAD

**Issue by lakshmankatari** [AgoraIO-Extensions/react-native-agora#699]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lakshmankatari** [comment]
can anyone help me please?

**Comment by LichKing-2234** [comment]
pls refer to https://github.com/AgoraIO-Extensions/react-native-agora/issues/682
