### ISSUE TITLE
navigate. goBack, black module appears

### ISSUE THREAD

**Issue by Huang-zekai** [AgoraIO-Extensions/react-native-agora#700]
After entering the video room and using navigate. goBack, a black module will appear at the top. When the black module is clicked on other routes, this problem will only occur in release mode
![img_v2_94b2ca84-3fa2-4bae-8257-4540a5b69a5g](https://github.com/AgoraIO-Extensions/react-native-agora/assets/82138184/f818471a-c92f-4513-a462-9ae8d7e01ac3)

**Comment by LichKing-2234** [comment]
you can try TextureView
