### ISSUE TITLE
No sound to other users on mic enable IOS devices.

### ISSUE THREAD

**Issue by rahulnainwalttn** [AgoraIO-Extensions/react-native-agora#707]
**Describe the bug**
When enabling mic in ios device audio is not getting to other users.

**To Reproduce**
User react-native-agora sdk "react-native-agora": "^4.0.0" and try to mute / unmute mic.

**Expected behavior**
On mic enable audio should pass to another users.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MackBook Pro M1 Pro

**Smartphone (please complete the following information):**
 - Device: iphone 13
 - OS: 16.3

**Additional context**
Same issue - https://github.com/AgoraIO-Extensions/react-native-agora/issues/561

**Comment by LichKing-2234** [comment]
Is our example working for you?

**Comment by rahulnainwalttn** [comment]
Happening the same in android too now. Sometime works fine.
