### ISSUE TITLE
Android Build failed

### ISSUE THREAD

**Issue by yasir-hussain-kodexo** [AgoraIO-Extensions/react-native-agora#712]
**Describe the bug**
Android App fails when I tried to run it, getting this error:
> Task :app:processAmazonDebugMainManifest FAILED
[io.agora.rtc:full-sdk:4.2.1] /Users/hs/.gradle/caches/transforms-3/e0422e039476ac37bc0b4cb51ad69a9f/transformed/jetified-full-sdk-4.2.1/AndroidManifest.xml Warning:
        Namespace 'io.agora.rtc' used in: io.agora.rtc:full-sdk:4.2.1, io.agora.rtc:iris-rtc:4.2.1-build.1.

**To Reproduce**
1. Create a new react native app
2. Run android app using command `yarn run android or npm run android`

**Expected behavior**
App builds and runs successfully

**Screenshots**
<img width="1031" alt="Screenshot 2023-10-09 at 7 45 11 PM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/102813851/9a0e696a-f6da-4d5b-a5e5-3b6740c2d213">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.6

**Comment by LichKing-2234** [comment]
Pls try 4.2.3

**Comment by talha-irshad-kodexo** [comment]
@LichKing-2234 still getting this error even after update:

```
 > Task :app:processAmazonDebugMainManifest FAILED
[io.agora.rtc:full-sdk:4.2.3] /Users/ishop/.gradle/caches/transforms-3/8372993a85eace354abd6e12156e786e/transformed/jetified-full-sdk-4.2.3/AndroidManifest.xml Warning:
        Namespace 'io.agora.rtc' used in: io.agora.rtc:full-sdk:4.2.3, io.agora.rtc:iris-rtc:4.2.3-build.4.
```
Tried these steps to resolve but unfortunately got no luck:

- Cleared cache using 
```
cd android && ./gradlew clean
``` 
- Deleted /Users/ishop/.gradle/caches folder and tried running again
- Deleted node_modules and installed again

installed version:
"react-native-agora": "^4.2.4"

React Native version: 0.72.5

Environment: Mac OS 13.5.2
M1 macbook pro 2020

**Comment by LichKing-2234** [comment]
I will try it later.

**Comment by LichKing-2234** [comment]
It works for me.
```
npx react-native@latest init AwesomeProject
cd AwesomeProject
yarn add react-native-agora@4.2.4
yarn android
```
