### ISSUE TITLE
Why I can't initialize rtcEngine?

### ISSUE THREAD

**Issue by idnfata** [AgoraIO-Extensions/react-native-agora#713]
Hi there, 
i got task to implement voice calling using react-native-agora, i have try the documentation instruction

https://docs.agora.io/en/voice-calling/get-started/get-started-sdk?platform=react-native

and this example https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/example/src/examples/basic/JoinChannelAudio/JoinChannelAudio.tsx

but still, i get an error like this

<img width="950" alt="Screen Shot 2023-10-15 at 2 56 00 PM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/68660403/af64c068-6761-4b22-9da9-82d44e371bb9">

**Comment by LichKing-2234** [comment]
<img width="797" alt="image" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/9312526/ffc8981b-33c7-4a1c-ac4d-3d6a535850d6">
You should disable the debug mode

**Comment by LichKing-2234** [comment]
you can refer to https://reactnative.dev/docs/next/native-modules-android#synchronous-methods
