### ISSUE TITLE
Volume Indicator event not sending remote UID

### ISSUE THREAD

**Issue by emmanuel-D** [AgoraIO-Extensions/react-native-agora#715]
**Describe the bug**
During a Audio Call with more than 2 users (also when only 2 users in call), the UID information of remote Users talking with highest volume are not sent into the `onVolumeIndicatorChanged` event.

It was previously working in version 3.7 but after migrating to V4.0 , it stops to works and only local User UID is received into the event.

**To Reproduce**
1. Initialize the RTC engine with enableVolumeIndicator(...) called with the default Params.
2. Enter the Channel with 2 or more Users on differents devices
3. Log incoming Volume indicator events
4. You can only see local UID information in the console logs

**Expected behavior**
The logs should also contains Remote UID volume Information just like it was in the SDK Version 3.7

**Smartphone (please complete the following information):**
 - OS: [ iOS any version of iOS from 14. and over / Android 12+ and over]
 - Device: [iPhone 12 Pro, 13 Pro, 14 Pro, Pixel 5, 6, 7]
**Additional context**

In SDK V.3.7 it was working fine
But since migrated to V.4.0, it no more working and the Remote UID volume Information are not received in the events.

**Comment by LichKing-2234** [comment]
<img width="1052" alt="image" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/9312526/1bb44c62-80fb-4ede-9726-fe7b95d35277">
I have tested it, it working.
