### ISSUE TITLE
Error when upload an app to app store apple

### ISSUE THREAD

**Issue by ChrisNg02655332** [AgoraIO-Extensions/react-native-agora#717]
**Describe the bug**
seems there are some errors with the agora package with CFBundleShortVersionString must be 3 parts only not 4 can you fix it to complete the upload of the app?

**Screenshots**
<img width="731" alt="Screenshot 2023-10-20 at 4 31 05 PM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/51181802/cb3bdb17-9ec1-43c4-8fc6-6e999270e0b6">

<img width="768" alt="Screenshot 2023-10-20 at 4 28 31 PM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/51181802/efd6bedc-2f85-4700-a4ce-3c6e6fadaeb8">

**Additional context**
xcode: 15.0
react-native: "^0.71.6"
react-native-agora: "^4.2.1"

**Comment by radko93** [comment]
It is fixed in #716, for now you can set your version to 4.2.1

**Comment by ChrisNg02655332** [comment]
It worked now. Thank you
