### ISSUE TITLE
Typescript definitions broken

### ISSUE THREAD

**Issue by radko93** [AgoraIO-Extensions/react-native-agora#718]
**Describe the bug**
After an update to 4.2.4 from 4.2.1 Typescript types are broken

```
Could not find a declaration file for module 'react-native-agora'. '....../node_modules/react-native-agora/lib/commonjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-agora` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-agora';`

```

**To Reproduce**
Import anything from `react-native-agora`

React Native 0.72.5 and typesctipt 5.1.6.

**Comment by LichKing-2234** [comment]
It is a mistake, pls modify this line in  `node_modules/react-native-agora/package.json`, then use [patch-package](https://www.npmjs.com/package/patch-package) to fix it before the next version.
```
"types": "lib/typescript/index.d.ts",
```
to
```
"types": "lib/typescript/src/index.d.ts",
```

**Comment by LichKing-2234** [comment]
The root cause is we upgrading to the latest version of [create-react-native-library](https://www.npmjs.com/package/create-react-native-library), but the root file location of types has been changed.

**Comment by LichKing-2234** [comment]
Also, you can npm install our SDK by GitHub commit
```
"react-native-agora": "github:AgoraIO-Extensions/react-native-agora#11c6b3d5b626b91a589b8cf75ef26e0a18ca5ed2",
```

**Comment by LichKing-2234** [comment]
The version 4.2.5 has been released.
