### ISSUE TITLE
打包出来报错

### ISSUE THREAD

**Issue by wulaizi** [AgoraIO-Extensions/react-native-agora#739]
手机1加10 pro
系统ColorOS 13.1
通过as 连着手机开发 或者在苹果模拟器都是能正常使用，
但是当打包出来 就会闪退，
把 react-native-agora的代码屏蔽掉 再打包出来，就正常了。
以下是部分报错信息
<img width="1271" alt="Snipaste_2023-11-13_11-25-26" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/33690834/f8caab78-86dc-4b15-a09b-92e2f7d276fa">
<img width="1236" alt="Snipaste_2023-11-13_11-25-58" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/33690834/5204c31c-51c2-42d1-a99d-86ff1d555133">
<img width="1272" alt="Snipaste_2023-11-13_11-26-28" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/33690834/27cb5342-e614-4799-a6cd-eff313e1e0b9">

**Comment by LichKing-2234** [comment]
有两个排查方向：
1. 方便截图下最终打包的产物里有哪些.so么，需要确认是否包含了我们所有的so
2. 检查下配置了避免混淆io.agora.*，如果没有则配置下

**Comment by wulaizi** [comment]
> 有两个排查方向：
> 
> 1. 方便截图下最终打包的产物里有哪些.so么，需要确认是否包含了我们所有的so
> 2. 检查下配置了避免混淆io.agora.*，如果没有则配置下

确实是混淆的问题,我把这个加入了不混淆 就可以了

**Comment by wulaizi** [comment]
> > 有两个排查方向：
> > 
> > 1. 方便截图下最终打包的产物里有哪些.so么，需要确认是否包含了我们所有的so
> > 2. 检查下配置了避免混淆io.agora.*，如果没有则配置下
> 
> 确实是混淆的问题,我把这个加入了不混淆 就可以了

感谢
