### ISSUE TITLE
SDK Working in debug mode but not in release.

### ISSUE THREAD

**Issue by aksainiarun** [AgoraIO-Extensions/react-native-agora#754]

**Comment by guoxianzhe** [comment]
@aksainiarun Can you give me some specific details about your problems?

**Comment by YuXueBJ** [comment]
<img width="706" alt="image" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/5047984/9c607841-020a-474a-9325-e8b4869f2538">

**Comment by guoxianzhe** [comment]
@YuXueBJ Can you tell me what version this error occurred in?
