### ISSUE TITLE
Build size increased in release mode

### ISSUE THREAD

**Issue by areebshakeel** [AgoraIO-Extensions/react-native-agora#757]
When i'm adding the agora package in my react native project version 0.72.6 the build increases massively around 150MB which is too big for any application. i made sure by removing the agora package and the build size is normal without this package. any idea how we can reduce the build size in release mode with this package installed in RN app.

**Comment by favaztechcurve** [comment]
I am also facing the same problem. before integrating this agora my app sie is 50 mb and after integrating it goes to 300 + so i done something in build.gradle which was recommended by community issues. but still the app size is above 150 i guess.

**Comment by guoxianzhe** [comment]
please check https://github.com/AgoraIO-Extensions/react-native-agora/issues/604 and https://github.com/AgoraIO-Extensions/react-native-agora/issues/514

**Comment by areebshakeel** [comment]
> please check #604 and #514
i'm still facing the same issue. remember i'm using the react native latest architecture version 0.72.6

**Comment by guoxianzhe** [comment]
@areebshakeel 

You can remove the unnecessary extension libraries of the Agora native sdk to reduce the APP size
https://docs.agora.io/en/video-calling/reference/downloads?platform=android#remove-unneeded-plugins
https://docs.agora.io/en/video-calling/reference/downloads?platform=ios#remove-unneeded-plugins
