### ISSUE TITLE
Camera preview not working 

### ISSUE THREAD

**Issue by favaztechcurve** [AgoraIO-Extensions/react-native-agora#759]
before starting live broadcast i have to enable users camera which users can see how his face looks like etc..but unfortunatly this screen become blank in my device. live screen is working perfectly. could anyone help me with this? iam using react native version 0.71.14. and agora version "react-native-agora": "^4.2.6",

`import React, {useRef, useState, useEffect} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  Image,
} from 'react-native';
import {PermissionsAndroid, Platform} from 'react-native';
import {
  createAgoraRtcEngine,
  RtcSurfaceView,
  ChannelProfileType,
  ClientRoleType,
} from 'react-native-agora';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import SVGImage from '../../../components/SVGImages';
import {PATH, SCREENS} from '../../../shared/constants';
import fonts from '../../../shared/theme/fonts';
import {palette} from '../../../shared/theme/themes';
import * as NavigationService from '../../../navigation/NavigationService';
import AppModalWithDuelButton from '../../../components/AppModalWithDuelButton';
import {generatePublisherLiveStreamToken} from '../../../services/api/apiCall';
import {useSelector} from 'react-redux';

const LiveLandingScreen = () => {
  const agoraEngineRef = useRef(null);
  const [isModalVisible, setIsModalVisible] = useState(false);

  const userId = useSelector(
    state => state?.auth?.userProfile?.user_info?.superstar_id,
  );

  const usersDp = [
    require('../../../../assets/images/user3.png'),
    require('../../../../assets/images/user2.png'),
    require('../../../../assets/images/user1.png'),
  ];

  useEffect(() => {
    setupVideoSDKEngine();
    return () => (agoraEngineRef.current = null);
  }, []);

  const setupVideoSDKEngine = async () => {
    try {
      if (Platform.OS === 'android') {
        const granted = await getPermission();
        if (!granted) {
          console.log('Permissions not granted');
          return;
        }
      }
      agoraEngineRef.current = createAgoraRtcEngine();
      const agoraEngine = agoraEngineRef.current;

      agoraEngine.setChannelProfile(
        ChannelProfileType.ChannelProfileLiveBroadcasting,
      );

      agoraEngine.startPreview();
    } catch (e) {
      console.log(e);
    }
  };

  const getPermission = async () => {
    if (Platform.OS === 'android') {
      const permissions = await PermissionsAndroid.requestMultiple([
        PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        PermissionsAndroid.PERMISSIONS.CAMERA,
      ]);
      return (
        permissions[PermissionsAndroid.PERMISSIONS.CAMERA] === 'granted' &&
        permissions[PermissionsAndroid.PERMISSIONS.RECORD_AUDIO] === 'granted'
      );
    }
    return true;
  };

  const join = async () => {
    try {
      const uniqueChannelName = 'channel-' + Date.now();
      const response = await generatePublisherLiveStreamToken({
        channelName: uniqueChannelName,
      });

      const resData = response?.data?.data?.data;

      const liveToken = resData?.token;
      const liveId = resData?._id;
      console.log('Response after generating token', resData);
      if (liveToken) {
        setIsModalVisible(false);
        NavigationService.navigate(SCREENS.GO_LIVE, {
          liveToken,
          channelName: uniqueChannelName,
          uid: userId,
          live_id: liveId,
        });
      }
    } catch (e) {
      console.error('error', e);
    }
  };

  return (
    <SafeAreaView style={styles.main}>
      <ScrollView style={styles.scroll}>
        <React.Fragment key={0}> 
            <RtcSurfaceView canvas={{uid: 0}} style={styles.videoView} />
        </React.Fragment>
      </ScrollView>

      <View style={styles.mainContainer}>
        <TouchableOpacity
          style={styles.backBtn}
          onPress={() => {
            console.log('pressed fz1');
            NavigationService.goBack();
          }}>
          <SVGImage svgContent={PATH.back} height={18} width={18} />
        </TouchableOpacity>

        <View style={styles.topTxtContainer}>
          <View style={styles.container}>
            {usersDp.map((image, index) => {
              return (
                <Image
                  key={index}
                  source={image}
                  style={[
                    styles.image,
                    {
                      marginLeft: index === 0 ? 0 : -40,
                      zIndex: -index + 2,
                    },
                  ]}
                />
              );
            })}
          </View>
          <Text style={styles.topTxt}>20 followers active now</Text>
        </View>

        <View style={styles.bottomContainer}>
          <TouchableOpacity
            onPress={() => {
              agoraEngineRef.current = null;
              setIsModalVisible(true);
            }}>
            <SVGImage svgContent={PATH.start_live_button} />
          </TouchableOpacity>
        </View>
      </View>
      {isModalVisible && (
        <AppModalWithDuelButton
          isVisible={true}
          svgContent={PATH.correct}
          title={'Are you sure?'}
          description={'To start the live'}
          btn1Title={'Cancel'}
          btn2Title={'Go Live'}
          onClose={() => setIsModalVisible(false)}
          onPressBtn2={() => join()}
          onPressBtn1={() => {
            setIsModalVisible(false);
          }}
        />
      )}
    </SafeAreaView>
  );
};`

**Comment by guoxianzhe** [comment]
@favaztechcurve please call [engine.initialize](https://api-ref.agora.io/en/voice-sdk/react-native/4.x/API/class_irtcengine.html#api_irtcengine_initialize) first
