### ISSUE TITLE
Support For usage alongside Expo Updates

### ISSUE THREAD

**Issue by OliverGeorge8** [AgoraIO-Extensions/react-native-agora#763]
**Describe the bug**
When using Both react-native-agora and expo updates i get the following error

**To Reproduce**
1. Create a new expo project with SDK v50
2. install react-native-agora v4.2.6 and expo-updates  v0.24.9
3. Try to build the app you will get the following error

**Expected behavior**

**Screenshots**
<img width="903" alt="Screenshot 2024-01-29 at 1 01 14 AM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/29260492/0795f6f2-e117-428d-9d32-3b8e0ebe2b3a">
<img width="419" alt="Screenshot 2024-01-29 at 1 01 41 AM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/29260492/9d11177f-bdff-4a66-842a-f7f0cd7db4f0">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1  (M1)

**Comment by guoxianzhe** [comment]
@OliverGeorge8  react-native-agora is using native modules, please refer https://www.agora.io/en/blog/building-a-video-calling-app-using-the-agora-sdk-on-expo-react-native/

**Comment by thebillzh** [comment]
@guoxianzhe Any timeline update on the patch release? Thanks

**Comment by guoxianzhe** [comment]
@thebillzh The plan is to release it together with 4.3.0 in the next few days.

**Comment by guoxianzhe** [comment]
4.3.0 have been released
