### ISSUE TITLE
Unsupported filename extension

### ISSUE THREAD

**Issue by MuhammadKomail** [AgoraIO-Extensions/react-native-agora#766]
error: node_modules/react-native-agora/src/specs/AgoraRtcSurfaceViewNativeComponent.tsx: /Users/hafiz/Documents/VideoCalling/node_modules/react-native-agora/src/specs/AgoraRtcSurfaceViewNativeComponent.tsx: Unable to parse file '/Users/hafiz/Documents/VideoCalling/node_modules/react-native-agora/src/specs/AgoraRtcSurfaceViewNativeComponent.tsx'. Unsupported filename extension.
<img width="259" alt="Screenshot 2024-02-06 at 11 19 18 am" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/92737744/805b6502-e12c-4d4e-9ea0-5a0a347e2687">

**Comment by emilnilimaa** [comment]
We get the same error.
After upgrading to expo 50 and react-native 0.73.4

**Comment by xhirazi** [comment]
+1

**Comment by xhirazi** [comment]
@MuhammadKomail 
fix issue [here](https://github.com/AgoraIO-Extensions/react-native-agora/pull/767) add patch accordingly.

**Comment by guoxianzhe** [comment]
Duplicate with #763 and will fix in #748
#748 will release in end of February, please make a patch temporarily

**Comment by emilnilimaa** [comment]
If we use the branch, it produces loads of errors hmm...
