### ISSUE TITLE
TS error with react native 0.73 and Expo 50

### ISSUE THREAD

**Issue by emilnilimaa** [AgoraIO-Extensions/react-native-agora#768]
node_modules/agora-react-native-rtm/src/RtmEngine.ts:441:20 - error TS2339: Property 'removeSubscription' does not exist on type 'NativeEventEmitter'.

**Comment by guoxianzhe** [comment]
Duplicate with #763 and will fix in #748
#748 will release in end of February, please make a patch temporarily

@emilnilimaa
