### ISSUE TITLE
V4 Migration Guide is pretty unclear

### ISSUE THREAD

**Issue by anisurrahman072** [AgoraIO-Extensions/react-native-agora#773]
I'm using Agora for last 2 years. All the code was working pretty well with version v3 **(^3.7.0)**. Recently started the migration to v4 **(^4.3.0-build.1)**. Found a migration guide. ([**Link**](https://docs.agora.io/en/video-calling/develop/migration-guide?platform=react-native#what-has-changed))

I found that the MIGRATION guide of above is pretty unclear. Just want to share 1 example below 👇

### In V3 I used this code & it was working pretty well 👇

```javascript
import { RtcLocalView, VideoRenderMode } from 'react-native-agora'

return (
        <RtcLocalView.SurfaceView
		renderMode={VideoRenderMode.Hidden}
		zOrderMediaOverlay={false}
		zOrderOnTop={false}
		style={styles.rtcViewStyle}
	/>
);
```

When I converted the version to v4 from package.json file, I see that all of these **RtcLocalView**, **VideoRenderMode** are stale. Ok great, but why they were **not mentioned in the "Migration Guide"** ?

### This waste my time to identify, "Hey, what happened! Migration guide didn't specify it 😵‍💫 ". 

My concern, did I miss any new Migration guide or some thing like that ? Or If I'm Ok, then what are the new code in V4 instead of above mentioned functions of V3 ?

@LichKing-2234 would you help here please ? We are a paid customer for last 2 years.

**Comment by LichKing-2234** [comment]
```
import {
  RtcSurfaceView,
} from 'react-native-agora';
```

pls refer to https://docs.agora.io/en/video-calling/get-started/get-started-sdk?platform=react-native#handle-the-system-logic

**Comment by anisurrahman072** [comment]
Thanks @LichKing-2234 for the link. Let me read it. Will it show all the changes for V4 ?

**Comment by LichKing-2234** [comment]
> Thanks @LichKing-2234 for the link. Let me read it. Will it show all the changes for V4 ?

just the usage for V4, if you want more changes, pls read https://docs.agora.io/en/video-calling/develop/migration-guide?platform=react-native

**Comment by anisurrahman072** [comment]
> > Thanks @LichKing-2234 for the link. Let me read it. Will it show all the changes for V4 ?
> 
> just the usage for V4, if you want more changes, pls read https://docs.agora.io/en/video-calling/develop/migration-guide?platform=react-native

I paste this link in the ISSUE description already & this migration guide has very limited info !!!

Another example that was not defined in the migration guide 👇

<img width="483" alt="Screenshot 2024-03-18 at 3 57 40 PM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/40535268/5eb2476f-4497-4b91-953d-60dc67a9e140">

There is no explanation of how can we do this for V4 ? As I see the functions here are deprecated in V4 !

**Comment by anisurrahman072** [comment]
Hi @LichKing-2234, due to lack of proper migration guide, it really wasting dev times. Like I found all these changes in V4 by reading the huge big documentation deeply. It would be better if these changes were in Migration Guide 🐥

<img width="808" alt="Screenshot 2024-03-18 at 5 37 29 PM" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/40535268/2a7bb930-4315-4811-ab57-4e651a63a33c">

**Comment by LichKing-2234** [comment]
> > > Thanks @LichKing-2234 for the link. Let me read it. Will it show all the changes for V4 ?
> > 
> > 
> > just the usage for V4, if you want more changes, pls read https://docs.agora.io/en/video-calling/develop/migration-guide?platform=react-native
> 
> I paste this link in the ISSUE description already & this migration guide has very limited info !!!
> 
> Another example that was not defined in the migration guide 👇
> 
> <img alt="Screenshot 2024-03-18 at 3 57 40 PM" width="483" src="https://private-user-images.githubusercontent.com/40535268/313629819-5eb2476f-4497-4b91-953d-60dc67a9e140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTYyMzIsIm5iZiI6MTcxMDgxNTkzMiwicGF0aCI6Ii80MDUzNTI2OC8zMTM2Mjk4MTktNWViMjQ3NmYtNDQ5Ny00YjkxLTk1M2QtNjBkYzY3YTllMTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAyMzg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTg4YzRkZDY1YjcxN2QyYjg3ZTI2YjVmN2ViZGE5MTNjOTIxZjMyMGQ2MzVjOGNjZTM5OGY5NjdkOTBlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UL9vDiyfhClXOMKooGPJAh1xOMayYPzEn-uz48urqJ0">
> There is no explanation of how can we do this for V4 ? As I see the functions here are deprecated in V4 !

```
await _engine.current.setCameraCapturerConfiguration({
cameraDirection: CameraDirection.Rear
})
```
