### ISSUE TITLE
How to upload Agora SDK logs to Agora, now that `IRtcEngine.uploadLogFile()` is ignored?

### ISSUE THREAD

**Issue by sunweiyang** [AgoraIO-Extensions/react-native-agora#777]
In the latest version of this package (4.x), `IRtcEngine.uploadLogFile()` is now an `@ignore` method. What is the new canonical way to get Agora SDK logs to Agora? More generally, is this functionality still supported?

**Comment by guoxianzhe** [comment]
@sunweiyang Currently we don't support this api in 4.x. Please submit a ticket to [Agora Support](https://www.agora.io/en/customer-support/) for further help of this feature.
