### ISSUE TITLE
Rounded Corners?

### ISSUE THREAD

**Issue by AB-70** [AgoraIO-Extensions/react-native-agora#782]
Is there any way to get rounded corners on android for the RTC Surface View?

I've tried so many ways, including overflow: hidden on parent, masked view (from react-native-community package), and none of them seem to work. 

The video is always rendered with sharp corners and this doesn't align with my app's theme. 

Any help in this regard will be appreciated.

Using react native 0.73.5
React Native Agora: 4.3.0

**Comment by guoxianzhe** [comment]
@AB-70 Thanks for your PR, we will make a fully test and release it in the future , maybe in 4.4.0.

**Comment by guoxianzhe** [comment]
```ts
<View style={{ flex: 1, borderRadius: 50, overflow: 'hidden' }}>
  <RtcSurfaceView style={{ flex:1 }}/>
</View>
```
Without native side changes, I use these simple code can make borderRadius happen(tested in Android and iOS), so I will not add this in sdk.
So If you still get problems we can look into them again.

<img width="419" alt="image" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/53285945/18be00fd-c074-4010-9312-85958acd9d9e">
<img width="376" alt="image" src="https://github.com/AgoraIO-Extensions/react-native-agora/assets/53285945/6689dd5c-a4c4-4d26-a641-c515968a6fce">
