### ISSUE TITLE
Support PiP in IOS 

### ISSUE THREAD

**Issue by alejandro-geeksquare** [AgoraIO-Extensions/react-native-agora#791]
It is possible to enter PiP (Picture in picture) mode on IOS, we are connecting to the broadcast with RtcSurfaceView. Currently we have created a native module on Android that works correctly but on IOS we are using AVPictureInPictureController(playerLayer: playerLayer) but we cannot get it to detect the broadcast and enter PiP mode correctly. Thank you very much for the help

**Comment by guoxianzhe** [comment]
@alejandro-geeksquare . We are planning to release the PiP feature for the RN version, please wait for future updates.

**Comment by alejandro-geeksquare** [comment]
> @alejandro-geeksquare . We are planning to release the PiP feature for the RN version, please wait for future updates.

thank you so much. We are waiting to test the new functionality, to implement it in our application

**Comment by takuyanz** [comment]
> We are planning to release the PiP feature for the RN version, please wait for future updates.

@guoxianzhe any information about when this will be released ... ? 🤔

**Comment by guoxianzhe** [comment]
@takuyanz Currently, we are in development. Please wait for a while, and I will inform you once it is released.

**Comment by vishalyad16** [comment]
@alejandro-geeksquare  does pip support on android can you share the doc or sample code for reference ?

**Comment by guoxianzhe** [comment]
@vishalyad16 We will release pip soon, it will include Android and iOS.

**Comment by guoxianzhe** [comment]
Hi all, We are supported PiP in #820 [v4.3.2-build.5-rc.1](https://www.npmjs.com/package/react-native-agora/v/4.3.2-build.5-rc.1)

Here is examples: https://github.com/AgoraIO-Extensions/react-native-agora/tree/special/4.3/example/src/examples/advanced/PictureInPicture

And we will support this feature >=4.5.0 too

**Comment by NirajBharambe** [comment]
Is there any documentation in the same?
Also Do these type of versions in agora signify anything?
[4.3.2-build.5-rc.1]

**Comment by takuyanz** [comment]
@guoxianzhe 

Thanks for supporting PiP! 😄  I am just wondering same thing as @NirajBharambe 

> Also Do these type of versions in agora signify anything?

Should I wait for `4.3.2-build.5-rc.1` to be merged into main branch before using PiP in production?

**Comment by vishalyad16** [comment]
Thanks for the update! We’re definitely waiting for 4.3.2-build.5-rc.1 to be merged into the main branch before using PiP in production. Do you have any updates on when that might happen, or how we can use it in the meantime?

**Comment by guoxianzhe** [comment]
@takuyanz @vishalyad16  Yes, you can use it in production. I will update it into main in the future. I will let you guys know when I finsh.

**Comment by SukumarRN7** [comment]
@guoxianzhe 
love the work you guys are doing, appreciate it. 

Could you let us know when can this be merged to "main" ?.

**Comment by vietdung97** [comment]
hi @guoxianzhe Do you have any plans to merge this feature (4.3.2-build.5-rc.1) into the main branch?

**Comment by dunghoangpg** [comment]
Hey @guoxianzhe I followed the change in the dev/pip. It looks good and is very helpful to me, but I'm currently facing issues when pip is in background mode, as it freezes the video streaming. How can i handle it? Do you have any idea for it please help!
