### ISSUE TITLE
I want to see my own screen, how can I do that?

### ISSUE THREAD

**Issue by showtan001** [AgoraIO-Extensions/react-native-agora#796]
Set uid to 0, the displayed screen is black, and the other party's screen is normal.
```
<RtcSurfaceView
    zOrderMediaOverlay={true}
    canvas={{
      uid: 0,
      sourceType: VideoSourceType.VideoSourceRemote,
    }}
  />
```

Thanks!

**Comment by guoxianzhe** [comment]
@showtan001 If you want show local video , please change your sourceType to `VideoSourceType.VideoSourceCameraPrimary` for etc.

`VideoSourceType .VideoSourceRemote` is One remote video acquired by the network.
