### ISSUE TITLE
Problem with dimensions in the latest version

### ISSUE THREAD

**Issue by alejandro-geeksquare** [AgoraIO-Extensions/react-native-agora#797]
Moving from version 4.3.0-build.1 to 4.3.1 and 4.3.2 creates a problem with the dimensions of the RtcSurfaceView, which does not take 100% of the height of the device. This happens one in four times we try to connect, rendering the image in horizontal format. This has started. happen with upgrade from 4.3.0-buid.1 to 4.3.1

**Comment by guoxianzhe** [comment]
@alejandro-geeksquare Can you provide a simple code for reproduce and please let me know which platform occurs.

**Comment by alejandro-geeksquare** [comment]
@guoxianzhe It has only happened to me with Android devices

`import { useCallback, useEffect, useRef, useState } from "react"
import { Animated, Dimensions, ImageBackground, StyleSheet } from "react-native"
import {
  ChannelProfileType,
  ClientRoleType,
  ConnectionChangedReasonType,
  ConnectionStateType,
  createAgoraRtcEngine,
  IRtcEngineEx,
  LogFilterType,
  RemoteVideoState,
  RtcConnection,
  RtcSurfaceView,
  VideoSourceType
} from "react-native-agora"
import { useRecoilValue } from "recoil"

import { TokenResponse } from "src/models/liveShopping.model"
import { palette } from "src/theme/palette"

import { BID_STATUS } from "constants/enums"
import {
  useGetLiveQuery,
  useLazyGetAudienceTokenQuery,
  usePostAudienceTokenRenewMutation
} from "features/liveStreamApiSlice"

import { bidStatusAtom } from "../context/BidState"
import { liveMuteAtom, liveVolumeLevelAtom } from "../context/LiveState"
import useLive from "../hooks/useLive"

const { height } = Dimensions.get("screen")
export default function LiveScreenAudience({ liveId, initLive, coverLive }) {
  const [triggerGetAudienceToken] = useLazyGetAudienceTokenQuery()
  const [token, setToken] = useState<TokenResponse>()

  const getAudienceToken = useCallback(async () => {
    const audienceToken = await triggerGetAudienceToken(liveId).unwrap()
    setToken(audienceToken)
  }, [liveId])

  useEffect(() => {
    setToken(undefined)
    getAudienceToken()
  }, [liveId])

  if (!token) return null

  return (
    <LiveScreenAudienceWithToken
      liveId={liveId}
      initLive={initLive}
      token={token}
      coverLive={coverLive}
    />
  )
}

const appId = process.env.EXPO_PUBLIC_AGORA_ID

function LiveScreenAudienceWithToken({ liveId, initLive, token, coverLive }) {
  const status = useRecoilValue(bidStatusAtom)
  const liveMute = useRecoilValue(liveMuteAtom)
  const liveVolumeLever = useRecoilValue(liveVolumeLevelAtom)
  const [triggerGetAudienceRenewToken] = usePostAudienceTokenRenewMutation()

  const [remoteUser, setRemoteUser] = useState(0)
  const channelName = liveId
  const [initStream, setStateStream] = useState(false)

  const agoraEngineRef = useRef<IRtcEngineEx>(createAgoraRtcEngine() as IRtcEngineEx)

  useLive({
    id: liveId,
    client: agoraEngineRef.current
  })

  const initRtcEngine = useCallback(async (): Promise<void> => {
    if (token) {
      try {
        agoraEngineRef.current.leaveChannel()
        agoraEngineRef.current.initialize({
          appId,
          channelProfile: ChannelProfileType.ChannelProfileLiveBroadcasting
        })
        agoraEngineRef.current.setLogFile("./src/agorasdk.log")
        agoraEngineRef.current.setLogFilter(LogFilterType.LogFilterDebug)
        agoraEngineRef.current.muteRemoteVideoStream(token.uid, true)
        agoraEngineRef.current.enableLocalAudio(false)
        agoraEngineRef.current.joinChannel(token.token, channelName, token.uid, {
          clientRoleType: ClientRoleType.ClientRoleAudience,
          autoSubscribeVideo: true,
          autoSubscribeAudio: true
        })
      } catch (e) {
        console.error("error", e)
      }
    }
  }, [channelName])

  const initAllListener = useCallback(() => {
    agoraEngineRef.current.addListener(
      "onRemoteVideoStateChanged",
      (connection, remoteUid, state, reason, elapsed) => {
        console.info("onRemoteVideoStateChanged", connection, remoteUid, state, reason, elapsed)
        if (state === RemoteVideoState.RemoteVideoStateStarting) {
          setStateStream(false)
          setRemoteUser(remoteUid)
          setStateStream(true)
        } else if (state === RemoteVideoState.RemoteVideoStateStopped && remoteUid === remoteUser) {
          setStateStream(false)
        }
      }
    )
    agoraEngineRef.current.addListener(
      "onUserJoined",
      (connection: RtcConnection, remoteUid: number, elapsed: number) => {
        console.info(
          "onUserJoined",
          "connection",
          connection,
          "remoteUid",
          remoteUid,
          "elapsed",
          elapsed
        )
        if (
          connection.channelId === liveId &&
          (connection.localUid === token?.uid || token?.uid === 0)
        ) {
          setRemoteUser(remoteUid)
        }
      }
    )

    agoraEngineRef.current.addListener(
      "onConnectionStateChanged",
      (connection, state: ConnectionStateType, reason: ConnectionChangedReasonType) => {
        console.info("onConnectionStateChanged", connection, state, reason)
      }
    )

    agoraEngineRef.current.addListener("onTokenPrivilegeWillExpire", async () => {
      try {
        const newToken = await triggerGetAudienceRenewToken({
          id: liveId as string,
          uid: token?.uid
        }).unwrap()
        const res = agoraEngineRef.current.renewToken(newToken.token)
        console.info("status renew token", res)
      } catch (e) {
        console.error("error", e)
      }
    })
  }, [liveId, token?.uid, triggerGetAudienceRenewToken])

  const handleJoinFromApiStatus = useCallback((status: number) => {
    if (!initStream) return
    if (status === BID_STATUS.CLOSED) {
      if (agoraEngineRef.current) {
        agoraEngineRef.current.leaveChannel()
        setRemoteUser(0)
      }
    }
  }, [])

  useEffect(() => {
    ;(async () => {
      await initRtcEngine()
    })()
    const engineCopy = agoraEngineRef.current
    initAllListener()
    handleJoinFromApiStatus(status)
    return () => {
      engineCopy.muteAllRemoteVideoStreams(true)
      engineCopy.muteAllRemoteAudioStreams(true)
      engineCopy.removeAllListeners()
    }
  }, [handleJoinFromApiStatus, initAllListener, initRtcEngine])

  return (
    <>
      {initStream && initLive && status !== BID_STATUS.CLOSED ? (
        <RtcSurfaceView
           style={{
            width: "100%",
            height,
            opacity: 1
          }}
          zOrderMediaOverlay={remoteUser !== 0}
          canvas={{ uid: remoteUser, sourceType: VideoSourceType.VideoSourceRemote }}
        />
      ) : (
        <View
          style={[
            {
              flex: 1,
              backgroundColor: palette.component.backgrounds.dark.primary,
              opacity: fadeAnim
            }
          ]}
        >
      )}
    </>
  )
}`

**Comment by guoxianzhe** [comment]
@alejandro-geeksquare I can not reproduce this in Oneplus 7T PRO(Android 11). Can you check logs when `does not take 100% of the height of the device` ? You can found width and height in logs and check the value is what you want.

**Comment by alejandro-geeksquare** [comment]
@guoxianzhe If the same thing happens with height 100%, it doesn't always happen, after several times the transmission starts it looks like this. It only happens with versions 4.3.1 and 4.3.2

**Comment by alejandro-geeksquare** [comment]
https://github.com/AgoraIO-Extensions/react-native-agora/assets/128458985/13f18a55-6e07-4778-85c6-eed015ed2933

**Comment by guoxianzhe** [comment]
@alejandro-geeksquare pls try to set RenderMode in `<RtcSurfaceView canvas={{ renderMode: RenderModeType.RenderModeHidden}}/>`

**Comment by alejandro-geeksquare** [comment]
@guoxianzhe I have tried it and it still happens

**Comment by alejandro-geeksquare** [comment]
It has not yet been resolved

**Comment by guoxianzhe** [comment]
@alejandro-geeksquare Sorry, I can not reproduce with this code,https://github.com/AgoraIO-Extensions/react-native-agora/commit/6c613ff7f1d1aa339b468c63d39f79951e9122aa please check
