### ISSUE TITLE
joinChannel with uid is "string" (react native)

### ISSUE THREAD

**Issue by duongquang1611** [AgoraIO-Extensions/react-native-agora#805]
I see the uid used in joinChannel on mobile (react-native) is number, is there a way to use uid as string on react native? Because our current system has guest users who can watch live stream and we need to join live stream as guest = self-generated uid is string so if on mobile uid is number then it seems we can't watch live stream

**Comment by guoxianzhe** [comment]
@duongquang1611 see https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/example/src/examples/basic/StringUid/StringUid.tsx#L87
