### ISSUE TITLE
Android: Capture audio in background (Foreground service)

### ISSUE THREAD

**Issue by jfbourne** [AgoraIO-Extensions/react-native-agora#807]
**Describe the bug**
The application stops getting audio from the microphone if it is put in the background. 

**To Reproduce**
1. Join a Voice Calling call
2. Put the application in the background
3. Wait about 5s
4. The other user doesn't hear you

**Expected behavior**
The app continues to function when in the background

**Smartphone (please complete the following information):**
 - Device: Galaxy A14
 - SDK: 34

**Additional context**
I already trying adding `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` to the manifest and added `setParameters('{"che.audio.opensl":true}');` to the engine but it does not work.

**Comment by guoxianzhe** [comment]
https://docs.agora.io/en/help/quality-issues/android_background
@jfbourne pls check here

**Comment by jfbourne** [comment]
@guoxianzhe thanks. I did came across that post but, that means I have to implement some android native code and bridge that back to react-native. I’m want to see if agora-react-native already implements some solution that won’t require the community to write custom native code.

**Comment by guoxianzhe** [comment]
@jfbourne understood, We will consider it.

**Comment by phoriachyi** [comment]
Any updates here if it would be implemented on the sdk side?

**Comment by sankparatkar** [comment]
This is still not implemented, has to be one of the important things for the react native sdk. I'm sure the team is onto it
