### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Dave-Forti** [AgoraIO-Extensions/react-native-agora#812]
**Describe the bug**
I am not able to find the proper resources to integrate this library in a react native app. 
The documentation: https://docs.agora.io/en/video-calling/get-started/get-started-sdk?platform=react-native#understand-the-tech

is not up to date, as the code snippets don't work at all. 

In the join method snippet, the property ChannelProfileBroadcasting has been changed to ChannelProfileLiveBroadcasting. 
'audienceLatencyLevelType' does not exist in type 'ChannelMediaOptions', it has been replaced by 'audienceLatencyLevel'
'AudienceLatencyLevelType.AudienceLatencyLevelUltraLowLatency' is not even imported by default in the snippet
`
// Define the join method called after clicking the join channel button
    const join = async () => {
        if (isJoined) {
            return;
        }
        try {
            // Set the channel profile type to live broadcasting after joining the channel
            agoraEngineRef.current?.setChannelProfile(
                ChannelProfileType.ChannelProfileBroadcasting,
            );
            // Call the joinChannel method to join the channel
            agoraEngineRef.current?.joinChannel(token, channelName, uid, {
                // Set the user role to broadcaster
                clientRoleType: ClientRoleType.ClientRoleBroadcaster,
                audienceLatencyLevelType: AudienceLatencyLevelType.AudienceLatencyLevelUltraLowLatency
            });
        } catch (e) {
            console.log(e);
        }
    };
`

**Screenshots**
![image](https://github.com/user-attachments/assets/4bc0bd7e-01ec-432d-8281-ab3026d52384)

**Additional context**
I also event tried to use Gemini, Chatgpt and Claude 3.5, and all of them hallucinate code mix-matched with the websdk and Properties that don't exist in this library

**Comment by Dave-Forti** [comment]
Seems like the outdated documentation has been an issue for a while: 
https://stackoverflow.com/questions/77342946/implementation-of-audio-video-calling-while-using-agora-sdk-in-react-native

**Comment by saudsami** [comment]
Hi @Dave-Forti 
We have updated the React Native Quickstart doc with the latest code samples. 
Regards
