### ISSUE TITLE
I'm unable to build the IPA or even run the build.

### ISSUE THREAD

**Issue by vishalyad16** [AgoraIO-Extensions/react-native-agora#821]
Facing issue

ld: warning: ignoring duplicate libraries: '-lc++'
ld: framework 'AgoraRtmKit' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by guoxianzhe** [comment]
@vishalyad16 Can you tell me the version?

**Comment by vishalyad16** [comment]
"react-native": "^0.73.8",
"react-native-agora": "^4.3.2",
"agora-react-native-rtm": "^1.5.1",

**Comment by vishalyad16** [comment]
@guoxianzhe, can you please tell me what I'm doing wrong here?

**Comment by guoxianzhe** [comment]
@vishalyad16 I saw you are using agora-react-native-rtm. 

> framework 'AgoraRtmKit' not found

this issue is from https://github.com/AgoraIO/agora-react-native-rtm , can you follow the [Documentation](https://github.com/AgoraIO/agora-react-native-rtm?tab=readme-ov-file#documentation) and try again?

**Comment by vishalyad16** [comment]
Thanks, @guoxianzhe! This resolved the issue.
