### ISSUE TITLE
onJoinChannelSuccess listener is not working in release mode android 

### ISSUE THREAD

**Issue by tayyabasikander** [AgoraIO-Extensions/react-native-agora#825]
**Describe the bug**
The listener onJoinChannelSuccess is not working in release mode but on the other user side it shows that the user has joined  who is in debug mode

**To Reproduce**
1. join a channel from a debug build android
2. join the same channel from release build
3. onJoinChannelSuccess won't get fired on release mode but works fine in debug mode

**Comment by guoxianzhe** [comment]
@tayyabasikander 
Can you please check as follow steps:

1. Please check if your two devices are using the same app ID.
2. Please check if your two devices are using the same UID data type. Number UIDs can only communicate with number UIDs, and string UIDs can only communicate with string UIDs.
