### ISSUE TITLE
AgoraAiNoiseSuppressionExtension.framework contains bitcode

### ISSUE THREAD

**Issue by Mrzhang007** [AgoraIO-Extensions/react-native-agora#826]
I encounter this issue when archive my app with xcode 16。
because bitcode support has been removed at xcode 16.

Asset validation failed (90482) Invalid Executable. The executable 'xxxx.app/Frameworks/AgoraAiNoiseSuppressionExtension.framework/AgoraAiNoiseSuppressionExtension' contains bitcode. (ID: 633b24da-b9da-4787-b141-f869b471d16e)

**Comment by guoxianzhe** [comment]
@Mrzhang007 Can you tell me the version?
you can remove bitcode by yourself as follow:

https://stackoverflow.com/questions/78993520/invalid-executable-the-executable-appname-app-frameworks-hermes-framework-herm
