### ISSUE TITLE
Get blank view when using two view of RtcLocalView,SurfaceView

### ISSUE THREAD

**Issue by Khoa69** [AgoraIO-Extensions/react-native-agora#831]
Get blank screen when using two view of RtcLocalView,SurfaceView() in one screen. Only one of that show and the other one shows blank.
react-native-agora: 3.7.1

**Comment by guoxianzhe** [comment]
@Khoa69 v3.x can not shows multi view at the same time, you can use 4.x with setupMode: VideoViewSetupMode.VideoViewSetupAdd

**Comment by Khoa69** [comment]
@guoxianzhe version 4.x how can I manually link in android guys.

**Comment by guoxianzhe** [comment]
@Khoa69 check this:

https://docs.agora.io/en/video-calling/overview/migration-guide?platform=react-native
https://docs.agora.io/en/video-calling/get-started/get-started-sdk?platform=react-native#integrate-the-sdk

And React Native 0.60.0 and later support automatic linking of native modules. Manual linking is not recommended. See [Autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) for details

**Comment by Khoa69** [comment]
@guoxianzhe, sorry, my project accept manually for build, can't use automatic link, the manually link in android is possible for v4.x

**Comment by guoxianzhe** [comment]
@Khoa69  Sorry, I didn't test manual link in v4

**Comment by Khoa69** [comment]
@guoxianzhe, oh I tested manually link in android with v4.x but didn't work, Can you fix manually link error, please.

**Comment by Khoa69** [comment]
@guoxianzhe, react-native version: 0.64.4
