### ISSUE TITLE
Check duplicate identity 

### ISSUE THREAD

**Issue by Khoa69** [AgoraIO-Extensions/react-native-agora#832]
react-native-agora : 3.7.1

How can I check for duplicate identity when joining another device?

Actually:
- Join room in the another device fail.

Expected:
- Return the error in the previous identity.
- The newest identity join room successful

**Comment by guoxianzhe** [comment]
@Khoa69 pls check the [document](https://api-ref.agora.io/en/voice-sdk/react-native/3.x/enums/errorcode.html#joinchannelrejected) first
