### ISSUE TITLE
Android Build failed

### ISSUE THREAD

**Issue by Snehasish7080** [AgoraIO-Extensions/react-native-agora#838]
On React native 0.76.2 Android build is failed with an error

`Namespace 'io.agora.rtc' is used in multiple modules and/or libraries: io.agora.rtc:full-sdk:4.4.1, io.agora.rtc:iris-rtc:4.4.0-build.6. Please ensure that all modules and libraries have a unique namespace.`

**Comment by guoxianzhe** [comment]
@Snehasish7080 I can not reproduce this issue on https://github.com/guoxianzhe/reproducer-react-native
Can you try?

**Comment by Snehasish7080** [comment]
@guoxianzhe Thanks it was some other issue which causing this. Now it is working fine.
