### ISSUE TITLE
onTokenPrivilageWillExpire event is still not triggering

### ISSUE THREAD

**Issue by Ullas-A-2000** [AgoraIO-Extensions/react-native-agora#840]
@zhangtao1104 @LichKing-2234 @guoxianzhe 
seems to be issue with sdk please check

**Comment by guoxianzhe** [comment]
@Ullas-A-2000 please tell me the version, thx!

**Comment by Ullas-A-2000** [comment]
"react-native-agora": "^4.4.0",
    "react-native-agora-chat": "^1.3.0-alpha.0",
    
    chat sdk works well **onTokenPrivilageWillExpire**  for this event
    Rtm sdk for signalling you provide even that works for this event
    the call sdk is not working (i checked these sdks in both web and react native , both sides im facing same issue with rtc)
    
    
    below is my react native integration (i removed config creds please ignore it)
    @guoxianzhe please provide an insight thx!
    
    
    
    
    
    
import { useCallback, useEffect, useRef, useState } from 'react';
import createAgoraRtcEngine, {
  ChannelProfileType,
  ErrorCodeType,
  IRtcEngineEx,
  RtcConnection,
  RtcStats,
  UserOfflineReasonType,
} from 'react-native-agora';

// import Config from '../../../config/agora.config';
import { askMediaAccess } from '../utils/permissions';

const Config = {
    appId: '',
    token: '',
    channelId: '',
    uid: 123,
    logFilePath: '',
  };

const useInitRtcEngine = (
  enableVideo: boolean,
  listenUserJoinOrLeave: boolean = true
) => {
  const [appId] = useState(Config.appId);
  const [channelId, setChannelId] = useState(Config.channelId);
  const [token] = useState(Config.token);
  const [uid, setUid] = useState(Config.uid);
  const [joinChannelSuccess, setJoinChannelSuccess] = useState(false);
  const [remoteUsers, setRemoteUsers] = useState<number[]>([]);
  const [startPreview, setStartPreview] = useState(false);

  const engine = useRef<IRtcEngineEx>(createAgoraRtcEngine() as IRtcEngineEx);

  const initRtcEngine = useCallback(async () => {
    if (!appId) {
      console.log('appId is invalid');
    }

    engine.current.initialize({
      appId,
      logConfig: { filePath: Config.logFilePath },
      // Should use ChannelProfileLiveBroadcasting on most of cases
      channelProfile: ChannelProfileType.ChannelProfileLiveBroadcasting,
    });

    // Need granted the microphone permission
    await askMediaAccess(['android.permission.RECORD_AUDIO']);

    // Only need to enable audio on this case
    engine.current.enableAudio();

    if (enableVideo) {
      // Need granted the camera permission
      await askMediaAccess(['android.permission.CAMERA']);

      // Need to enable video on this case
      // If you only call `enableAudio`, only relay the audio stream to the target channel
      engine.current.enableVideo();

      // Start preview before joinChannel
      engine.current.startPreview();
      setStartPreview(true);
    }
  }, [appId, enableVideo]);

  const onRequestToken = (connection: RtcConnection) => {
    console.log('request token');
};

  const onError = useCallback((err: ErrorCodeType, msg: string) => {
    console.log('onError', 'err', err, 'msg', msg);
  }, []);

  const onJoinChannelSuccess = useCallback(
    (connection: RtcConnection, elapsed: number) => {
      if (
        connection.channelId === channelId &&
        (connection.localUid === uid || uid === 0)
      ) {
        setJoinChannelSuccess(true);
      }
    },
    [channelId, uid]
  );

  const onTokenPrivilegeWillExpire = useCallback(
    (connection: RtcConnection, token: string) => {
        console.log('will expire')
    },
    []
  );



  const onLeaveChannel = useCallback(
    (connection: RtcConnection, stats: RtcStats) => {
      console.log('onLeaveChannel', 'connection', connection, 'stats', stats);
      if (
        connection.channelId === channelId &&
        (connection.localUid === uid || uid === 0)
      ) {
        setJoinChannelSuccess(false);
        setRemoteUsers([]);
      }
    },
    [channelId, uid]
  );

  const onUserJoined = useCallback(
    (connection: RtcConnection, remoteUid: number, elapsed: number) => {
      console.log(
        'onUserJoined',
        'connection',
        connection,
        'remoteUid',
        remoteUid,
        'elapsed',
        elapsed
      );
      if (
        connection.channelId === channelId &&
        (connection.localUid === uid || uid === 0)
      ) {
        setRemoteUsers((prev) => {
          if (prev === undefined) {return [];}
          return [...prev, remoteUid];
        });
      }
    },
    [channelId, uid]
  );

  const onUserOffline = useCallback(
    (
      connection: RtcConnection,
      remoteUid: number,
      reason: UserOfflineReasonType
    ) => {
      console.log(
        'onUserOffline',
        'connection',
        connection,
        'remoteUid',
        remoteUid,
        'reason',
        reason
      );
      if (
        connection.channelId === channelId &&
        (connection.localUid === uid || uid === 0)
      ) {
        setRemoteUsers((prev) => {
          if (prev === undefined) {return [];}
          return prev!.filter((value) => value !== remoteUid);
        });
      }
    },
    [channelId, uid]
  );

  useEffect(() => {
    (async () => {
      await initRtcEngine();
    })();

    const engineCopy = engine.current;
    return () => {
      engineCopy.release();
    };
  }, [engine, initRtcEngine]);

  useEffect(() => {
    engine.current.addListener('onError', onError);
    engine.current.addListener('onJoinChannelSuccess', onJoinChannelSuccess);
    engine.current.addListener('onLeaveChannel', onLeaveChannel);
    if (listenUserJoinOrLeave) {
      engine.current.addListener('onUserJoined', onUserJoined);
      engine.current.addListener('onUserOffline', onUserOffline);
      engine.current.addListener('onTokenPrivilegeWillExpire', onTokenPrivilegeWillExpire);
    }

    const engineCopy = engine.current;
    return () => {
      engineCopy.removeListener('onError', onError);
      engineCopy.removeListener('onJoinChannelSuccess', onJoinChannelSuccess);
      engineCopy.removeListener('onLeaveChannel', onLeaveChannel);
      engineCopy.removeListener('onTokenPrivilegeWillExpire', onTokenPrivilegeWillExpire);;
      if (listenUserJoinOrLeave) {
        engineCopy.removeListener('onUserJoined', onUserJoined);
        engineCopy.removeListener('onUserOffline', onUserOffline);
      }
    };
  }, [
    engine,
    initRtcEngine,
    onError,
    onJoinChannelSuccess,
    onLeaveChannel,
    onUserJoined,
    onUserOffline,
    listenUserJoinOrLeave,
    onTokenPrivilegeWillExpire,
  ]);

  useEffect(() => {
    engine.current.addListener('onRequestToken', onRequestToken);
  }, [onRequestToken]);

  return {
    appId,
    channelId,
    setChannelId,
    token,
    uid,
    setUid,
    joinChannelSuccess,
    setJoinChannelSuccess,
    remoteUsers,
    setRemoteUsers,
    startPreview,
    engine,
  };
};
export default useInitRtcEngine;

**Comment by guoxianzhe** [comment]
@Ullas-A-2000 Can you receive the `onRequestToken` event?

**Comment by Ullas-A-2000** [comment]
@guoxianzhe no even onRequestToken this dosent work

**Comment by Ullas-A-2000** [comment]
@guoxianzhe no even onRequestToken this dosent work

**Comment by guoxianzhe** [comment]
@Ullas-A-2000 I think maybe the token doesn't expired at all. Why do you think your token has expired?

**Comment by Ullas-A-2000** [comment]
@guoxianzhe i manually generated the token from backend manually setting expiry time to the token as 100 secs
and then tested this trigger function **onTokenPrivilageWillExpire**
in 3 sdk you provide

"react-native-agora": "^4.4.0",
"react-native-agora-chat": "^1.3.0-alpha.0",
agora-react-native-rtm

it works on agora-react-native-rtm & react-native-agora-chat 
but it dint work on react-native-agora

even i thought token dint expire but when i cut the call and try to rejoin it throes error 109 which corresponds to token expiry

**Comment by guoxianzhe** [comment]
@Ullas-A-2000  Are you using AccessToken2? Did you follow this doc to upgrade your token ?

https://docs.agora.io/en/3.x/video-calling/reference/upgrade-token

**Comment by Ullas-A-2000** [comment]
@guoxianzhe  
can you please provide a node js approach , our servers are in node, te one you mentioned supports go lang
but as you mentioned below is my node js code of agora token creation


```
const {
  RtcTokenBuilder,
  RtcRole,
  RtmTokenBuilder,
  ChatTokenBuilder
} = require('agora-token')

// RTC -> real time call [ audio & video calls ]
// RTM -> real time message [ signalling ]
// Chat -> real time chat [ text messages ]

class AgoraService {
  #appId
  #appCertificate
  #role = RtcRole.PUBLISHER
  #expiry
  #timeOfExpiryFromNow
  #uid
  #channelName

  #calculateFutureTimeStamp() {
    const currentTimeStamp = Math.floor(Date.now() / 1000)
    this.#timeOfExpiryFromNow = currentTimeStamp + this.#expiry
  }

  /**
   * Create a new instance of the AgoraService
   * @param {Object} opts options to create the service
   * @param {number} opts.uid user id
   * @param {string} opts.channelName channel name
   * @param {number} opts.expiry time in seconds for the token to expire
   * @hideconstructor
   */
  constructor({ uid, channelName, expiry }) {
    this.#uid = uid
    this.#channelName = channelName
    this.#expiry = expiry

    this.#appId = '0d7d9ed73f454e00acc02ed1d3d47ca5'
    this.#appCertificate = '8c8161b958924ceda7b2d4f85e181c69'

    this.#calculateFutureTimeStamp()
  }

  /**
   * Generate a token for the Real-time Communication (RTC) service.
   * @return {string} the token
   */
  generateRtcToken() {
    const __rtcToken = RtcTokenBuilder.buildTokenWithUid(
      this.#appId,
      this.#appCertificate,
      this.#channelName,
      this.#uid,
      this.#role,
      this.#expiry,
      this.#timeOfExpiryFromNow
    )
    return __rtcToken
  }

module.exports = { AgoraService }
```

**Comment by guoxianzhe** [comment]
@Ullas-A-2000 Here is others language version : https://docs.agora.io/en/video-calling/get-started/authentication-workflow?platform=react-native#implement-basic-authentication

**Comment by Ullas-A-2000** [comment]
@guoxianzhe will try this and let you know thx!

**Comment by Ullas-A-2000** [comment]
@guoxianzhe 
this is working perfectly fine, thanks for the support!
